import { LegacyCommentThread } from 'platform-bible-utils';

const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const twoDaysAgo = new Date(today);
twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);

export const sampleComments: LegacyCommentThread[] = [
  // #region Test comments pulled from zzz6
  {
    id: 'c5bfd1ac',
    comments: [
      {
        id: 'c5bfd1ac/TJ Couch/2026-01-28T10:35:12.1345682-06:00',
        isRead: true,
        thread: 'c5bfd1ac',
        user: 'TJ Couch',
        verseRef: 'MAT 1:23',
        language: 'hwc-AQ',
        date: '2026-01-28T10:35:12.1345682-06:00',
        deleted: false,
        selectedText: 'neva',
        startPosition: 78,
        contextBefore: ' One young wahine \\q2 Who ',
        contextAfter: ' sleep wit nobody, \\q Goin',
        verse:
          '\\v 23 \\x - \\xo 1:23: \\xo*\\xt Isa 7:14\\xt*\\x*“Lissen! One young wahine \\q2 Who neva sleep wit nobody, \\q Goin get hapai. \\q2 She goin born one boy. \\q Dey goin name him Emmanuel.” \\m (“Emmanuel” stay mean, “God stay hea now wit us guys.”) \\p ',
        extraHeadingInfo: '￼￼￼',
        hideInTextWindow: false,
        contents:
          "<blockquote lang='hwc-AQ' style='text-align:left'><p>Test <b>bold</b><i>italic</i> stuff</p></blockquote>",
      },
      {
        id: 'c5bfd1ac/TJ Couch/2026-01-28T11:08:45.7800125-06:00',
        isRead: true,
        thread: 'c5bfd1ac',
        user: 'TJ Couch',
        verseRef: 'MAT 1:23',
        language: '',
        date: '2026-01-28T11:08:45.7800125-06:00',
        deleted: false,
        selectedText: 'neva',
        startPosition: 78,
        contextBefore: ' One young wahine \\q2 Who ',
        contextAfter: ' sleep wit nobody, \\q Goin',
        extraHeadingInfo: '￼￼￼',
        hideInTextWindow: false,
        contents:
          "<blockquote lang='hwc-AQ' style='text-align:left'><p>stuff</p><p>n things</p></blockquote>",
      },
      {
        id: 'c5bfd1ac/TJ Couch/2026-01-29T10:13:29.5668846-06:00',
        isRead: true,
        thread: 'c5bfd1ac',
        user: 'TJ Couch',
        verseRef: 'MAT 1:23',
        language: '',
        date: '2026-01-29T10:13:29.5668846-06:00',
        deleted: false,
        selectedText: 'neva',
        startPosition: 78,
        contextBefore: ' One young wahine \\q2 Who ',
        contextAfter: ' sleep wit nobody, \\q Goin',
        extraHeadingInfo: '￼￼￼',
        hideInTextWindow: false,
        contents:
          "<blockquote lang='hwc-AQ' style='text-align:left'><p>Another reply</p></blockquote>",
      },
    ],
    status: 'Todo',
    type: 'Normal',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    modifiedDate: '2026-01-29T10:13:29.5668846-06:00',
    verseRef: 'MAT 1:23',
    assignedUser: '',
    isRead: true,
  },
  {
    id: '19499e40',
    comments: [
      {
        id: '19499e40/TJ Couch/2024-08-21T14:11:40.6051574-05:00',
        isRead: true,
        thread: '19499e40',
        user: 'TJ Couch',
        verseRef: 'GEN 1:1',
        language: '',
        date: '2024-08-21T14:11:40.6051574-05:00',
        deleted: false,
        startPosition: 0,
        status: 'Todo',
        type: 'Conflict',
        conflictType: 'verseText',
        verse:
          '\\v 1 Da wait a minuteeeee tttttttime wen eryting had start, God make da sky an da world. ',
        extraHeadingInfo: '￼￼￼',
        hideInTextWindow: false,
        contents:
          "<blockquote lang='hwc-AQ' style='text-align:left'><p>Two different people made conflicting changes in this verse.</p><p><span lang='hwc-AQ'>\\v 1 Da wait a <s>minuteeeee </s><u>minute </u>time wen eryting had start, God make da sky an da world. </span></p></blockquote>",
      },
      {
        id: '19499e40/TJ Couch/2024-08-23T14:29:35.4874426-05:00',
        isRead: true,
        thread: '19499e40',
        user: 'TJ Couch',
        verseRef: 'GEN 1:1',
        language: 'hwc-AQ',
        date: '2024-08-23T14:29:35.4874426-05:00',
        deleted: false,
        startPosition: 0,
        status: 'Resolved',
        type: 'Conflict',
        extraHeadingInfo: '￼￼￼',
        hideInTextWindow: false,
        contents: "<blockquote lang='hwc-AQ' style='text-align:left'></blockquote>",
      },
      {
        id: '19499e40/TJ Couch/2024-08-23T14:38:45.3188613-05:00',
        isRead: true,
        thread: '19499e40',
        user: 'TJ Couch',
        verseRef: 'GEN 1:1',
        language: 'hwc-AQ',
        date: '2024-08-23T14:38:45.3188613-05:00',
        deleted: false,
        startPosition: 0,
        type: 'Conflict',
        verse:
          '\\v 1 Da wait aaaa minute tttttttime wen eryting had start, God make da sky an da world. ',
        extraHeadingInfo: '￼￼￼',
        hideInTextWindow: false,
        contents: "<blockquote lang='hwc-AQ' style='text-align:left'></blockquote>",
      },
    ],
    status: 'Resolved',
    type: 'Conflict',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    modifiedDate: '2024-08-23T14:38:45.3188613-05:00',
    verseRef: 'GEN 1:1',
    assignedUser: '',
    isRead: true,
  },
  {
    id: 'c0b0e523',
    comments: [
      {
        id: 'c0b0e523/TJ Couch/2024-07-31T09:49:04.7798653-05:00',
        isRead: false,
        thread: 'c0b0e523',
        user: 'TJ Couch',
        verseRef: 'MRK 2:1',
        language: '',
        date: '2024-07-31T09:49:04.7798653-05:00',
        deleted: false,
        startPosition: 0,
        status: 'Todo',
        type: 'Conflict',
        conflictType: 'verseText',
        verse:
          '\\v 1 Afta couple days, JJJJJJesus go back Capernaum wea he wen stay befoa. Da peopo hear dat Jesus stay home now. ',
        extraHeadingInfo: '￼￼￼',
        hideInTextWindow: false,
        contents:
          "<blockquote lang='hwc-AQ' style='text-align:left'><p>TJ Couch edited this verse on two different machines.</p><p><span lang='hwc-AQ'>\\v 1 Afta couple days, Jesus go back <s>Capernaum </s><u>Capernaummmm </u>wea he wen stay befoa. Da peopo hear dat Jesus stay home now. </span></p></blockquote>",
      },
      {
        id: 'c0b0e523/TJ Couch/2024-07-31T09:49:45.2006000-05:00',
        isRead: false,
        thread: 'c0b0e523',
        user: 'TJ Couch',
        verseRef: 'MRK 2:1',
        language: 'hwc-AQ',
        date: '2024-07-31T09:49:45.2006000-05:00',
        deleted: false,
        startPosition: 0,
        status: 'Resolved',
        type: 'Conflict',
        extraHeadingInfo: '￼￼￼',
        hideInTextWindow: false,
        contents: "<blockquote lang='hwc-AQ' style='text-align:left'></blockquote>",
      },
    ],
    status: 'Resolved',
    type: 'Conflict',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    modifiedDate: '2024-07-31T09:49:45.2006-05:00',
    verseRef: 'MRK 2:1',
    assignedUser: '',
    isRead: false,
  },
  // #endregion Test comments pulled from zzz6
  // #region sample comments with some old data
  {
    id: 'thread-1',
    comments: [
      {
        id: '1',
        user: 'Charlie Delta',
        contents:
          '<p>Consider revising this portion for clarity:</p><blockquote>God is our refuge</blockquote><p>Maybe we could expand on what &ldquo;refuge&rdquo; means in this context? Some target languages might need a more explicit description.</p>',
        date: yesterday.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: true,
        language: 'en',
        startPosition: 0,
        thread: 'thread-1',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: 'God is our refuge',
      },
      {
        id: '2',
        user: 'Beth Bee',
        contents:
          '<p>I agree with Charlie. In some languages, the word for "refuge" might not exist, so we may need to use a descriptive phrase like <strong>safe place</strong> or <em>shelter from danger</em>.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: true,
        language: 'en',
        startPosition: 0,
        thread: 'thread-1',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
      },
      {
        id: '3',
        user: 'David Echo',
        contents:
          '<blockquote><p>Good points! Let&apos;s make sure to add a note for translators about this. Also, should we clarify what "trouble" means in this context?</p></blockquote>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: true,
        language: 'en',
        startPosition: 0,
        thread: 'thread-1',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
      },
    ],
    status: 'Unspecified',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: yesterday.toISOString(),
    verseRef: 'PSA 46:1',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    isRead: true,
  },
  {
    id: 'thread-2',
    comments: [
      {
        id: '4',
        user: 'Eve Fox',
        contents:
          '<h1>Translation Workshop Notes</h1><h2>1. Key terms identified:</h2><ul><li>refuge (<span dir="rtl">מַחֲסֶה</span>)</li><li>strength (<span dir="rtl">עֹז</span>)</li><li>trouble (<span dir="rtl">צָרָה</span>)</li></ul><h2>2. Alternative renderings to consider:</h2><ul><li>&ldquo;safe place&rdquo; for &ldquo;refuge&rdquo;</li><li>&ldquo;power&rdquo; for &ldquo;strength&rdquo;</li><li>&ldquo;difficult times&rdquo; for &ldquo;trouble&rdquo;</li></ul><h2>3. Cultural considerations:</h2><ul><li>Military imagery</li><li>Ancient city fortifications</li><li>Divine protection metaphors</li></ul>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-2',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
      },
      {
        id: '5',
        user: 'Charlie Delta',
        contents:
          '<p>Thanks for the summary, Eve! I think the cultural notes are especially helpful for teams working in different regions.</p>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-2',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
      },
      {
        id: '6',
        user: 'Beth Bee',
        contents:
          '<p>One more suggestion: should we add a note about the poetic structure of this Psalms? It might help translators preserve the literary feel.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-2',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: 'Frank Graham',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'PSA 46:1',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: true,
    isConsultantNote: false,
    isRead: false,
  },
  {
    id: 'thread-3',
    comments: [
      {
        id: '7',
        user: 'Frank Graham',
        contents: '<p>This verse is a great encouragement. No changes needed from my side.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-3',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'PSA 46:1',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    isRead: false,
  },
  {
    id: 'thread-4',
    comments: [
      {
        id: '8',
        user: 'Allison Park',
        contents:
          '<p>Thanks for the summary, Eve! I think the cultural notes are especially helpful for teams working in different regions.</p>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-4',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'PSA 46:1',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    isRead: false,
  },
  {
    id: 'thread-5',
    comments: [
      {
        id: '9a',
        user: 'Jane Doe',
        contents: '<p>This verse is a great encouragement. No changes needed from my side.</p>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-5',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
      },
      {
        id: '9b',
        user: 'Checker One',
        contents: 'Agreed, resolving this thread.',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-5',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
        status: 'Resolved',
      },
      {
        id: '9c',
        user: 'Checker Two',
        contents: 'I believe we should reconsider',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        isRead: false,
        startPosition: 0,
        thread: 'thread-5',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
        status: 'Todo',
      },
      {
        id: '9d',
        user: 'Checker One',
        contents: 'As discussed offline, we can resolve this thread',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-5',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
        status: 'Resolved',
      },
      {
        id: '9e',
        user: 'Checker Two',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-5',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
        status: 'Todo',
        contents: '',
      },
      {
        id: '9f',
        user: 'Checker One',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-5',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'PSA 46:1',
        selectedText: '',
        status: 'Resolved',
        contents: '',
      },
    ],
    status: 'Resolved',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'PSA 46:1',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    isRead: false,
  },
  {
    id: 'thread-6',
    comments: [
      {
        id: '10',
        user: 'Grace Hill',
        contents:
          '<p>This verse presents some interesting translation challenges. The phrase "will not fear" is an emphatic statement in Hebrew. How should we handle this in languages that don\'t have this kind of emphatic negation?</p>',
        date: yesterday.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-6',
        verse:
          'Therefore we will not fear, though the earth be removed, and though the mountains be carried into the midst of the sea;',
        verseRef: 'PSA 46:2',
        selectedText: 'will not fear',
      },
      {
        id: '11',
        user: 'Allison Park',
        contents:
          '<p>Great question! I think we need to consider the emotional intensity here. The Hebrew (<span dir="rtl">לֹא נִירָא</span>) is more than just "we will not be afraid" - it\'s almost defiant in its confidence.</p>',
        date: yesterday.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-6',
        verse:
          'Therefore we will not fear, though the earth be removed, and though the mountains be carried into the midst of the sea;',
        verseRef: 'PSA 46:2',
        selectedText: '',
      },
      {
        id: '12',
        user: 'David Echo',
        contents:
          '<p>The apocalyptic imagery here is also striking - "earth be removed" and "mountains carried into the sea." These are cosmic upheavals that represent the most extreme circumstances possible. Should we maintain this hyperbolic language or adapt it for cultures unfamiliar with such imagery?</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-6',
        verse:
          'Therefore we will not fear, though the earth be removed, and though the mountains be carried into the midst of the sea;',
        verseRef: 'PSA 46:2',
        selectedText:
          'earth be removed, and though the mountains be carried into the midst of the sea',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: 'Grace Hill',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'PSA 46:2',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    isRead: false,
  },
  {
    id: 'thread-7',
    comments: [
      {
        id: '13',
        user: 'Henry Kim',
        contents:
          "<p>The river imagery in this verse is beautiful, but I'm wondering about the cultural context. In ancient Jerusalem, there wasn't a major river. This seems to be referring to something beyond the literal geography.</p>",
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-7',
        verse:
          'There is a river, the streams of which make glad the city of God, the holy place of the tabernacles of the Most High.',
        verseRef: 'PSA 46:4',
        selectedText: 'There is a river, the streams of which',
      },
      {
        id: '14',
        user: 'Beth Bee',
        contents:
          '<p>You\'re absolutely right, Henry. This is likely referencing the river of life or divine blessing - perhaps drawing on Eden imagery or eschatological themes. The Hebrew word for "streams" (<span dir="rtl">פְּלָגָיו</span>) suggests channels or divisions of water that bring life and prosperity.</p>',
        date: yesterday.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-7',
        verse:
          'There is a river, the streams of which make glad the city of God, the holy place of the tabernacles of the Most High.',
        verseRef: 'PSA 46:4',
        selectedText: '',
      },
      {
        id: '15',
        user: 'Eve Fox',
        contents:
          '<p>This connects beautifully with the temple imagery - "the holy place of the tabernacles of the Most High." Should we add a note explaining that this isn\'t referring to temporary structures but to God\'s eternal dwelling place?</p>',
        date: yesterday.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-7',
        verse:
          'There is a river, the streams of which make glad the city of God, the holy place of the tabernacles of the Most High.',
        verseRef: 'PSA 46:4',
        selectedText: 'the holy place of the tabernacles of the Most High',
      },
      {
        id: '16',
        user: 'Charlie Delta',
        contents:
          '<p>I think we should also consider how to translate "make glad" (<span dir="rtl">יְשַׂמְּחוּ</span>). It\'s more than just happiness - it\'s a deep joy and celebration. Some languages might need a stronger expression than just "make happy."</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-7',
        verse:
          'There is a river, the streams of which make glad the city of God, the holy place of the tabernacles of the Most High.',
        verseRef: 'PSA 46:4',
        selectedText: 'make glad',
      },
    ],
    status: 'Unspecified',
    type: 'Normal',
    assignedUser: 'Henry Kim',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'PSA 46:4',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: true,
    isRead: false,
  },
  {
    id: 'thread-8',
    comments: [
      {
        id: '17',
        user: 'Tim Steenwyk',
        contents:
          'This is a note with <b>bold text</b> and <i>italic text</i>.</p><p>It also has <u>underlined</u> and <s>strikethrough</s> text.',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-8',
        verse: '\\v 1 When people had spread all over the world...',
        verseRef: 'GEN 6:1',
        selectedText: '',
      },
      {
        id: '18',
        user: 'Beth Bee',
        contents:
          '<p>This is a reply with <b>bold</b> and <i><b>bold italic</b></i> formatting.</p>',
        date: yesterday.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-8',
        verse: '',
        verseRef: 'GEN 6:1',
        selectedText: '',
      },
      {
        id: '19',
        user: 'Charlie Delta',
        contents:
          '<p>Another reply with <u>underline</u> and <s>strikethrough</s> combined: <u><s>both</s></u>.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-8',
        verse: '',
        verseRef: 'GEN 6:1',
        selectedText: '',
      },
      {
        id: '100',
        user: 'Charlie Delta',
        contents:
          '<p>Another reply with <u>underline</u> and <s>strikethrough</s> combined: <u><s>both</s></u>.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-8',
        verse: '',
        verseRef: 'GEN 6:1',
        selectedText: '',
      },
      {
        id: '101',
        user: 'Charlie Delta',
        contents:
          '<p>Another reply with <u>underline</u> and <s>strikethrough</s> combined: <u><s>both</s></u>.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-8',
        verse: '',
        verseRef: 'GEN 6:1',
        selectedText: '',
      },
      {
        id: '102',
        user: 'Charlie Delta',
        contents:
          '<p>Another reply with <u>underline</u> and <s>strikethrough</s> combined: <u><s>both</s></u>.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-8',
        verse: '',
        verseRef: 'GEN 6:1',
        selectedText: '',
      },
      {
        id: '103',
        user: 'Charlie Delta',
        contents:
          '<p>Another reply with <u>underline</u> and <s>strikethrough</s> combined: <u><s>both</s></u>.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-8',
        verse: '',
        verseRef: 'GEN 6:1',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'GEN 6:1',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    isRead: false,
  },
  {
    id: 'thread-9',
    comments: [
      {
        id: '20',
        user: 'Tim Steenwyk',
        contents:
          'Two different people made conflicting changes in this verse.<p><language name="es-015-vaidika"><p>\\v 9 Moses said to the <s><color name="red">large group of </color></s>people, "While we were still at Mount Sinai, I told you, \'The responsibility for leading you is too much for me. I can\'t do it alone. </p></language></p>This <color name="green">is</color> <color name="blue">a</color> <strikethrough>new</strikethrough> paragraph</p>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-9',
        verse: '\\v 9 Moses said to the people, "While we were still at Mount Sinai..."',
        verseRef: 'DEU 1:9',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: twoDaysAgo.toISOString(),
    verseRef: 'DEU 1:9',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    isRead: false,
  },
  {
    id: 'thread-10',
    comments: [
      {
        id: '21',
        user: 'Eve Fox',
        contents:
          '<p>This is my note with <language name="es-015-vaidika">Spanish text</language> embedded.</p>',
        date: yesterday.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        isRead: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-10',
        verse: '\\v 18 and cried out as they saw the smoke from the flames...',
        verseRef: 'REV 18:18',
        selectedText: '',
      },
    ],
    status: 'Resolved',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: yesterday.toISOString(),
    verseRef: 'REV 18:18',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
    isRead: false,
  },
  // #endregion sample comments with some old data
];
