/**
 * === GREEN PHASE CROSS-WP JOURNEY TESTS — manage-books ===
 *
 * Feature: manage-books Cross-WP Journey Tests (GREEN phase — activated post-implementation).
 *
 * Generated by: e2e-test-writer mode=write; activated/reconciled by: e2e-test-writer mode=verify.
 *
 * Stage 3.5 (verify mode) reconciliations:
 *
 * - Action-toggle clicks switched from `getByRole('button', { name: /^X$/i })` to the proven
 *   `[data-testid="action-toggle-{view|create|delete|copy|import}"]` selectors used by
 *   manage-books-functional-WP-001.spec.ts. The role+name pattern would have matched the toggle
 *   button (its accessible name comes from the inner text node "Create" / "Delete" / etc.) but the
 *   data-testid is the explicit, stable contract the component now exposes.
 * - View toggle data-state assertion uses `[data-testid="manage-books-sidebar-section-show"]`.
 * - Picker selector kept as `getByRole('dialog', { name: /Greek Esther/i })` — proven by
 *   manage-books-functional-WP-002.spec.ts which uses the same pattern.
 * - Confirmation modals scoped to `[role="alertdialog"]` (proven in WP-001).
 * - Selection-state assertions on book pills use `aria-checked` (the dialog component renders both
 *   `aria-selected` and `aria-checked` on selectable pills — see component line 1904-1905).
 *
 * Scope: These tests exercise multi-step user flows that span two or more work packages, focusing
 * on cross-screen and cross-mode behavior that no single per-WP functional test can express on its
 * own. Per-WP tests live in `manage-books-functional-WP-001.spec.ts` (ManageBooksDialog Unified —
 * all 5 action modes) and `manage-books-functional-WP-002.spec.ts` (GreekEstherTemplatePicker).
 *
 * Why this file exists: The manage-books feature consolidates 5 PT9 dialogs into a single
 * ManageBooksDialog (WP-001) plus one modal-on-modal sub-dialog (WP-002). Most user value comes
 * from the _transitions_ between action modes (e.g., select books in Create, switch to Delete,
 * return — preserve state) and from the cross-WP modal-on-modal stack (Create → Esther picker →
 * return to Create with template choice routed into createBooks). Journey tests pin those
 * transitions.
 *
 * Conventions:
 *
 * - Uses `cdp.fixture` only (NEVER papi.fixture / app.fixture).
 * - Navigates via visible UI only (NEVER sendPapiCommand).
 * - Every test has a `// @scenario TS-XXX` comment for traceability.
 * - Every test that produces an evidence-worthy state captures a screenshot under
 *   `proofs/component-evidence/journey/`.
 * - Tests that depend on the FN-010 multi-select native file-picker spike are marked FN-010-blocked
 *   in their inline comment so verify-mode knows to leave them on .fixme until that spike lands. We
 *   deliberately omit such journeys here — Import-mode flows live in the per-WP file because the
 *   spike still gates them.
 * - Selector strategy mirrors the per-WP files: role+name + `data-book="..."` for grid pills +
 *   `role="alertdialog"` for confirmation modals + `role="dialog"` (with a `name` matcher) for the
 *   Esther picker. The cherry-picked component does not yet expose `data-testid` attributes; if
 *   component-builder adds them during wiring, these tests can be tightened.
 *
 * Naming: Strategic plan v2.0.0 collapsed the 7 separate UI-PKG entries from v1.1.0 into 2 work
 * packages (WP-001 covers all 5 action modes inside the unified dialog; WP-002 is the Esther
 * picker). For the purposes of "cross-WP journey", we treat cross-mode flows within WP-001 as
 * legitimate journey tests because the unified-dialog idiom means the user's mental model is "I'm
 * using one tool that does many things" and the production risk is in the transitions between those
 * modes.
 */
import type { FrameLocator, Page } from '@playwright/test';
import { test, expect } from '../../fixtures/cdp.fixture';
import { openFromEditorHamburger, waitForAppReady } from '../../fixtures/helpers';

const SCREENSHOT_BASE = 'proofs/component-evidence/journey';
const WEB_VIEW_TITLE_REGEX = /Manage Books/i;
const MENU_LABEL_REGEX = /Manage Books/i;
const MANAGE_BOOKS_FRAME = 'iframe[title*="Manage Books" i]';
/**
 * Project whose editor hosts the Manage Books entry point (Manila UX follow-up moved the menu item
 * from the application main menu into the scripture editor's hamburger menu). Same test project the
 * markers-checklist specs use. Tests that need a different target project still switch via the
 * dialog's own sidebar project picker after opening.
 */
const ENTRY_PROJECT_NAME = 'wgPIDGIN';

test.describe('Manage Books Journey Tests (Cross-WP / Cross-Mode)', () => {
  /**
   * Close all tabs except Home before each test so dock layout state from a previous test does not
   * leak in. Platform.Bible persists the dock layout per user-data dir, so a stale Manage Books tab
   * would otherwise pollute these tests.
   */
  test.beforeEach(async ({ mainPage }) => {
    const staleCloseBtn = mainPage
      .locator('.dock-tab')
      .filter({ hasNotText: 'Home' })
      .locator('.dock-tab-close-btn');
    const maxClosures = 8;
    for (let i = 0; i < maxClosures; i += 1) {
      // Sequential awaits intentional: count() must complete before we decide to break the loop.
      // eslint-disable-next-line no-await-in-loop
      const remaining = await staleCloseBtn.count();
      if (remaining === 0) break;
      // Closing a tab re-renders the dock, so we await each click before the next pass.
      // eslint-disable-next-line no-await-in-loop
      await staleCloseBtn.first().dispatchEvent('click');
      // Brief settle to let React commit the dock-layout state change.
      // eslint-disable-next-line no-await-in-loop
      await mainPage.waitForTimeout(300);
    }
  });

  /**
   * Helper: open the Manage Books unified dialog via the scripture editor's hamburger ("Project")
   * menu and return a frameLocator scoped to the dialog's web-view iframe. Uses the shared
   * {@link openFromEditorHamburger} bootstrap (same helper the per-WP functional tests use) so
   * journey tests do not drift from the per-WP idiom.
   *
   * The Manila UX follow-up moved the entry point from the application main menu into the editor
   * hamburger (reserved `platform.manageBooks` default group in the Project section). The hamburger
   * button and its Radix menu both render INSIDE the editor's iframe.
   */
  async function openManageBooks(mainPage: Page): Promise<FrameLocator> {
    await openFromEditorHamburger(mainPage, {
      projectName: ENTRY_PROJECT_NAME,
      menuItem: MENU_LABEL_REGEX,
      tabTitle: WEB_VIEW_TITLE_REGEX,
    });
    return mainPage.frameLocator(MANAGE_BOOKS_FRAME);
  }

  /**
   * Try to switch the dialog's active project to `candidate` and return true iff that project
   * exists in the project picker AND the requested `bookId` is creatable in it (i.e. missing from
   * the project, so it appears in Create mode's universe). Returns false if the candidate is not in
   * the picker or already contains the book.
   */
  async function tryProjectCandidate(
    frame: FrameLocator,
    candidate: string,
    bookId: string,
  ): Promise<boolean> {
    await frame.locator('[data-testid="manage-books-sidebar-project-trigger"]').click();
    const option = frame.locator('[cmdk-item]', { hasText: new RegExp(candidate) });
    const optionVisible = await option
      .first()
      .isVisible()
      .catch(() => false);
    if (!optionVisible) {
      // Close the dropdown and signal to caller that this candidate isn't available.
      await frame.locator('body').press('Escape');
      return false;
    }
    await option.first().click();
    // Wait for the grid to re-render against the new project.
    await frame.locator('ul[role="listbox"] li[data-book]').first().waitFor({ timeout: 10_000 });
    const candidatePill = frame.locator(`ul[role="listbox"] li[data-book="${bookId}"]`);
    return candidatePill.isVisible().catch(() => false);
  }

  /**
   * Switch the dialog's active project to one that is MISSING the supplied book ID. Walks the
   * #af-project Select options, opening each candidate, switching to it, and checking the Create-
   * mode universe for the requested book pill. Returns the short-name of the chosen project.
   *
   * Why this exists: the cold-open default project (e.g. ESVUS16 in the local fixture) often
   * already contains ESG, which puts ESG outside the Create universe (`books NOT yet present`).
   * Tests that need ESG to be creatable must rotate to a project that doesn't yet contain it. The
   * fixture rotation pool — per the prompt and the WP-001 verdict notes — is `zzz7`, `zzz6`, `MP1`,
   * `wgPIDGIN`, `RH2`, `ROT`. We try each until one works.
   */
  async function switchToProjectMissingBook(frame: FrameLocator, bookId: string): Promise<string> {
    // Candidate pool — order matters: prefer the projects most likely to be missing ESG given
    // the local fixture. zzz7 (RTL NT) and wgPIDGIN are the most reliable starting points.
    const candidates = ['zzz7', 'wgPIDGIN', 'zzz6', 'MP1', 'RH2', 'ROT'];

    // Ensure we are in Create mode (the universe we need to test against). Switch toggles do
    // not change the active project, so this is safe.
    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').click();

    // Sequential reduce-with-promise pattern: walks candidates one at a time, short-circuits as
    // soon as one matches. Avoids `for...of` (no-restricted-syntax) while keeping per-step
    // awaits semantically correct (each step depends on the previous step's UI state).
    const matched = await candidates.reduce<Promise<string | undefined>>(
      async (accPromise, candidate) => {
        const acc = await accPromise;
        if (acc !== undefined) return acc;
        const ok = await tryProjectCandidate(frame, candidate, bookId);
        return ok ? candidate : undefined;
      },
      Promise.resolve(undefined),
    );
    if (matched === undefined) {
      throw new Error(
        `No fixture project found missing ${bookId}; tried: ${candidates.join(', ')}`,
      );
    }
    return matched;
  }

  /**
   * Wait for the dialog's submit-state to clear after a mutation. Asserting `apply.toBeEnabled` is
   * incorrect: when a mutation completes successfully the run* paths call `setSelected(new Set())`
   * which makes `canApply` false (selection length 0), so the apply button stays disabled. The
   * right submit-cleared signal is the disappearance of the `Creating…` / `Deleting…` / `Copying…`
   * footer status text + the spinner icon.
   */
  async function waitForSubmitCleared(frame: FrameLocator, timeoutMs = 30_000): Promise<void> {
    await expect(
      frame.locator('footer').getByText(/Creating|Deleting|Copying|Importing/i),
    ).toHaveCount(0, { timeout: timeoutMs });
  }

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 1: Mode-Switch Journey (WP-001 internal cross-mode)
  //
  // Tests selection-state and dialog-state preservation across the 5 action modes within
  // the unified ManageBooksDialog. The unified-dialog idiom hinges on `selectionsByAction:
  // Record<Action, Set<string>>` (see strategic-plan-ui.md WP-001 State Management) — a
  // user-facing journey test that pins multi-mode transitions belongs here, not in the per-WP
  // functional file.
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-049, TS-058, TS-076
  test('Journey 1: View → Create → Delete preserves per-action selection (selectionsByAction)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    const frame = await openManageBooks(mainPage);

    // Step 1: Open the dialog — defaults to View mode. View universe = books currently in the
    // project (BHV-300). The fixture-rotated default may not always have GEN, so we resolve
    // the first creatable pill dynamically below.
    await expect(frame.getByText(/Manage Books/i).first()).toBeVisible({ timeout: 10_000 });
    const viewToggle = frame.locator('[data-testid="manage-books-sidebar-section-show"]');
    await expect(viewToggle).toHaveAttribute('data-active', 'true');

    // EVD-J-001-a: starting state — View mode, default project.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-001a-view-mode-default.png`,
    });

    // Step 2: Switch to Create mode. Universe flips to "books NOT yet present". Pick the first
    // creatable pill (whatever it is — the test fixture decides).
    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').click();
    const creatablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
    await expect(creatablePill).toBeVisible({ timeout: 10_000 });
    const creatableBookId = (await creatablePill.getAttribute('data-book')) ?? '';
    expect(creatableBookId).not.toBe('');
    await creatablePill.click();
    await expect(creatablePill).toHaveAttribute('aria-checked', 'true');

    // Step 3: Switch to Delete mode. Universe flips to "books present". Selection is per-action
    // (selectionsByAction) so the Create selection MUST NOT bleed into Delete. Pick the first
    // present-book pill (resolved dynamically — any non-empty fixture always has at least one
    // present book in delete-mode universe).
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').click();
    const firstDeletablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
    await expect(firstDeletablePill).toBeVisible({ timeout: 10_000 });
    const deletableBookId = (await firstDeletablePill.getAttribute('data-book')) ?? '';
    expect(deletableBookId).not.toBe('');
    // Pre-condition: Delete selection starts empty (Create selection didn't leak).
    await expect(firstDeletablePill).toHaveAttribute('aria-checked', 'false');
    await firstDeletablePill.click();
    await expect(firstDeletablePill).toHaveAttribute('aria-checked', 'true');

    // Step 4: Switch back to Create mode. The original creatable selection MUST still be
    // present (selectionsByAction preserves it).
    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').click();
    const creatableAfterReturn = frame.locator(
      `ul[role="listbox"] li[data-book="${creatableBookId}"]`,
    );
    await expect(creatableAfterReturn).toHaveAttribute('aria-checked', 'true', {
      timeout: 10_000,
    });

    // Step 5: Switch back to Delete mode. The previously-selected present book must still be
    // selected.
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').click();
    await expect(
      frame.locator(`ul[role="listbox"] li[data-book="${deletableBookId}"]`),
    ).toHaveAttribute('aria-checked', 'true', { timeout: 10_000 });

    // EVD-J-001-b: end state — both Create and Delete selections preserved across mode
    // transitions.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-001b-cross-mode-selection-preserved.png`,
    });
  });

  // @scenario TS-049, TS-076
  test('Journey 1b: filter input persists per-mode (filter belongs to dialog state, not per-action)', async ({
    mainPage,
  }) => {
    // The filter input lives in the always-present filter row (ui-spec-manage-books.md "Filters
    // row"). The strategic-plan State Management `filter: string` is a single dialog-level
    // value, not a per-action one. Switching modes should NOT clear the filter — the user is
    // refining the same project's book list across actions.
    await waitForAppReady(mainPage);
    const frame = await openManageBooks(mainPage);

    const filterInput = frame.getByRole('textbox', { name: /Filter books/i });
    await expect(filterInput).toBeVisible({ timeout: 10_000 });
    await filterInput.fill('Gen');

    // Switch View → Create — filter persists across the toggle.
    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').click();
    await expect(filterInput).toHaveValue('Gen');

    // Switch Create → Delete — filter still persists.
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').click();
    await expect(filterInput).toHaveValue('Gen');
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 2: Create-with-Greek-Esther Journey (cross-WP-001 + WP-002)
  //
  // The Esther picker is the canonical cross-WP integration point. WP-001 detects ESG +
  // fromTemplate at submit time; WP-002 renders the picker as modal-on-modal. The picker's
  // result must route into createBooks via the wiring layer (acceptance criterion A1).
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-079, TS-077, TS-072
  test('Journey 2: Create ESG + ScriptureTemplate → Esther picker → Vulgate → OK routes template into createBooks', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    const frame = await openManageBooks(mainPage);

    // Step 0: Rotate to a project that does NOT have ESG so the Create universe contains it.
    // The cold-open fixture default may have ESG already (e.g. ESVUS16 has all 92 books) which
    // would put ESG outside Create mode.
    await switchToProjectMissingBook(frame, 'ESG');

    // Step 1: We are already in Create mode after switchToProjectMissingBook. Select ESG.
    const esgPill = frame.locator('ul[role="listbox"] li[data-book="ESG"]');
    await expect(esgPill).toBeVisible({ timeout: 10_000 });
    await esgPill.click();
    await expect(esgPill).toHaveAttribute('aria-checked', 'true');

    // Step 2: Pick the "Based on..." (fromTemplate / ScriptureTemplate) creation method. The
    // method dropdown is `#af-method` per the dialog component (line 1569).
    await frame.locator('#af-method').click();
    await frame.getByRole('option', { name: /Based on|From template|Reference text/i }).click();

    // Step 3: Pick a reference / model project that has ESG so the Create-mode pre-flight
    // passes the model-required gate (VAL-100) without showing the missing-book prompt that
    // would block this test's expected path. Filter to TPTS (a known ESG-having model project)
    // rather than `.first()`, since the first option may be a project without ESG and the
    // ordering is environment-dependent. Scope the option lookup to the open Radix popper to
    // avoid matching book-grid options (those also have role="option").
    await frame.locator('#af-reference').click();
    await frame
      .locator('[data-radix-popper-content-wrapper] [role="option"]')
      .filter({ hasText: /TPTS/ })
      .first()
      .click();

    // EVD-J-002-a: Create form populated with ESG + fromTemplate + reference picked.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-002a-create-esg-from-template.png`,
    });

    // Step 4: Click apply. WP-001 acceptance A1 requires the dialog to detect ESG +
    // fromTemplate and open WP-002's Esther picker as modal-on-modal — onCreateBooks does
    // NOT fire yet.
    const createApply = frame
      .locator('footer button')
      .filter({ hasText: /Create/i })
      .last();
    await createApply.click();

    // Step 5: Picker opens. The picker is a Radix `<Dialog>` rendered as a peer of the parent
    // ManageBooksDialog inside the same web-view iframe (WP-002 architectural decision —
    // in-process render). Accessible name is "Greek Esther: Choose Template".
    const picker = frame.getByRole('dialog', { name: /Greek Esther/i });
    await expect(picker).toBeVisible({ timeout: 10_000 });

    // Default selection is LXX per RF-UI-006 (closed 2026-05-01); switch to Vulgate to prove
    // the user's choice flows through, not just the default.
    const vulgateRadio = picker.getByRole('radio', { name: /^Vulgate/i });
    await vulgateRadio.click();
    await expect(vulgateRadio).toBeChecked();

    // EVD-J-002-b: picker open with Vulgate selected.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-002b-picker-vulgate-selected.png`,
    });

    // Step 6: Click OK. The wiring layer's handlePickerSelect resolves the parent's
    // onOpenEstherPicker promise and the parent's createBooks(...) call dispatches with the
    // chosen template (`'vulgate'`). The picker dismisses; the parent dialog stays mounted.
    // The picker's confirm button label is 'Choose' (%manageBooks_createEsther_okButton%);
    // accept the legacy 'OK' too in case the label is revised again.
    await picker.getByRole('button', { name: /^(OK|Choose)$/i }).click();
    await expect(picker).toBeHidden({ timeout: 5_000 });

    // Step 7: createBooks is now in flight — A3 acceptance requires the apply button to be
    // disabled and a "Creating books..." live-region announcement to appear during the
    // mutation. The MIN_SUBMITTING_VISIBLE_MS=1500 floor applied during WP-001 iteration 2
    // guarantees this state is observable to e2e tools polling sequentially. We assert the
    // disabled-apply state as the cross-WP wire-through evidence — actual book creation
    // completes asynchronously.
    await expect(createApply).toBeDisabled({ timeout: 5_000 });
    // Footer renders "Creating..." both as visible span and sr-only aria-live; pick first
    // to satisfy strict-mode locator (mirrors the WP-001 functional test fix).
    await expect(
      frame
        .locator('footer')
        .getByText(/Creating/i)
        .first(),
    ).toBeVisible({
      timeout: 10_000,
    });

    // EVD-J-002-c: parent dialog after picker closed, mutation in flight.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-002c-picker-closed-mutation-in-flight.png`,
    });
  });

  // @scenario TS-079, TS-072
  test('Journey 3: Cancel Esther picker aborts Create flow without dispatching createBooks', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    const frame = await openManageBooks(mainPage);

    // Setup identical to Journey 2 up through clicking apply (rotate to ESG-missing project).
    await switchToProjectMissingBook(frame, 'ESG');
    const esgPill = frame.locator('ul[role="listbox"] li[data-book="ESG"]');
    await expect(esgPill).toBeVisible({ timeout: 10_000 });
    await esgPill.click();
    await frame.locator('#af-method').click();
    await frame.getByRole('option', { name: /Based on|From template|Reference text/i }).click();
    await frame.locator('#af-reference').click();
    // Filter to TPTS (ESG-having model) — see Journey 2 comment.
    await frame
      .locator('[data-radix-popper-content-wrapper] [role="option"]')
      .filter({ hasText: /TPTS/ })
      .first()
      .click();

    const createApply = frame
      .locator('footer button')
      .filter({ hasText: /Create/i })
      .last();
    await createApply.click();

    const picker = frame.getByRole('dialog', { name: /Greek Esther/i });
    await expect(picker).toBeVisible({ timeout: 10_000 });

    // Cancel from the picker. The parent Create flow must abort: createBooks does NOT fire.
    await picker.getByRole('button', { name: /^Cancel$/i }).click();
    await expect(picker).toBeHidden({ timeout: 5_000 });

    // Cross-WP cancel-aborts evidence:
    // 1. The parent dialog stays open (modal-on-modal — only the inner picker dismissed).
    await expect(
      frame.locator('[data-testid="manage-books-sidebar-section-create"]'),
    ).toBeVisible();
    // 2. The ESG selection is preserved (the cancel doesn't clear the user's Create work).
    await expect(esgPill).toHaveAttribute('aria-checked', 'true');
    // 3. Most importantly: the apply button is back to ENABLED (no in-flight mutation).
    //    If createBooks had fired, the button would be DISABLED with a "Creating books..."
    //    live-region message (A3 acceptance). Re-enabled apply = mutation aborted.
    await expect(createApply).toBeEnabled({ timeout: 5_000 });
    await expect(frame.locator('footer').getByText(/Creating/i)).toHaveCount(0);

    // EVD-J-003: parent dialog after picker cancel — Create flow aborted, selection preserved.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-003-picker-cancel-create-aborted.png`,
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 3: Copy → View Mode Journey (WP-001 cross-mode after mutation)
  //
  // Pin the post-mutation refresh + cross-mode UX after a Copy. This catches regressions where
  // the post-success state forgets to refresh `useProjectSetting('platformScripture.booksPresent')`
  // or where the dialog stays in the mutating mode without giving the user a clear next step.
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-073, TS-090, TS-062
  test('Journey 4: Copy from source project → bulk-select → submit → return to View shows updated book list', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    const frame = await openManageBooks(mainPage);

    // Step 1: Switch to Copy mode. Apply is disabled (no source picked).
    await frame.locator('[data-testid="manage-books-sidebar-section-copy"]').click();
    const copyApply = frame.locator('footer button').filter({ hasText: /Copy/i }).last();
    await expect(copyApply).toBeDisabled({ timeout: 5_000 });

    // Step 2: Pick the first available source project (Copy filterProjects purpose='copySource'
    // excludes self). After selection the comparison grid populates with badges.
    const sourceTrigger = frame
      .locator('button[role="combobox"]')
      .filter({ hasText: /Select project/i });
    await sourceTrigger.click();
    const firstSource = frame.locator('[role="option"]').first();
    await expect(firstSource).toBeVisible({ timeout: 10_000 });
    await firstSource.click();

    // Step 3: Wait for at least one comparison row to appear. (The grid populates from
    // platformScripture.getBookComparison once both projects are set.)
    const grid = frame.locator('ul[role="listbox"]');
    await expect(grid.locator('li[data-book]').first()).toBeVisible({ timeout: 10_000 });

    // EVD-J-004-a: Copy mode populated with comparison badges.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-004a-copy-grid-populated.png`,
    });

    // Step 4: Bulk-select via the "Select all visible" checkbox (BHV-314 / TS-062).
    // After the BookGridSelector port (2026-05-03) the per-group select-all
    // checkboxes also use aria-label="Select all in {group}", so we anchor on
    // the bare "Select all" name with `exact: true` to disambiguate the outer
    // filter-bar checkbox from the per-group ones.
    const selectAll = frame.getByRole('checkbox', { name: 'Select all', exact: true });
    await expect(selectAll).toBeVisible({ timeout: 10_000 });
    await selectAll.click();

    const checkedPills = grid.locator('li[aria-checked="true"]');
    await expect(checkedPills.first()).toBeVisible({ timeout: 5_000 });
    const checkedCountBefore = await checkedPills.count();
    expect(checkedCountBefore).toBeGreaterThan(0);

    // Step 5: Click apply. A3 acceptance: apply disables + spinner during mutation
    // (MIN_SUBMITTING_VISIBLE_MS=1500 guarantees observability).
    await expect(copyApply).toBeEnabled();
    await copyApply.click();
    // If the bulk selection included books that already exist in the destination,
    // the three-way conflict prompt ('Books already exist') intercepts the submit.
    // Choose 'Replace entire books' — this journey asserts the destination ends up
    // with the source's books.
    const conflictDialog = frame.getByRole('dialog', { name: /Books already exist/i });
    const conflictAppeared = await conflictDialog
      .waitFor({ state: 'visible', timeout: 2_000 })
      .then(() => true)
      .catch(() => false);
    if (conflictAppeared) {
      await conflictDialog.getByRole('button', { name: /Replace entire books/i }).click();
    }
    await expect(copyApply).toBeDisabled({ timeout: 5_000 });

    // Step 6: Wait for the submit-state to clear. NOTE: we cannot assert
    // `copyApply.toBeEnabled()` here — the run* paths call `setSelected(new Set())` on
    // success, which makes `canApply` false (no books selected) so the apply button stays
    // disabled. The right submit-cleared signal is the "Copying…" footer status text
    // disappearing.
    await waitForSubmitCleared(frame, 30_000);

    // EVD-J-004-b: Copy completed (mutation succeeded, submit-state cleared).
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-004b-copy-mutation-completed.png`,
    });

    // Step 7: Switch to View mode. The View universe (books currently present) MUST reflect
    // the freshly copied books — proving the wiring layer's
    // `useProjectSetting('platformScripture.booksPresent')` subscription refreshed after the
    // mutation. We assert at least one book pill renders in View mode after the copy.
    await frame.locator('[data-testid="manage-books-sidebar-section-show"]').click();
    const viewBooks = grid.locator('li[data-book]');
    await expect(viewBooks.first()).toBeVisible({ timeout: 10_000 });
    const viewBookCount = await viewBooks.count();
    expect(viewBookCount).toBeGreaterThan(0);

    // EVD-J-004-c: Returned to View mode with refreshed book list after Copy.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-004c-view-after-copy.png`,
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 4: Delete with Confirmation Modal (WP-001 — destructive-confirm + AlertDialog)
  //
  // Pin the BHV-310 / BHV-312 / A2 destructive-confirm pattern: Delete-mode submit must NOT
  // fire onDeleteBooks immediately — a `<AlertDialog>` interrupts with default focus on Cancel.
  // The journey covers both the cancel path (no mutation) and the confirm path (mutation
  // dispatches, dialog refreshes).
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-074, TS-057, TS-055
  test('Journey 5: Delete → AlertDialog → Cancel preserves selection and does NOT dispatch deleteBooks', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    const frame = await openManageBooks(mainPage);

    // Step 1: Switch to Delete mode and pick the first present-book pill (resolved dynamically;
    // the active fixture project rotates and may not always have GEN as the first pill, but
    // any non-empty project will have at least one deletable book).
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').click();
    const firstDeletablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
    await expect(firstDeletablePill).toBeVisible({ timeout: 10_000 });
    const deletableBookId = (await firstDeletablePill.getAttribute('data-book')) ?? '';
    expect(deletableBookId).not.toBe('');
    await firstDeletablePill.click();
    await expect(firstDeletablePill).toHaveAttribute('aria-checked', 'true');

    // Step 2: Click apply. A2 acceptance: a destructive-confirm AlertDialog opens with default
    // focus on Cancel. onDeleteBooks does NOT fire yet.
    const deleteApply = frame
      .locator('footer button')
      .filter({ hasText: /Delete/i })
      .last();
    await deleteApply.click();

    const confirmDialog = frame.locator('[role="alertdialog"]');
    await expect(confirmDialog).toBeVisible({ timeout: 5_000 });
    const cancelBtn = confirmDialog.getByRole('button', { name: /Cancel/i });
    const confirmBtn = confirmDialog.getByRole('button', { name: /^Delete$/i });
    await expect(cancelBtn).toBeVisible();
    await expect(confirmBtn).toBeVisible();

    // EVD-J-005-a: AlertDialog shown with destructive-confirm copy.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-005a-delete-confirm-shown.png`,
    });

    // Step 3: Click Cancel. AlertDialog dismisses; the underlying ManageBooksDialog stays
    // open with the selection preserved. deleteBooks did NOT fire — apply re-enables to
    // its pre-submit state (no in-flight mutation, no spinner).
    await cancelBtn.click();
    await expect(confirmDialog).toBeHidden({ timeout: 5_000 });
    await expect(
      frame.locator(`ul[role="listbox"] li[data-book="${deletableBookId}"]`),
    ).toHaveAttribute('aria-checked', 'true');
    await expect(deleteApply).toBeEnabled();
    await expect(frame.locator('footer').getByText(/Deleting/i)).toHaveCount(0);

    // EVD-J-005-b: parent dialog after cancel — selection preserved, no mutation.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-005b-delete-cancel-no-mutation.png`,
    });
  });

  // @scenario TS-074, TS-002, TS-055
  test('Journey 6: Delete → AlertDialog → Confirm dispatches deleteBooks; book disappears from View', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    const frame = await openManageBooks(mainPage);

    // Step 0: Switch the dialog's target to RH2. Deleting books requires the
    // current user to be an ADMINISTRATOR of the target project
    // (DeleteBooksOrchestrator WarnIfNotAdministrator, PT9 parity) — on the
    // entry project (wgPIDGIN) the e2e user is only a TeamMember, so the
    // backend correctly refuses with a toast and nothing is deleted. RH2 is a
    // registered project where the e2e user is Administrator, which also
    // exercises the shared-project confirmation copy.
    await frame.locator('[data-testid="manage-books-sidebar-project-trigger"]').click();
    await frame.locator('[cmdk-item]').filter({ hasText: /RH2/ }).first().click();
    await mainPage.waitForTimeout(800);

    // Step 1: Pick the LAST present-book pill in Delete mode (Delete universe = books currently
    // present; the test asserts on the chosen ID symbolically — whatever the fixture has).
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').click();
    const presentPills = frame.locator('ul[role="listbox"] li[data-book]');
    await expect(presentPills.first()).toBeVisible({ timeout: 10_000 });
    const presentCount = await presentPills.count();
    expect(presentCount).toBeGreaterThan(0);
    // Pick the LAST canonical present pill. (Earlier XX-book delete failures
    // observed against wgPIDGIN were admin-permission refusals, not an
    // extra-book defect — fixed by targeting RH2 above. The canonical filter
    // stays as cheap determinism against fixture drift.)
    const presentIds = await presentPills.evaluateAll((els) =>
      els.map((el) => el.getAttribute('data-book')),
    );
    const canonicalIds = presentIds.filter((id): id is string => !!id && !id.startsWith('XX'));
    expect(canonicalIds.length).toBeGreaterThan(0);
    const targetBookId = canonicalIds[canonicalIds.length - 1];
    const targetPill = frame.locator(`ul[role="listbox"] li[data-book="${targetBookId}"]`);
    expect(targetBookId).not.toBe('');
    await targetPill.click();
    await expect(targetPill).toHaveAttribute('aria-checked', 'true');

    // Step 2: Click apply → AlertDialog opens.
    const deleteApply = frame
      .locator('footer button')
      .filter({ hasText: /Delete/i })
      .last();
    await deleteApply.click();
    const confirmDialog = frame.locator('[role="alertdialog"]');
    await expect(confirmDialog).toBeVisible({ timeout: 5_000 });

    // Step 3: Click Confirm. The wiring layer dispatches deleteBooks via PAPI, the AlertDialog
    // dismisses, and the dialog enters its in-flight state.
    await confirmDialog.getByRole('button', { name: /^Delete$/i }).click();
    await expect(confirmDialog).toBeHidden({ timeout: 10_000 });

    // EVD-J-006-a: AlertDialog dismissed, mutation in flight.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-006a-delete-confirm-mutation.png`,
    });

    // Step 4: Wait for the mutation to complete and the dialog to refresh. NOTE: we cannot
    // assert `deleteApply.toBeEnabled()` because the run* paths clear selection on success
    // (`setSelected(new Set())`), making canApply=false. We instead wait for the "Deleting…"
    // footer status text to disappear, then assert the target book's pill no longer appears
    // in the Delete universe (Delete = present books; a deleted book is no longer present).
    await waitForSubmitCleared(frame, 30_000);
    const deletedBookPill = frame.locator(`ul[role="listbox"] li[data-book="${targetBookId}"]`);
    await expect(deletedBookPill).toHaveCount(0, { timeout: 10_000 });

    // Step 5: Cross-mode verification — switch to View mode and confirm the cross-mode data
    // refresh occurred. View universe = ALL canonical books, so the deleted book's pill IS
    // still rendered in View — but it must NOT carry the "Present" badge anymore (component
    // lines 1147-1150: `if (action === 'view' && !isPresent) return undefined;` skips the
    // Present badge for missing books). The strict cross-mode-refresh contract is: the
    // book that was just deleted in Delete mode no longer appears as Present in View mode.
    await frame.locator('[data-testid="manage-books-sidebar-section-show"]').click();
    const viewDeletedBook = frame.locator(`ul[role="listbox"] li[data-book="${targetBookId}"]`);
    await expect(viewDeletedBook).toBeVisible({ timeout: 10_000 });
    // The deleted book's pill must NOT contain the "Present" badge. We check that the pill
    // text does not include "Present" — the badge renders the localized "Present" label for
    // present books only.
    await expect(viewDeletedBook).not.toContainText(/Present/i);

    // EVD-J-006-b: View mode refreshed after Delete — deleted book no longer present.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-006b-view-after-delete.png`,
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 5: Dialog lifecycle journey — close/reopen restores fresh state
  //
  // This catches regressions where the dialog persists in-progress mutation state, stale
  // selection from a previous session, or a stuck pendingPrompt across close/reopen.
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-049, TS-058, TS-089
  test('Journey 7: close dialog mid-Create-selection, reopen → starts at View with no leftover selection', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    const frame = await openManageBooks(mainPage);

    // Step 1: Switch to Create and pick a creatable book.
    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').click();
    const creatablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
    await expect(creatablePill).toBeVisible({ timeout: 10_000 });
    const creatableBookId = (await creatablePill.getAttribute('data-book')) ?? '';
    expect(creatableBookId).not.toBe('');
    await creatablePill.click();
    await expect(creatablePill).toHaveAttribute('aria-checked', 'true');

    // Step 2: Close the dialog by closing its dock tab. (The dialog opens as a float web
    // view; the dock-tab close button dismisses it — see WP-001 EVD-003.)
    const tab = mainPage.locator('.dock-tab', { hasText: WEB_VIEW_TITLE_REGEX });
    await tab.locator('.dock-tab-close-btn').dispatchEvent('click');
    await expect(tab).toBeHidden({ timeout: 10_000 });

    // Step 3: Reopen the dialog. It should start at View mode (the default per the unified
    // spec: "The dialog opens with View as the default action") with no leftover selection
    // from the previous session — selection state is per-instance, not per-user.
    const reopened = await openManageBooks(mainPage);
    const reopenedViewToggle = reopened.locator(
      '[data-testid="manage-books-sidebar-section-show"]',
    );
    await expect(reopenedViewToggle).toHaveAttribute('data-active', 'true', { timeout: 10_000 });

    // Step 4: Switch to Create — the previously selected pill must NOT be checked anymore.
    await reopened.locator('[data-testid="manage-books-sidebar-section-create"]').click();
    const reopenedPill = reopened.locator(`ul[role="listbox"] li[data-book="${creatableBookId}"]`);
    // The pill may not even appear (universe could differ if the project changed), but if
    // it does it must not be checked.
    if ((await reopenedPill.count()) > 0) {
      await expect(reopenedPill).toHaveAttribute('aria-checked', 'false');
    }

    // EVD-J-007: reopened dialog starts fresh, no leaked selection.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/JEVD-007-reopen-fresh-state.png`,
    });
  });
});
