/**
 * === RED PHASE FUNCTIONAL TESTS — WP-001: ManageBooksDialog (Unified) wiring ===
 *
 * Feature: manage-books Work Package: WP-001 — wiring + web-view for the unified ManageBooksDialog
 * (covers ALL 5 action modes: View / Create / Delete / Copy / Import + the inline book-chooser
 * grid).
 *
 * Generated by: ui-test-writer (RED phase — all tests originally used test.fixme()).
 *
 * Component under test (presentational):
 * `lib/platform-bible-react/src/components/advanced/manage-books-dialog/manage-books-dialog.component.tsx`
 *
 * Wiring under test (NOT YET IMPLEMENTED — that's why tests are .fixme):
 *
 * - `extensions/src/platform-scripture/src/manage-books.web-view.tsx`
 * - `extensions/src/platform-scripture/src/manage-books.web-view-provider.ts`
 * - `extensions/src/platform-scripture/contributions/menus.json` (entry-point menu item)
 * - `extensions/src/platform-scripture/src/main.ts` (provider/command registration)
 * - `extensions/src/platform-scripture/src/types/platform-scripture.d.ts` (open-command declaration)
 * - `extensions/src/platform-scripture/contributions/localizedStrings.json`
 *
 * Selector strategy: The cherry-picked component does NOT define `data-testid` attributes. Tests
 * therefore rely on: - Accessible names: button text, `aria-label`, `role="listbox"` /
 * `role="option"` for the grid. - The `data-book="{BOOK_ID}"` attribute on each grid pill `<li>`
 * (line 1846 of the component). - The `role="alertdialog"` attribute on the destructive-confirm /
 * preflight / overlap modals. - ToggleGroupItem `value=` attributes for the action toggle
 * (view/create/import/copy/delete). Follow-up for component-builder: add
 * `data-testid="manage-books-dialog"` (root), `action-toggle`,
 * `action-toggle-{view|create|import|copy|delete}`, `book-pill-{ID}`, `apply-button`,
 * `cancel-button`, `delete-confirm-dialog`, `usx-confirm-dialog`, `overlap-error-dialog`,
 * `result-panel` so tests can become more resilient. Recorded in functional-test-plan-WP-001.md.
 *
 * Conventions:
 *
 * - Uses `cdp.fixture` only (NEVER papi.fixture or app.fixture).
 * - Navigates via visible UI only (NEVER sendPapiCommand).
 * - Every test has a `// @scenario TS-XXX` comment for traceability.
 * - Every Test-Contract evidence point (EVD-XXX) has a `mainPage.screenshot()` call.
 * - File-picker-driven Import-mode flows use PT9-derived BHV-318 expectations; the underlying
 *   multi-select native file-picker spike (FN-010) must land before these wiring tests can be
 *   activated. Tests for those flows remain .fixme until that spike completes.
 */
import { test, expect } from '../../fixtures/cdp.fixture';
import { waitForAppReady } from '../../fixtures/helpers';

const SCREENSHOT_BASE = 'proofs/component-evidence/WP-001';
const WEB_VIEW_TITLE_REGEX = /Manage Books/i;
const MENU_LABEL_REGEX = /Manage Books/i;

test.describe('Manage Books Functional Tests (WP-001 — Unified Dialog Wiring)', () => {
  // Close all tabs except Home to start from a clean state. Platform.Bible persists the dock
  // layout across sessions, so a stale Manage Books tab from a previous test would otherwise
  // pollute these tests.
  test.beforeEach(async ({ mainPage }) => {
    // Press Escape twice to close any lingering menubar dropdown / Radix
    // popover / Select content from a previous test. Some tests (BHV-400/412)
    // leave the Tools menu open after asserting the Manage Books entry; the
    // next test would then click "Tools" and *toggle* the menu shut, breaking
    // the menu-item-click sequence. Escape is a no-op when nothing is open.
    await mainPage.keyboard.press('Escape');
    await mainPage.keyboard.press('Escape');

    const staleCloseBtn = mainPage
      .locator('.dock-tab')
      .filter({ hasNotText: 'Home' })
      .locator('.dock-tab-close-btn');
    // Bound the cleanup to a small fixed number of iterations: a real test environment
    // never has more than ~5 stale tabs, and capping prevents runaway loops if the dock
    // close handler regresses.
    const maxClosures = 8;
    for (let i = 0; i < maxClosures; i += 1) {
      // Intentional sequential await: count() must complete before we decide to break.
      // eslint-disable-next-line no-await-in-loop
      const remaining = await staleCloseBtn.count();
      if (remaining === 0) break;
      // Closing a tab re-renders the dock, so we await each click before the next pass.
      // eslint-disable-next-line no-await-in-loop
      await staleCloseBtn.first().dispatchEvent('click');
      // Brief settle to let React commit the dock-layout state change.
      // eslint-disable-next-line no-await-in-loop
      await mainPage.waitForTimeout(300);
    }
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 1: Navigation — entry-point menu item opens the unified dialog as a web view
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-067, TS-072
  test('should open Manage Books unified dialog from the Project menu', async ({ mainPage }) => {
    await waitForAppReady(mainPage);

    // The wiring phase adds an entry-point menu item under the Project menu (per
    // ui-spec-manage-books.md "Trigger" section: "Tools > Manage books..." — final placement
    // is decided in phase-3-ui when wiring menus.json). The test accepts either a top-level
    // "Project" or "Tools" menu trigger to remain stable across that decision.
    const projectMenu = mainPage.getByRole('menuitem', { name: /Project|Tools/i }).first();
    await projectMenu.click();

    // EVD-001: menu dropdown shows the Manage Books entry.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-001-menu-open.png`,
    });

    const manageBooksMenuItem = mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX });
    await expect(manageBooksMenuItem).toBeVisible({ timeout: 10_000 });
    await manageBooksMenuItem.click();

    // The wiring phase opens the dialog as a float web view (per ui-alignment.md
    // "Dialog Opening Pattern"); this surfaces as a dock tab whose title matches the
    // localized "Manage Books" string.
    const tab = mainPage.locator('.dock-tab', { hasText: WEB_VIEW_TITLE_REGEX });
    await expect(tab).toBeVisible({ timeout: 15_000 });
  });

  // @scenario TS-067, TS-068
  test('should expose Manage Books only when a scripture project is the active context (BHV-400/412)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);

    // BHV-400: Manage Books menu visible for Default window category. BHV-412: hidden for
    // Tool / Resource / ConsultantNotes contexts. The wiring phase must respect the
    // platform menu-contribution gating; this test verifies the menu item shows up under
    // the project-context entry path (the test environment's default scripture project is
    // the active editor on app boot).
    const projectMenu = mainPage.getByRole('menuitem', { name: /Project|Tools/i }).first();
    await projectMenu.click();
    const manageBooksMenuItem = mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX });
    await expect(manageBooksMenuItem).toBeVisible({ timeout: 10_000 });
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 2: Render — unified dialog frame, action toggle, filters, grid, footer
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-049
  test('should render dialog with action toggle, project header, grid, and apply footer (View default)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);

    // Open the dialog via menu.
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    await expect(mainPage.locator('.dock-tab', { hasText: WEB_VIEW_TITLE_REGEX })).toBeVisible({
      timeout: 15_000,
    });

    // Switch into the dialog's web-view iframe.
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // Header: title "Manage Books".
    await expect(frame.getByText(/Manage Books/i).first()).toBeVisible({ timeout: 10_000 });

    // Action toggle: 5 ToggleGroupItems (view/create/import/copy/delete). Each renders the
    // localized label as button text; default is `view`.
    await expect(frame.locator('[data-testid="manage-books-sidebar-section-show"]')).toBeVisible();
    await expect(
      frame.locator('[data-testid="manage-books-sidebar-section-create"]'),
    ).toBeVisible();
    await expect(
      frame.locator('[data-testid="manage-books-sidebar-section-import"]'),
    ).toBeVisible();
    await expect(frame.locator('[data-testid="manage-books-sidebar-section-copy"]')).toBeVisible();
    await expect(
      frame.locator('[data-testid="manage-books-sidebar-section-delete"]'),
    ).toBeVisible();

    // Filter input always present (placeholder "Filter books…", aria-label "Filter books").
    await expect(frame.getByRole('textbox', { name: /Filter books/i })).toBeVisible();

    // Grid: role="listbox" with role="option" children, each carrying data-book="{ID}".
    const grid = frame.locator('ul[role="listbox"]');
    await expect(grid).toBeVisible();
    // GEN is in every canon — should always be present in the View universe.
    await expect(grid.locator('li[data-book="GEN"]')).toBeVisible();

    // Footer: Close button (View mode shows Close, not Cancel).
    // Scoped to the footer to avoid matching the Radix Dialog's built-in
    // top-right X close button.
    await expect(frame.locator('footer').getByRole('button', { name: /^Close$/i })).toBeVisible();

    // EVD-002: dialog fully loaded in default View action mode.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-002-show-books-loaded.png`,
    });
  });

  // @scenario TS-049
  test('should display the present-book check indicator on books that exist in the active project', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    await expect(mainPage.locator('.dock-tab', { hasText: WEB_VIEW_TITLE_REGEX })).toBeVisible({
      timeout: 15_000,
    });
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // The "present" filter chip narrows the universe to books currently in the project. The
    // wiring layer subscribes to `useProjectSetting('platformScripture.booksPresent')` so a
    // real value comes through here; we assert at least one present book is rendered.
    const presentChip = frame.locator('[data-testid="presence-filter-existing"]');
    await presentChip.click();

    const presentBooks = frame.locator('ul[role="listbox"] li[data-book]');
    await expect(presentBooks.first()).toBeVisible({ timeout: 10_000 });
    const presentCount = await presentBooks.count();
    expect(presentCount).toBeGreaterThan(0);
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 3: Data Wiring — backend data flows through PAPI into props
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-082
  test('should populate the project-selector header dropdown with real ScrText projects (filterProjects)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // The header project Select renders the ShortName of the active project as its
    // SelectValue. After the wiring layer subscribes to manageBooks.filterProjects, the
    // Select's open-listbox should expose the available scripture projects.
    const projectSelectTrigger = frame.locator('button[role="combobox"]').first();
    await projectSelectTrigger.click();

    // Select content portals into the same iframe (Radix `<SelectContent>` defaults).
    const projectOptions = frame.locator('[role="option"]');
    await expect(projectOptions.first()).toBeVisible({ timeout: 10_000 });
    const optionCount = await projectOptions.count();
    // At least one project must be discoverable in the live test fixture (the C# manage-books
    // theme-verification suite uses ESVUS16, MP1, TPTS, etc. — confirmed in
    // manage-books-commands.spec.ts).
    expect(optionCount).toBeGreaterThan(0);
  });

  // @scenario TS-049, TS-089
  test('should reflect the active editor project in the dialog header at open', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);

    // Open the project tab first so the active context is concrete (Home tab is the default
    // post-launch). Click the first project tile in Home.
    const homeFrame = mainPage.frameLocator('iframe[title="Home"]');
    const firstOpenButton = homeFrame.getByRole('button', { name: /Open/i }).first();
    await firstOpenButton.click();
    // Wait for an editor tab to attach.
    await expect(mainPage.locator('.dock-tab').filter({ hasNotText: 'Home' }).first()).toBeVisible({
      timeout: 15_000,
    });

    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // Header project select should display a non-empty short name.
    const projectSelectValue = frame.locator('button[role="combobox"]').first();
    await expect(projectSelectValue).toBeVisible({ timeout: 10_000 });
    const headerText = (await projectSelectValue.textContent()) ?? '';
    expect(headerText.trim().length).toBeGreaterThan(0);
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 4: Interaction — action-mode switching, selection, mutation flows
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-049, TS-055
  test('should switch to Delete mode and reveal Delete-specific apply footer label', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').first().click();

    // The footer button label adapts: Delete-mode shows "Delete N books from {shortName}"
    // when at least one book is selected, and is disabled when no selection.
    const applyBtn = frame
      .locator('footer button')
      .filter({ hasText: /Delete/i })
      .last();
    await expect(applyBtn).toBeVisible();
  });

  // @scenario TS-076, TS-055, TS-056
  test('should toggle book selection via grid pill click and update apply-button enablement', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // Switch to Delete mode (universe = present books, so GEN is selectable in any project
    // that has Genesis).
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').first().click();

    // The Delete-mode apply footer button should be DISABLED when no books are selected
    // (VAL-103 / TS-056).
    const deleteApply = frame
      .locator('footer button')
      .filter({ hasText: /Delete/i })
      .last();
    await expect(deleteApply).toBeDisabled();

    // Click GEN pill to toggle selection on. Book pills carry data-book="GEN".
    const genPill = frame.locator('ul[role="listbox"] li[data-book="GEN"]');
    await expect(genPill).toBeVisible({ timeout: 10_000 });
    await genPill.click();

    // Apply enabled now (TS-055). aria-checked should be true.
    await expect(genPill).toHaveAttribute('aria-checked', 'true');
    await expect(deleteApply).toBeEnabled();
  });

  // @scenario TS-074, TS-057
  test('should show a destructive-confirm dialog with Cancel-default before deleting (BHV-310, A2)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // Switch to Delete mode and select GEN.
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').first().click();
    await frame.locator('ul[role="listbox"] li[data-book="GEN"]').click();

    // Click footer apply -> destructive-confirm modal opens (does NOT fire onDeleteBooks
    // immediately per WP-001 acceptance A2).
    await frame
      .locator('footer button')
      .filter({ hasText: /Delete/i })
      .last()
      .click();

    // Confirm modal: role="alertdialog", localized title "Delete books from {project}?",
    // Cancel is autoFocus (default focus on Cancel per A2).
    const confirmDialog = frame.locator('[role="alertdialog"]');
    await expect(confirmDialog).toBeVisible({ timeout: 5_000 });
    await expect(confirmDialog.getByRole('button', { name: /Cancel/i })).toBeVisible();
    await expect(confirmDialog.getByRole('button', { name: /^Delete$/i })).toBeVisible();

    // EVD-023: confirmation appearance.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-023-delete-confirmation.png`,
    });

    // Cancel keeps the dialog open and does not fire the mutation.
    await confirmDialog.getByRole('button', { name: /Cancel/i }).click();
    await expect(confirmDialog).toBeHidden({ timeout: 5_000 });
    // The grid pill remains selected (selection preserved across the cancel).
    await expect(frame.locator('ul[role="listbox"] li[data-book="GEN"]')).toHaveAttribute(
      'aria-checked',
      'true',
    );
  });

  // @scenario TS-074, TS-002 (post-delete grey-banner)
  test('should fire onDeleteBooks when destructive-confirm Delete is accepted, then refresh', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').first().click();
    await frame.locator('ul[role="listbox"] li[data-book="GEN"]').click();
    await frame
      .locator('footer button')
      .filter({ hasText: /Delete/i })
      .last()
      .click();

    const confirmDialog = frame.locator('[role="alertdialog"]');
    await expect(confirmDialog).toBeVisible({ timeout: 5_000 });
    await confirmDialog.getByRole('button', { name: /^Delete$/i }).click();

    // The wiring layer must call manageBooks.deleteBooks via PAPI and refresh the grid via
    // useProjectSetting('platformScripture.booksPresent'). Confirm dialog dismissed,
    // mutation initiated.
    await expect(confirmDialog).toBeHidden({ timeout: 10_000 });

    // EVD-024: post-delete state.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-024-after-delete.png`,
    });
  });

  // @scenario TS-072
  test('should reveal the Create-mode method dropdown when Create action is selected', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();

    // Method dropdown (id="af-method") visible in Create mode.
    const methodSelect = frame.locator('#af-method');
    await expect(methodSelect).toBeVisible({ timeout: 5_000 });

    // EVD-011: Create mode in default empty-selection state.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-011-create-empty.png`,
    });
  });

  // @scenario TS-077, TS-072
  test('should select books in Create mode and enable the Create apply button (EVD-012)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();

    // Universe in Create mode is books NOT yet present. We click the first selectable
    // pill instead of hard-coding GEN (which may already exist in every test project).
    const firstCreatablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
    await firstCreatablePill.click();
    await expect(firstCreatablePill).toHaveAttribute('aria-checked', 'true');

    const createApply = frame
      .locator('footer button')
      .filter({ hasText: /Create/i })
      .last();
    await expect(createApply).toBeEnabled();

    // EVD-012: books selected, apply enabled.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-012-books-selected.png`,
    });
  });

  // @scenario TS-079, TS-053
  test('should reveal the model-project picker when "Based on" creation method is chosen (EVD-013)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();

    // Open the method Select and pick "Based on" (referenceText / fromTemplate).
    const methodSelect = frame.locator('#af-method');
    await methodSelect.click();
    const basedOnOption = frame.getByRole('option', { name: /Based on/i });
    await expect(basedOnOption).toBeVisible({ timeout: 5_000 });
    await basedOnOption.click();

    // Reference-project picker (id="af-reference") becomes visible.
    const referenceSelect = frame.locator('#af-reference');
    await expect(referenceSelect).toBeVisible({ timeout: 5_000 });

    // EVD-013: model method selected, reference picker visible.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-013-model-method.png`,
    });
  });

  // @scenario TS-073, TS-059
  test('should render the Copy-mode source-project picker and disable apply until source is chosen', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-copy"]').click();

    // Source-project Select placeholder is "Select project" (per
    // %manageBooks_copy_sourcePlaceholder%).
    await expect(frame.getByText(/Select project/i).first()).toBeVisible({ timeout: 5_000 });

    // Copy-mode apply footer button is disabled until source is chosen AND books selected
    // (TS-059). Until source is chosen, the grid is empty (or no comparison computed) so
    // there's nothing to select.
    const copyApply = frame.locator('footer button').filter({ hasText: /Copy/i }).last();
    await expect(copyApply).toBeDisabled();

    // EVD-031: Copy mode without both projects = warning state.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-031-copy-warning.png`,
    });
  });

  // @scenario TS-073, TS-090
  test('should populate Copy-mode comparison badges once a source project is selected (EVD-032)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-copy"]').click();

    // Open source picker and pick the first available scripture project (different from
    // current). Copy filterProjects purpose='copySource' will exclude self.
    const sourceTrigger = frame
      .locator('button[role="combobox"]')
      .filter({ hasText: /Select project/i });
    await sourceTrigger.click();
    const firstSourceOption = frame.locator('[role="option"]').first();
    await expect(firstSourceOption).toBeVisible({ timeout: 10_000 });
    await firstSourceOption.click();

    // Now the grid populates with comparison badges. State filter chips become available.
    const stateFilters = frame.locator('[data-testid^="copy-state-filter-"]');
    await expect(stateFilters.first()).toBeVisible({ timeout: 10_000 });

    // EVD-032: comparison grid populated.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-032-grid-populated.png`,
    });
  });

  // @scenario TS-062, TS-087
  test('should toggle "Select all visible" via the grid header checkbox (Copy mode bulk select)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-copy"]').click();
    const sourceTrigger = frame
      .locator('button[role="combobox"]')
      .filter({ hasText: /Select project/i });
    await sourceTrigger.click();
    await frame.locator('[role="option"]').first().click();

    // The grid filter-bar exposes a "Select all" checkbox tooltip-trigger. Click it.
    const selectAll = frame.getByRole('checkbox', { name: /Select all/i });
    await expect(selectAll).toBeVisible({ timeout: 10_000 });
    await selectAll.click();

    // After bulk-select, at least one pill is aria-checked=true.
    const checkedPills = frame.locator('ul[role="listbox"] li[aria-checked="true"]');
    await expect(checkedPills.first()).toBeVisible({ timeout: 5_000 });
    const checkedCount = await checkedPills.count();
    expect(checkedCount).toBeGreaterThan(0);

    // EVD-033: all visible selected.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-033-all-selected.png`,
    });
  });

  // @scenario TS-075, TS-083
  test('should switch to Import mode and auto-open the file picker on first entry (BHV-318, A8)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // FN-010 spike: native multi-select file picker. Until that lands, the wiring layer
    // injects a callback prop that this test will exercise directly. The user-visible
    // expectation here is that switching to Import mode does NOT immediately revert (per A8
    // — "auto-cancel on no files" only fires AFTER the user cancels the picker; until the
    // picker is dismissed, Import mode is sticky).
    await frame.locator('[data-testid="manage-books-sidebar-section-import"]').first().click();

    // The Import sidebar section is now the active one. The new sidebar uses
    // `data-active="true"` (and `aria-current="page"`) for the highlighted row, replacing the
    // ToggleGroup's `data-state="on"` attribute that the original cherry-pick used.
    const importToggle = frame.locator('[data-testid="manage-books-sidebar-section-import"]');
    await expect(importToggle).toHaveAttribute('data-active', 'true');

    // EVD-040 / EVD-041 placeholder: Import mode entered, file-picker handed off to host.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-040-menu-import.png`,
    });
  });

  // @scenario TS-088
  // DEF-UI-009 (FN-010): blocked by missing multi-select file picker. Reactivate
  // when papi.dialogs.selectFiles (or equivalent) ships.
  test.fixme(
    'should clear the import file list when a "Clear" affordance is exercised (BHV-320)',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      await mainPage
        .getByRole('menuitem', { name: /Project|Tools/i })
        .first()
        .click();
      await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
      const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

      await frame.locator('[data-testid="manage-books-sidebar-section-import"]').first().click();

      // Once the file-picker spike lands, this test populates files and verifies the
      // "clear filter" button (the Clear-list affordance, mapped to BHV-320 in the unified
      // dialog idiom) empties the grid.
      const clearBtn = frame.getByRole('button', { name: /Clear/i });
      await expect(clearBtn).toBeVisible({ timeout: 10_000 });
      await clearBtn.click();

      // EVD-043: cleared state.
      await mainPage.screenshot({
        path: `${SCREENSHOT_BASE}/EVD-043-cleared.png`,
      });
    },
  );

  // @scenario TS-058
  test('should preserve per-action selection when the user toggles between action modes', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // Switch to Delete and pick whatever the first present-book pill is.
    // The test originally hard-coded GEN, but earlier tests in this file run
    // a real DELETE-GEN mutation against the live project, so by the time
    // this test runs GEN may no longer be present in delete-mode universe.
    // Whichever book IS present in delete mode will exercise the per-action
    // selection-preservation contract just as well — the assertion isn't
    // about GEN specifically, it's about selectionsByAction[mode] surviving
    // a mode toggle.
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').first().click();
    const firstDeletablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
    await expect(firstDeletablePill).toBeVisible({ timeout: 10_000 });
    const bookId = await firstDeletablePill.getAttribute('data-book');
    expect(bookId, 'delete-mode universe must have at least one book').toBeTruthy();
    const bookSelector = `ul[role="listbox"] li[data-book="${bookId}"]`;
    await firstDeletablePill.click();
    await expect(firstDeletablePill).toHaveAttribute('aria-checked', 'true');

    // Switch to Create — selection should not bleed across (selectionsByAction is
    // per-mode).
    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();
    const sameBookInCreate = frame.locator(bookSelector);
    // The book may not even appear in Create mode (universe = books not present).
    // Whatever appears must NOT be aria-checked.
    if ((await sameBookInCreate.count()) > 0) {
      await expect(sameBookInCreate).toHaveAttribute('aria-checked', 'false');
    }

    // Switch back to Delete — selection preserved.
    await frame.locator('[data-testid="manage-books-sidebar-section-delete"]').first().click();
    await expect(frame.locator(bookSelector)).toHaveAttribute('aria-checked', 'true');
  });

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 5: Validation — VAL-100 / VAL-101 / VAL-103 / VAL-105 / VAL-105.1 / VAL-013 / VAL-012
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-051
  test('VAL-105.1: should disable the chapter/verse method when only non-canonical books are selected (A6)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();

    // Select only a non-canonical book (e.g. XXA / XXB / XXC if present in the universe;
    // they're available in Canon as "extras"). Falls back to selecting "FRT" (Front Matter)
    // which is non-canonical per Canon.IsCanonical.
    const xxaPill = frame.locator(
      'ul[role="listbox"] li[data-book="XXA"], ul[role="listbox"] li[data-book="FRT"]',
    );
    await expect(xxaPill.first()).toBeVisible({ timeout: 10_000 });
    await xxaPill.first().click();

    // Method dropdown: "With all chapter and verse numbers" item should be aria-disabled.
    const methodSelect = frame.locator('#af-method');
    await methodSelect.click();
    const cvOption = frame.getByRole('option', { name: /chapter and verse/i });
    await expect(cvOption).toBeVisible({ timeout: 5_000 });
    await expect(cvOption).toHaveAttribute('aria-disabled', 'true');

    // EVD-015: validation disablement.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-015-cv-disabled-non-canonical.png`,
    });
  });

  // @scenario TS-052
  test('VAL-100: should keep apply disabled when "Based on" method is chosen but no model project is picked', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();

    // Pick an arbitrary creatable book.
    const firstCreatablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
    await firstCreatablePill.click();

    // Switch method to "Based on" without picking a reference project.
    const methodSelect = frame.locator('#af-method');
    await methodSelect.click();
    await frame.getByRole('option', { name: /Based on/i }).click();

    // Reference picker visible but unset. Apply must be disabled (model required when
    // method is fromTemplate).
    const referenceSelect = frame.locator('#af-reference');
    await expect(referenceSelect).toBeVisible();
    const createApply = frame
      .locator('footer button')
      .filter({ hasText: /Create/i })
      .last();
    await expect(createApply).toBeDisabled();
  });

  // @scenario TS-054
  // GAP-002 FIX (P3U.1 ui-spec-validator post-IUG, 2026-05-02): the component now eagerly loads
  // the reference project's book inventory when the user picks a "Based on" model
  // (`useEffect([open, createReferenceId, refreshBooks])` in manage-books-dialog.component.tsx).
  // Before the fix, `createReferenceBookState.present` was always an empty Set, so EVERY selected
  // book appeared "missing" and the prompt always fired regardless of the underlying state — this
  // test passed for the wrong reason. After the fix, the prompt fires only when at least one
  // selected book is genuinely absent from the reference project.
  //
  // Functional verification of the missing-model branch end-to-end now requires a deterministic
  // fixture pair: a reference model project whose book set is a known proper subset of the
  // canonical books, and a target project that lets us select books from outside that subset.
  // The 10 fixture projects in this workspace share unpredictable, mutating book inventories
  // (each createBooks run writes USFM stubs that persist), so picking "first + last" from the
  // grid is no longer guaranteed to produce a missing-model book.
  //
  // Keeping the test as a contract reminder (test.fixme) until a deterministic fixture lands.
  // Component-level unit tests against manage-books-dialog.component.tsx (mocked loadBooks
  // returning a partial inventory) can already exercise the prompt logic directly without the
  // fixture problem.
  test.fixme(
    'EXT-102: should show missing-model-books prompt when not all selected books are in the model (A4)',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      await mainPage
        .getByRole('menuitem', { name: /Project|Tools/i })
        .first()
        .click();
      await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
      const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

      await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();

      // Pick multiple creatable books — at least one of which is unlikely to exist in the
      // chosen model project (the wiring layer fans out validateCreateBooks which surfaces
      // the missing-books pre-flight).
      const pills = frame.locator('ul[role="listbox"] li[data-book]');
      await expect(pills.first()).toBeVisible({ timeout: 10_000 });
      const total = await pills.count();
      // Pick first + last so the set is broad enough to trigger missing-in-model on most
      // models.
      await pills.nth(0).click();
      if (total > 1) await pills.nth(total - 1).click();

      // Method = Based on, pick first model.
      await frame.locator('#af-method').click();
      await frame.getByRole('option', { name: /Based on/i }).click();
      await frame.locator('#af-reference').click();
      // Scope the option lookup to the open Radix popper so we don't accidentally
      // click a book-grid option (those also have role="option").
      await frame.locator('[data-radix-popper-content-wrapper] [role="option"]').first().click();

      // Submit — pre-flight prompt opens (role="alertdialog" with title containing "not in
      // the model project").
      await frame
        .locator('footer button')
        .filter({ hasText: /Create/i })
        .last()
        .click();
      const preflightDialog = frame.locator('[role="alertdialog"]');
      await expect(preflightDialog).toBeVisible({ timeout: 10_000 });
      await expect(preflightDialog).toContainText(/not in the model project/i);

      // EVD-015: pre-flight validation.
      await mainPage.screenshot({
        path: `${SCREENSHOT_BASE}/EVD-015-validation-missing-model.png`,
      });
    },
  );

  // @scenario TS-053
  //
  // DEFERRED: All test projects in the local fixture set share versification = 4
  // (English). The component-level versification-mismatch wiring is exercised by
  // unit tests against `manage-books-dialog.component.tsx` (mocked
  // loadVersification returns differing strings); a true end-to-end mismatch
  // would require a non-English-versification project (e.g. Russian Orthodox or
  // Vulgate) in the fixture set, which is out of scope for WP-001. This test
  // remains as a contract reminder so that when such fixtures land we can
  // un-fixme it. Tracked alongside the existing test.fixme entries for FN-010.
  test.fixme(
    'EXT-103: should show versification-mismatch prompt when model uses different versification (A4)',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      await mainPage
        .getByRole('menuitem', { name: /Project|Tools/i })
        .first()
        .click();
      await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
      const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

      await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();

      const firstCreatablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
      await firstCreatablePill.click();
      await frame.locator('#af-method').click();
      await frame.getByRole('option', { name: /Based on/i }).click();
      await frame.locator('#af-reference').click();
      // Scope to the open popper to avoid matching book-grid options.
      await frame.locator('[data-radix-popper-content-wrapper] [role="option"]').first().click();
      await frame
        .locator('footer button')
        .filter({ hasText: /Create/i })
        .last()
        .click();

      // Either the missing-model prompt fires first; clicking Continue advances to the
      // versification-mismatch prompt when the model's versification differs.
      const dlg = frame.locator('[role="alertdialog"]');
      await expect(dlg).toBeVisible({ timeout: 10_000 });
      const continueBtn = dlg.getByRole('button', { name: /Continue/i });
      if (await continueBtn.isVisible()) {
        await continueBtn.click();
      }

      // After advancing, the dialog title should reference versification (only fires when
      // the destination and model versifications differ; otherwise the test concludes the
      // prompt was the missing-model variant alone).
      const versTitle = dlg.getByText(/Versification mismatch/i);
      // Soft assertion: the prompt text must be present in at least one of the two prompt
      // variants for this test to be meaningful — when it's not present, the assertion
      // fails clearly.
      await expect(versTitle).toBeVisible({ timeout: 5_000 });
    },
  );

  // @scenario TS-085
  // DEF-UI-009 (FN-010): blocked by missing multi-select file picker.
  test.fixme(
    'VAL-105 / VAL-012: should surface an overlap-error dialog when two import files map to the same book (A10)',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      await mainPage
        .getByRole('menuitem', { name: /Project|Tools/i })
        .first()
        .click();
      await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
      const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

      await frame.locator('[data-testid="manage-books-sidebar-section-import"]').first().click();

      // The wiring layer's parseImportFiles + checkOverlappingFiles flow surfaces the
      // overlap-error alertdialog when two files claim the same book number. Title key is
      // %manageBooks_import_overlapTitle% / "Two files map to the same book".
      const overlapDialog = frame.locator('[role="alertdialog"]').filter({
        hasText: /map to the same book|same book/i,
      });
      await expect(overlapDialog).toBeVisible({ timeout: 15_000 });

      // EVD-045: overlap error displayed.
      await mainPage.screenshot({
        path: `${SCREENSHOT_BASE}/EVD-045-overlap-error.png`,
      });
    },
  );

  // @scenario TS-084
  // DEF-UI-009 (FN-010): blocked by missing multi-select file picker.
  test.fixme(
    'VAL-104 / BHV-112: should show the USX confirmation prompt before importing .usx files (A9)',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      await mainPage
        .getByRole('menuitem', { name: /Project|Tools/i })
        .first()
        .click();
      await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
      const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

      await frame.locator('[data-testid="manage-books-sidebar-section-import"]').first().click();

      // The USX-confirm dialog (role="alertdialog", title key
      // %manageBooks_import_usxConfirmTitle% — "Import USX files?") fires when any selected
      // file ends in .usx or .xml. The wiring layer must surface it BEFORE the import
      // mutation. The file-picker spike provides the .usx fixture for this test.
      const usxDialog = frame.locator('[role="alertdialog"]').filter({
        hasText: /Import USX files/i,
      });
      await expect(usxDialog).toBeVisible({ timeout: 15_000 });
      await expect(usxDialog.getByRole('button', { name: /^Import$/i })).toBeVisible();
      await expect(usxDialog.getByRole('button', { name: /Cancel/i })).toBeVisible();
    },
  );

  // @scenario TS-086
  // DEF-UI-009 (FN-010): blocked by missing multi-select file picker. Also, the
  // in-dialog result panel was removed per Theme C1 — assertion needs to migrate
  // to a Sonner-toaster locator before reactivation.
  test.fixme(
    'VAL-013 / Theme 6: should surface AlertEntry permission errors via a result panel after import',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      await mainPage
        .getByRole('menuitem', { name: /Project|Tools/i })
        .first()
        .click();
      await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
      const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

      await frame.locator('[data-testid="manage-books-sidebar-section-import"]').first().click();

      // After an import that hits a per-book permission gate, the wiring layer maps
      // result.errors AlertEntry[] into either toasts (per A5 canonical surface) or the
      // in-dialog result panel (`role="alert"` with aria-live="polite" — line 1973 of the
      // component). We assert the panel surfaces a permission-related error message; if A5
      // wiring routes everything to toasts the test will need to assert via the Sonner
      // toaster instead.
      const resultPanel = frame.locator('[role="alert"]');
      await expect(resultPanel).toBeVisible({ timeout: 30_000 });
      await expect(resultPanel).toContainText(/permission|edit/i);
    },
  );

  // ═══════════════════════════════════════════════════════════════════════════════════════
  // Category 6: Edge Cases — empty data, loading, focus restoration, dismiss path
  // ═══════════════════════════════════════════════════════════════════════════════════════

  // @scenario TS-002, TS-049
  test('should render an empty-state message when no books match the active filter', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // Type a guaranteed-no-match filter into the always-present filter input.
    await frame.getByRole('textbox', { name: /Filter books/i }).fill('zzzzzz_no_match_zzzzzz');

    // The empty-state shows a "Clear filter" button when the filter caused the empty
    // state (per the component's isFilterEmptyState branch at line 1805).
    const clearFilterBtn = frame.getByRole('button', { name: /Clear filter/i });
    await expect(clearFilterBtn).toBeVisible({ timeout: 5_000 });
    await clearFilterBtn.click();

    // After clearing, books reappear.
    await expect(frame.locator('ul[role="listbox"] li[data-book="GEN"]')).toBeVisible({
      timeout: 5_000,
    });
  });

  // @scenario TS-049, TS-089
  test('should close the dialog (web view tab dismissed) when Close is clicked from View mode (EVD-003)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const tab = mainPage.locator('.dock-tab', { hasText: WEB_VIEW_TITLE_REGEX });
    await expect(tab).toBeVisible({ timeout: 15_000 });
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame
      .locator('footer')
      .getByRole('button', { name: /^Close$/i })
      .click();

    // Tab is removed from the dock.
    await expect(tab).toBeHidden({ timeout: 10_000 });

    // EVD-003: dialog dismissed.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-003-dialog-closed.png`,
    });
  });

  // @scenario TS-049, TS-072
  test('should disable the apply button while a mutation is in flight and show the spinner (A3)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    await frame.locator('[data-testid="manage-books-sidebar-section-create"]').first().click();
    const firstCreatablePill = frame.locator('ul[role="listbox"] li[data-book]').first();
    await firstCreatablePill.click();
    const createApply = frame
      .locator('footer button')
      .filter({ hasText: /Create/i })
      .last();
    await createApply.click();

    // While createBooks is pending, the apply button must be disabled and the cancel
    // button must be disabled (A3 acceptance — isSubmitting state).
    await expect(createApply).toBeDisabled({ timeout: 5_000 });
    const cancelBtn = frame.getByRole('button', { name: /Cancel/i });
    await expect(cancelBtn).toBeDisabled();

    // Live region announces "Creating books...". The footer renders the message twice — once
    // in an aria-live sr-only span (for screen readers) and once in a visible span next to
    // the spinner. Strict mode requires we pick one; the visible (non-sr-only) variant is
    // what the user actually sees, so assert against `.first()` of the matching nodes.
    await expect(
      frame
        .locator('footer')
        .getByText(/Creating/i)
        .first(),
    ).toBeVisible({ timeout: 10_000 });
  });

  // @scenario TS-049
  test('should render the books-present subtitle reflecting the canonical book count (BHV-300)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await mainPage
      .getByRole('menuitem', { name: /Project|Tools/i })
      .first()
      .click();
    await mainPage.getByRole('menuitem', { name: MENU_LABEL_REGEX }).click();
    const frame = mainPage.frameLocator(`iframe[title*="Manage Books" i]`);

    // The header subtitle from ui-spec-manage-books.md Header section reads e.g.
    // "30 of 88 canonical books in WEB (eng_versification)". The wiring layer subscribes
    // to platformScripture.booksPresent — the exact count depends on the active project,
    // so we assert the regex pattern, not a literal count.
    const subtitle = frame.getByText(/\d+\s+of\s+\d+/i);
    await expect(subtitle.first()).toBeVisible({ timeout: 10_000 });
  });
});
