/**
 * Generated types using `nx generate markers-data` with
 * 'https://raw.githubusercontent.com/ubsicap/usfm/refs/heads/master/sty/usfm.sty'
 */

export enum CategoryType {
  FileIdentification = 'FileIdentification',
  Headers = 'Headers',
  Remarks = 'Remarks',
  Introduction = 'Introduction',
  DivisionMarks = 'DivisionMarks',
  Paragraphs = 'Paragraphs',
  Poetry = 'Poetry',
  TitlesHeadings = 'TitlesHeadings',
  Tables = 'Tables',
  CenterTables = 'CenterTables',
  RightTables = 'RightTables',
  Lists = 'Lists',
  Footnotes = 'Footnotes',
  CrossReferences = 'CrossReferences',
  SpecialText = 'SpecialText',
  CharacterStyling = 'CharacterStyling',
  Breaks = 'Breaks',
  SpecialFeatures = 'SpecialFeatures',
  PeripheralReferences = 'PeripheralReferences',
  PeripheralMaterials = 'PeripheralMaterials',
  Uncategorized = 'Uncategorized',
}

export enum MarkerType {
  Paragraph = 'Paragraph',
  Character = 'Character',
  Note = 'Note',
  Unknown = 'Unknown',
}

export interface Marker {
  category: CategoryType;
  type: MarkerType;
  description: string;
  hasEndMarker: boolean;
  children?: Partial<{ [K in CategoryType]: string[] }>;
}

// TODO: Incorporate `.sty` files to allow user customization and more standard marker data storage
export const usfmMarkers: { [marker: string]: Marker } = {
  id: {
    category: CategoryType.FileIdentification,
    type: MarkerType.Paragraph,
    description: 'File identification information (BOOKID, FILENAME, EDITOR, MODIFICATION DATE)',
    hasEndMarker: false,
    children: {
      FileIdentification: ['usfm', 'ide'],
      Headers: ['h', 'h1', 'h2', 'h3', 'toc1', 'toc2', 'toc3'],
      Remarks: ['rem', 'sts', 'restore'],
      Introduction: [
        'imt',
        'imt1',
        'imt2',
        'imt3',
        'imt4',
        'imte',
        'imte1',
        'imte2',
        'is',
        'is1',
        'is2',
        'iot',
        'io',
        'io1',
        'io2',
        'io3',
        'io4',
        'ior',
        'ip',
        'im',
        'ipi',
        'imi',
        'ili',
        'ili1',
        'ili2',
        'ipq',
        'imq',
        'ipr',
        'ib',
        'iq',
        'iq1',
        'iq2',
        'iq3',
        'iex',
        'ie',
      ],
      DivisionMarks: ['c', 'cl'],
      TitlesHeadings: ['mt', 'mt1', 'mt2', 'mt3', 'mt4'],
    },
  },
  usfm: {
    category: CategoryType.FileIdentification,
    type: MarkerType.Paragraph,
    description: 'File markup version information',
    hasEndMarker: false,
    children: undefined,
  },
  ide: {
    category: CategoryType.FileIdentification,
    type: MarkerType.Paragraph,
    description: 'File encoding information',
    hasEndMarker: false,
    children: {
      Remarks: ['rem', 'sts'],
    },
  },
  h: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Running header text for a book (basic)',
    hasEndMarker: false,
    children: {
      Headers: ['toc1', 'toc2', 'toc3', 'toca1', 'toca2', 'toca3'],
    },
  },
  h1: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Running header text',
    hasEndMarker: false,
    children: {
      Headers: ['toc1', 'toc2', 'toc3', 'toca1', 'toca2', 'toca3'],
    },
  },
  h2: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Running header text, left side of page',
    hasEndMarker: false,
    children: {
      Headers: ['toc1', 'toc2', 'toc3', 'toca1', 'toca2', 'toca3'],
    },
  },
  h3: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Running header text, right side of page',
    hasEndMarker: false,
    children: {
      Headers: ['toc1', 'toc2', 'toc3', 'toca1', 'toca2', 'toca3'],
    },
  },
  toc1: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Long table of contents text',
    hasEndMarker: false,
    children: undefined,
  },
  toc2: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Short table of contents text',
    hasEndMarker: false,
    children: undefined,
  },
  toc3: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Book Abbreviation',
    hasEndMarker: false,
    children: undefined,
  },
  toca1: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Alternative language long table of contents text',
    hasEndMarker: false,
    children: undefined,
  },
  toca2: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Alternative language short table of contents text',
    hasEndMarker: false,
    children: undefined,
  },
  toca3: {
    category: CategoryType.Headers,
    type: MarkerType.Paragraph,
    description: 'Alternative language book Abbreviation',
    hasEndMarker: false,
    children: undefined,
  },
  rem: {
    category: CategoryType.Remarks,
    type: MarkerType.Paragraph,
    description: 'Comments and remarks',
    hasEndMarker: false,
    children: undefined,
  },
  sts: {
    category: CategoryType.Remarks,
    type: MarkerType.Paragraph,
    description: 'Status of this file',
    hasEndMarker: false,
    children: undefined,
  },
  restore: {
    category: CategoryType.Remarks,
    type: MarkerType.Paragraph,
    description: 'Project restore information',
    hasEndMarker: false,
    children: undefined,
  },
  imt: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction major title, level 1 (if single level) (basic)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imt1: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction major title, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imt2: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction major title, level 2',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imt3: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction major title, level 3',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imt4: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction major title, level 4 (usually within parenthesis)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imte: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction major title at introduction end, level 1 (if single level)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imte1: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction major title at introduction end, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imte2: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction major title at introduction end, level 2',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  is: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction section heading, level 1 (if single level) (basic)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
      CharacterStyling: ['no'],
    },
  },
  is1: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction section heading, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  is2: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction section heading, level 2',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  iot: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction outline title (basic)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CharacterStyling: ['no'],
    },
  },
  io: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction outline text, level 1 (if single level)',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  io1: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction outline text, level 1 (if multiple levels) (basic)',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  io2: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction outline text, level 2',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  io3: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction outline text, level 3',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  io4: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction outline text, level 4',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ior: {
    category: CategoryType.Introduction,
    type: MarkerType.Character,
    description:
      'Introduction references range for outline entry; for marking references separately',
    hasEndMarker: true,
    children: undefined,
  },
  ip: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction prose paragraph (basic)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  im: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction prose paragraph, with no first line indent (may occur after poetry)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ipi: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction prose paragraph, indented, with first line indent',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  imi: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction prose paragraph text, indented, with no first line indent',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ili: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'A list entry, level 1 (if single level)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ili1: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'A list entry, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ili2: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'A list entry, level 2',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ipq: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction prose paragraph, quote from the body text',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  imq: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description:
      'Introduction prose paragraph, quote from the body text, with no first line indent',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ipr: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction prose paragraph, right aligned',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ib: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction blank line',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
    },
  },
  iq: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction poetry text, level 1 (if single level)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  iq1: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction poetry text, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  iq2: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction poetry text, level 2',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  iq3: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction poetry text, level 3',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  iex: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description:
      'Introduction explanatory or bridge text (e.g. explanation of missing book in Short Old Testament)',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CharacterStyling: ['no'],
    },
  },
  iqt: {
    category: CategoryType.Introduction,
    type: MarkerType.Character,
    description: 'For quoted scripture text appearing in the introduction',
    hasEndMarker: true,
    children: undefined,
  },
  ie: {
    category: CategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: 'Introduction ending marker',
    hasEndMarker: false,
    children: undefined,
  },
  c: {
    category: CategoryType.DivisionMarks,
    type: MarkerType.Paragraph,
    description: 'Chapter number',
    hasEndMarker: false,
    children: undefined,
  },
  ca: {
    category: CategoryType.DivisionMarks,
    type: MarkerType.Character,
    description:
      'Second (alternate) chapter number (for coding dual versification; useful for places where different traditions of chapter breaks need to be supported in the same translation)',
    hasEndMarker: true,
    children: undefined,
  },
  cp: {
    category: CategoryType.DivisionMarks,
    type: MarkerType.Paragraph,
    description:
      'Published chapter number (chapter string that should appear in the published text)',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
    },
  },
  cl: {
    category: CategoryType.DivisionMarks,
    type: MarkerType.Paragraph,
    description:
      "Chapter label used for translations that add a word such as 'Chapter' before chapter numbers (e.g. Psalms). The subsequent text is the chapter label.",
    hasEndMarker: false,
    children: undefined,
  },
  cd: {
    category: CategoryType.DivisionMarks,
    type: MarkerType.Paragraph,
    description: 'Chapter Description (Publishing option D, e.g. in Russian Bibles)',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['vp'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  v: {
    category: CategoryType.DivisionMarks,
    type: MarkerType.Character,
    description: 'A verse number',
    hasEndMarker: false,
    children: undefined,
  },
  va: {
    category: CategoryType.DivisionMarks,
    type: MarkerType.Character,
    description:
      'Second (alternate) verse number (for coding dual numeration in Psalms; see also NRSV Exo 22.1-4)',
    hasEndMarker: true,
    children: undefined,
  },
  vp: {
    category: CategoryType.DivisionMarks,
    type: MarkerType.Character,
    description: 'Published verse marker (verse string that should appear in the published text)',
    hasEndMarker: true,
    children: undefined,
  },
  p: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Paragraph text, with first line indent (basic)',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p', 'pmo', 'pm', 'pmc', 'pmr'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  m: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Paragraph text, with no first line indent (may occur after poetry) (basic)',
    hasEndMarker: false,
    children: {
      Paragraphs: ['pmo', 'pm', 'pmc', 'pmr'],
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  po: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Letter opening',
    hasEndMarker: false,
    children: {
      Paragraphs: ['pmo', 'pm', 'pmc', 'pmr'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pr: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Text refrain (paragraph text, right aligned)',
    hasEndMarker: false,
    children: {
      Paragraphs: ['pmo', 'pm', 'pmc', 'pmr'],
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  cls: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Letter Closing',
    hasEndMarker: false,
    children: {
      SpecialText: ['tl', 'sig', 'pn', 'png', 'addpn', 'add'],
    },
  },
  pmo: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Embedded text opening',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pm: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Embedded text paragraph',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pmc: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Embedded text closing',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pmr: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: "Embedded text refrain (e.g. Then all the people shall say, 'Amen!')",
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pi: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description:
      'Paragraph text, level 1 indent (if single level), with first line indent; often used for discourse (basic)',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pi1: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description:
      'Paragraph text, level 1 indent (if multiple levels), with first line indent; often used for discourse',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pi2: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Paragraph text, level 2 indent, with first line indent; often used for discourse',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pi3: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Paragraph text, level 3 indent, with first line indent; often used for discourse',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pc: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Paragraph text, centered (for Inscription)',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  mi: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: 'Paragraph text, indented, with no first line indent; often used for discourse',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  nb: {
    category: CategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description:
      'Paragraph text, with no break from previous paragraph text (at chapter boundary) (basic)',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, level 1 indent (if single level)',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3', 'q', 'q1', 'q2', 'q3', 'q4', 'b'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q1: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, level 1 indent (if multiple levels) (basic)',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3', 'q', 'q1', 'q2', 'q3', 'q4', 'b'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q2: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, level 2 indent (basic)',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b', 'qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q3: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, level 3 indent',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b', 'qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q4: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, level 4 indent',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b', 'qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qc: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, centered',
    hasEndMarker: false,
    children: {
      Poetry: ['qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qr: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, Right Aligned',
    hasEndMarker: false,
    children: {
      Poetry: ['qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qs: {
    category: CategoryType.Poetry,
    type: MarkerType.Character,
    description: 'Poetry text, Selah',
    hasEndMarker: true,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  qa: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, Acrostic marker/heading',
    hasEndMarker: false,
    children: undefined,
  },
  qac: {
    category: CategoryType.Poetry,
    type: MarkerType.Character,
    description: 'Poetry text, Acrostic markup of the first character of a line of acrostic poetry',
    hasEndMarker: true,
    children: undefined,
  },
  qm: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, embedded, level 1 indent (if single level)',
    hasEndMarker: false,
    children: {
      Paragraphs: ['p'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qm1: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, embedded, level 1 indent (if multiple levels)',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qm2: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, embedded, level 2 indent',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qm3: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text, embedded, level 3 indent',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qd: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description:
      'A Hebrew musical performance annotation, similar in content to Hebrew descriptive title.',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  b: {
    category: CategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: 'Poetry text stanza break (e.g. stanza break) (basic)',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b'],
      TitlesHeadings: [
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
    },
  },
  mt: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'The main title of the book (if single level)',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  mt1: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'The main title of the book (if multiple levels) (basic)',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  mt2: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A secondary title usually occurring before the main title (basic)',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  mt3: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A secondary title occurring after the main title',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  mt4: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A small secondary title sometimes occurring within parentheses',
    hasEndMarker: false,
    children: undefined,
  },
  mte: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description:
      'The main title of the book repeated at the end of the book, level 1 (if single level)',
    hasEndMarker: false,
    children: undefined,
  },
  mte1: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description:
      'The main title of the book repeated at the end of the book, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte2'],
    },
  },
  mte2: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: "A secondary title occurring before or after the 'ending' main title",
    hasEndMarker: false,
    children: undefined,
  },
  ms: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A major section division heading, level 1 (if single level) (basic)',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mr'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ms1: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A major section division heading, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mr'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ms2: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A major section division heading, level 2',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mr'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ms3: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A major section division heading, level 3',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mr'],
      Footnotes: ['f', 'fe'],
    },
  },
  mr: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A major section division references range heading (basic)',
    hasEndMarker: false,
    children: undefined,
  },
  s: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A section heading, level 1 (if single level) (basic)',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  s1: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A section heading, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  s2: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A section heading, level 2 (e.g. Proverbs 22-24)',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  s3: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: "A section heading, level 3 (e.g. Genesis 'The First Day')",
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  s4: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A section heading, level 4',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  sr: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A section division references range heading',
    hasEndMarker: false,
    children: undefined,
  },
  r: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'Parallel reference(s) (basic)',
    hasEndMarker: false,
    children: undefined,
  },
  sp: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A heading, to identify the speaker (e.g. Job)',
    hasEndMarker: false,
    children: {
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  d: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'A Hebrew text heading, to provide description (e.g. Psalms)',
    hasEndMarker: false,
    children: {
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  sd: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'Vertical space used to divide the text into sections, level 1 (if single level)',
    hasEndMarker: false,
    children: undefined,
  },
  sd1: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description:
      'Vertical space used to divide the text into sections, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: undefined,
  },
  sd2: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'Vertical space used to divide the text into sections, level 2',
    hasEndMarker: false,
    children: undefined,
  },
  sd3: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'Vertical space used to divide the text into sections, level 3',
    hasEndMarker: false,
    children: undefined,
  },
  sd4: {
    category: CategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: 'Vertical space used to divide the text into sections, level 4',
    hasEndMarker: false,
    children: undefined,
  },
  lh: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'List header (introductory remark)',
    hasEndMarker: false,
    children: {
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'A list entry, level 1 (if single level)',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li1: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'A list entry, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li2: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'A list entry, level 2',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li3: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'A list entry, level 3',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li4: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'A list entry, level 4',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lf: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'List footer (concluding remark)',
    hasEndMarker: false,
    children: {
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'An embedded list entry, level 1 (if single level)',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim1: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'An embedded list entry, level 1 (if multiple levels)',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim2: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'An embedded list entry, level 2',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim3: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'An embedded list item, level 3',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim4: {
    category: CategoryType.Lists,
    type: MarkerType.Paragraph,
    description: 'An embedded list entry, level 4',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  litl: {
    category: CategoryType.Lists,
    type: MarkerType.Character,
    description: 'List entry total text',
    hasEndMarker: true,
    children: undefined,
  },
  lik: {
    category: CategoryType.Lists,
    type: MarkerType.Character,
    description: 'Structured list entry key text',
    hasEndMarker: true,
    children: undefined,
  },
  liv: {
    category: CategoryType.Lists,
    type: MarkerType.Character,
    description: 'Structured list entry value 1 content (if single value)',
    hasEndMarker: true,
    children: undefined,
  },
  liv1: {
    category: CategoryType.Lists,
    type: MarkerType.Character,
    description: 'Structured list entry value 1 content (if multiple values)',
    hasEndMarker: true,
    children: undefined,
  },
  liv2: {
    category: CategoryType.Lists,
    type: MarkerType.Character,
    description: 'Structured list entry value 2 content',
    hasEndMarker: true,
    children: undefined,
  },
  liv3: {
    category: CategoryType.Lists,
    type: MarkerType.Character,
    description: 'Structured list entry value 3 content',
    hasEndMarker: true,
    children: undefined,
  },
  liv4: {
    category: CategoryType.Lists,
    type: MarkerType.Character,
    description: 'Structured list entry value 4 content',
    hasEndMarker: true,
    children: undefined,
  },
  liv5: {
    category: CategoryType.Lists,
    type: MarkerType.Character,
    description: 'Structured list entry value 5 content',
    hasEndMarker: true,
    children: undefined,
  },
  f: {
    category: CategoryType.Footnotes,
    type: MarkerType.Note,
    description: 'A Footnote text item (basic)',
    hasEndMarker: true,
    children: {
      Footnotes: ['fr', 'ft', 'fk', 'fq', 'fqa', 'fl', 'fw', 'fp', 'fv', 'fdc'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  fe: {
    category: CategoryType.Footnotes,
    type: MarkerType.Note,
    description: 'An Endnote text item',
    hasEndMarker: true,
    children: {
      Footnotes: ['fr', 'ft', 'fk', 'fq', 'fqa', 'fl', 'fw', 'fp', 'fv', 'fdc'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  fr: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'The origin reference for the footnote (basic)',
    hasEndMarker: true,
    children: undefined,
  },
  ft: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'Footnote text, Protocanon (basic)',
    hasEndMarker: true,
    children: undefined,
  },
  fk: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'A footnote keyword (basic)',
    hasEndMarker: true,
    children: undefined,
  },
  fq: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'A footnote scripture quote or alternate rendering (basic)',
    hasEndMarker: true,
    children: undefined,
  },
  fqa: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'A footnote alternate rendering for a portion of scripture text',
    hasEndMarker: true,
    children: undefined,
  },
  fl: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description:
      "A footnote label text item, for marking or 'labelling' the type or alternate translation being provided in the note.",
    hasEndMarker: true,
    children: undefined,
  },
  fw: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description:
      'A footnote witness list, for distinguishing a list of sigla representing witnesses in critical editions.',
    hasEndMarker: true,
    children: undefined,
  },
  fp: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'A Footnote additional paragraph marker',
    hasEndMarker: true,
    children: undefined,
  },
  fv: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'A verse number within the footnote text',
    hasEndMarker: true,
    children: undefined,
  },
  fdc: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'Footnote text, applies to Deuterocanon only',
    hasEndMarker: true,
    children: undefined,
  },
  fm: {
    category: CategoryType.Footnotes,
    type: MarkerType.Character,
    description: 'An additional footnote marker location for a previous footnote',
    hasEndMarker: true,
    children: undefined,
  },
  x: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Note,
    description: 'A list of cross references (basic)',
    hasEndMarker: true,
    children: {
      CrossReferences: ['xo', 'xop', 'xt', 'xta', 'xk', 'xq', 'xot', 'xnt', 'xdc'],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  xo: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'The cross reference origin reference (basic)',
    hasEndMarker: true,
    children: undefined,
  },
  xop: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description:
      'Published cross reference origin reference (origin reference that should appear in the published text)',
    hasEndMarker: true,
    children: undefined,
  },
  xt: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'The cross reference target reference(s), protocanon only (basic)',
    hasEndMarker: true,
    children: undefined,
  },
  xta: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'Cross reference target references added text',
    hasEndMarker: true,
    children: undefined,
  },
  xk: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'A cross reference keyword',
    hasEndMarker: true,
    children: undefined,
  },
  xq: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'A cross-reference quotation from the scripture text',
    hasEndMarker: true,
    children: undefined,
  },
  xot: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'Cross-reference target reference(s), Old Testament only',
    hasEndMarker: true,
    children: undefined,
  },
  xnt: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'Cross-reference target reference(s), New Testament only',
    hasEndMarker: true,
    children: undefined,
  },
  xdc: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'Cross-reference target reference(s), Deuterocanon only',
    hasEndMarker: true,
    children: undefined,
  },
  rq: {
    category: CategoryType.CrossReferences,
    type: MarkerType.Character,
    description: 'A cross-reference indicating the source text for the preceding quotation.',
    hasEndMarker: true,
    children: undefined,
  },
  qt: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For Old Testament quoted text appearing in the New Testament (basic)',
    hasEndMarker: true,
    children: undefined,
  },
  nd: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For name of deity (basic)',
    hasEndMarker: true,
    children: undefined,
  },
  tl: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For transliterated words',
    hasEndMarker: true,
    children: undefined,
  },
  dc: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'Deuterocanonical/LXX additions or insertions in the Protocanonical text',
    hasEndMarker: true,
    children: undefined,
  },
  bk: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For the quoted name of a book',
    hasEndMarker: true,
    children: undefined,
  },
  sig: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For the signature of the author of an Epistle',
    hasEndMarker: true,
    children: undefined,
  },
  pn: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For a proper name',
    hasEndMarker: true,
    children: undefined,
  },
  png: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For a geographic proper name',
    hasEndMarker: true,
    children: undefined,
  },
  addpn: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For chinese words to be dot underline & underline',
    hasEndMarker: true,
    children: undefined,
  },
  wj: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For marking the words of Jesus',
    hasEndMarker: true,
    children: undefined,
  },
  k: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For a keyword',
    hasEndMarker: true,
    children: undefined,
  },
  sls: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description:
      'To represent where the original text is in a secondary language or from an alternate text source',
    hasEndMarker: true,
    children: undefined,
  },
  ord: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For the text portion of an ordinal number',
    hasEndMarker: true,
    children: undefined,
  },
  add: {
    category: CategoryType.SpecialText,
    type: MarkerType.Character,
    description: 'For a translational addition to the text',
    hasEndMarker: true,
    children: undefined,
  },
  lit: {
    category: CategoryType.SpecialText,
    type: MarkerType.Paragraph,
    description: 'For a comment or note inserted for liturgical use',
    hasEndMarker: false,
    children: undefined,
  },
  no: {
    category: CategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: 'A character style, use normal text',
    hasEndMarker: true,
    children: undefined,
  },
  it: {
    category: CategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: 'A character style, use italic text',
    hasEndMarker: true,
    children: undefined,
  },
  bd: {
    category: CategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: 'A character style, use bold text',
    hasEndMarker: true,
    children: undefined,
  },
  bdit: {
    category: CategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: 'A character style, use bold + italic text',
    hasEndMarker: true,
    children: undefined,
  },
  em: {
    category: CategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: 'A character style, use emphasized text style',
    hasEndMarker: true,
    children: undefined,
  },
  sc: {
    category: CategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: 'A character style, for small capitalization text',
    hasEndMarker: true,
    children: undefined,
  },
  sup: {
    category: CategoryType.CharacterStyling,
    type: MarkerType.Character,
    description:
      'A character style, for superscript text. Typically for use in critical edition footnotes.',
    hasEndMarker: true,
    children: undefined,
  },
  pb: {
    category: CategoryType.Breaks,
    type: MarkerType.Paragraph,
    description:
      "Page Break used for new reader portions and children's bibles where content is controlled by the page",
    hasEndMarker: false,
    children: undefined,
  },
};
