import { LegacyCommentThread } from 'legacy-comment-manager';

const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const twoDaysAgo = new Date(today);
twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);

export const sampleComments: LegacyCommentThread[] = [
  {
    id: 'thread-1',
    comments: [
      {
        id: '1',
        user: 'Allison Park',
        contents:
          '<p>I noticed some interesting parallels between this verse and <em>Psalm 18:2</em>. The imagery of God as a refuge appears throughout the Psalms, emphasizing the theme of divine protection. What do others think about the consistency of this metaphor?</p>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-1',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
      {
        id: '2',
        user: 'Beth Bee',
        contents:
          '<p>Great observation! I think we should also consider how this connects to the historical context. The word &ldquo;refuge&rdquo; (<span dir="rtl">מַחֲסֶה</span>) here carries a strong connotation of physical protection, which would have resonated deeply with the original audience.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-1',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
      {
        id: '3',
        user: 'David Echo',
        contents:
          '<p>✅ Good insights from both of you. Let&apos;s make sure to incorporate these nuances in the translation notes.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-1',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: 'Beth Bee',
    replyToUser: 'Allison Park',
    modifiedDate: today.toISOString(),
    verseRef: 'Psalm 46:1',
    verse: 'God is our refuge and strength, an ever-present help in trouble.',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
  },
  {
    id: 'thread-2',
    comments: [
      {
        id: '4',
        user: 'Charlie Delta',
        contents:
          '<p>Consider revising this portion for clarity:</p><blockquote>God is our refuge</blockquote><p>Maybe we could expand on what &ldquo;refuge&rdquo; means in this context? Some target languages might need a more explicit description.</p>',
        date: yesterday.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-2',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: 'God is our refuge',
      },
      {
        id: '6',
        user: 'Beth Bee',
        contents:
          '<p>I agree with Charlie. In some languages, the word for "refuge" might not exist, so we may need to use a descriptive phrase like <strong>safe place</strong> or <em>shelter from danger</em>.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-2',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
      {
        id: '7',
        user: 'David Echo',
        contents:
          '<p>Good points! Let&apos;s make sure to add a note for translators about this. Also, should we clarify what "trouble" means in this context?</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-2',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
    ],
    status: 'Unspecified',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: yesterday.toISOString(),
    verseRef: 'Psalm 46:1',
    verse: 'God is our refuge and strength, an ever-present help in trouble.',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
  },
  {
    id: 'thread-3',
    comments: [
      {
        id: '5',
        user: 'Eve Fox',
        contents:
          '<h1>Translation Workshop Notes</h1><h2>1. Key terms identified:</h2><ul><li>refuge (<span dir="rtl">מַחֲסֶה</span>)</li><li>strength (<span dir="rtl">עֹז</span>)</li><li>trouble (<span dir="rtl">צָרָה</span>)</li></ul><h2>2. Alternative renderings to consider:</h2><ul><li>&ldquo;safe place&rdquo; for &ldquo;refuge&rdquo;</li><li>&ldquo;power&rdquo; for &ldquo;strength&rdquo;</li><li>&ldquo;difficult times&rdquo; for &ldquo;trouble&rdquo;</li></ul><h2>3. Cultural considerations:</h2><ul><li>Military imagery</li><li>Ancient city fortifications</li><li>Divine protection metaphors</li></ul>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-3',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
      {
        id: '8',
        user: 'Charlie Delta',
        contents:
          '<p>Thanks for the summary, Eve! I think the cultural notes are especially helpful for teams working in different regions.</p>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-3',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
      {
        id: '9',
        user: 'Beth Bee',
        contents:
          '<p>One more suggestion: should we add a note about the poetic structure of this Psalm? It might help translators preserve the literary feel.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-3',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: 'Frank Graham',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'Psalm 46:1',
    verse: 'God is our refuge and strength, an ever-present help in trouble.',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: true,
    isConsultantNote: false,
  },
  {
    id: 'thread-4',
    comments: [
      {
        id: '10',
        user: 'Frank Graham',
        contents: '<p>This verse is a great encouragement. No changes needed from my side.</p>',
        date: today.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-4',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'Psalm 46:1',
    verse: 'God is our refuge and strength, an ever-present help in trouble.',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
  },
  {
    id: 'thread-5',
    comments: [
      {
        id: '11',
        user: 'Allison Park',
        contents:
          '<p>Thanks for the summary, Eve! I think the cultural notes are especially helpful for teams working in different regions.</p>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-5',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
    ],
    status: 'Todo',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'Psalm 46:1',
    verse: 'God is our refuge and strength, an ever-present help in trouble.',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
  },
  {
    id: 'thread-6',
    comments: [
      {
        id: '12',
        user: 'Jane Doe',
        contents: '<p>This verse is a great encouragement. No changes needed from my side.</p>',
        date: twoDaysAgo.toISOString(),
        deleted: false,
        hideInTextWindow: false,
        language: 'en',
        startPosition: 0,
        thread: 'thread-6',
        verse: 'God is our refuge and strength, an ever-present help in trouble.',
        verseRef: 'Psalm 46:1',
        selectedText: '',
      },
    ],
    status: 'Resolved',
    type: 'Normal',
    assignedUser: '',
    replyToUser: '',
    modifiedDate: today.toISOString(),
    verseRef: 'Psalm 46:1',
    verse: 'God is our refuge and strength, an ever-present help in trouble.',
    contextScrTextName: 'WEB',
    isSpellingNote: false,
    isBTNote: false,
    isConsultantNote: false,
  },
];
