/*
 * auto-generated by derive-storybook-mock.ts; do not edit by hand.
 *
 * Command: compareBackupFile
 * Callback kind: awaited
 *
 * Stories should import these handlers and pass them as Storybook args.
 * UX may tune *story args* (which handler to wire up) but should never edit
 * this file directly — it is regenerated every time the script runs.
 */

type Args = unknown[];

const compareBackupFileSample = {
  config: {
    displayOptions: 'showToolbar',
    initialBookId: 'GEN',
    initialChapter: 1,
    initialVerse: 3.14,
    leftLabelKey: 'Sample leftLabelKey',
    leftSourceToken: 'Sample leftSourceToken',
    rightLabelKey: 'Sample rightLabelKey',
    rightSourceToken: 'Sample rightSourceToken',
  },
  status: null,
};

export async function defaultCompareBackupFileHandler(..._args: Args): Promise<unknown> {
  return compareBackupFileSample;
}

export async function emptyCompareBackupFileHandler(..._args: Args): Promise<unknown> {
  return {};
}

export async function SessionUnknownInvalidSessionCompareBackupFileHandler(
  ..._args: Args
): Promise<never> {
  throw { code: -32020, message: 'Session unknown (INVALID_SESSION)' };
}

export async function FileIdNotInCompareBackupFileHandler(..._args: Args): Promise<never> {
  throw { code: -32025, message: 'File id not in session (FILE_NOT_FOUND)' };
}

export async function CannotCompareFileDoesCompareBackupFileHandler(
  ..._args: Args
): Promise<never> {
  throw {
    code: -32026,
    message:
      'Cannot compare — file does not exist on disk, or canViewDifferences === false (CANNOT_COMPARE)',
  };
}
