/*
 * auto-generated by derive-storybook-mock.ts; do not edit by hand.
 *
 * Command: createBackup
 * Callback kind: awaited
 *
 * Stories should import these handlers and pass them as Storybook args.
 * UX may tune *story args* (which handler to wire up) but should never edit
 * this file directly — it is regenerated every time the script runs.
 */

type Args = unknown[];

const createBackupSample = {
  backupLogEntryWritten: true,
  destinationPath: '/sample/path',
  fileSizeBytes: 3.14,
  status: null,
};

export async function defaultCreateBackupHandler(..._args: Args): Promise<unknown> {
  return createBackupSample;
}

export async function emptyCreateBackupHandler(..._args: Args): Promise<unknown> {
  return {};
}

export async function DestinationpathInvalidSpecInvalidCreateBackupHandler(
  ..._args: Args
): Promise<never> {
  throw { code: -32010, message: 'destinationPath invalid spec (INVALID_DEST_PATH)' };
}

export async function DestinationFolderNotWritableCreateBackupHandler(
  ..._args: Args
): Promise<never> {
  throw { code: -32011, message: 'Destination folder not writable (DEST_FOLDER_NOT_WRITABLE)' };
}

export async function ProjectidNotFoundNotCreateBackupHandler(..._args: Args): Promise<never> {
  throw { code: -32001, message: 'projectId not found / not editable (INVALID_PROJECT)' };
}

export async function ProjectIsResourceIsprotectedtextCreateBackupHandler(
  ..._args: Args
): Promise<never> {
  throw {
    code: -32012,
    message: 'Project is resource (isProtectedText) (RESOURCE_NOT_BACKUPABLE)',
  };
}

export async function UsernameEmptyUserNameCreateBackupHandler(..._args: Args): Promise<never> {
  throw { code: -32013, message: 'userName empty (USER_NAME_REQUIRED)' };
}

export async function NoBooksSelectedNotCreateBackupHandler(..._args: Args): Promise<never> {
  throw { code: -32014, message: 'No books selected & not Notes-type (NO_BOOKS_SELECTED)' };
}

export async function ScrtextPersistchangesReturnsFalseCreateBackupHandler(
  ..._args: Args
): Promise<never> {
  throw {
    code: -32015,
    message: 'scrText.PersistChanges() returns false (PERSIST_CHANGES_FAILED)',
  };
}

export async function FileSystemIoErrorCreateBackupHandler(..._args: Args): Promise<never> {
  throw { code: -32016, message: 'File-system IO error (IO_ERROR)' };
}
