/*
 * auto-generated by derive-storybook-mock.ts; do not edit by hand.
 *
 * Command: enumerateUsbDevices
 * Callback kind: awaited
 *
 * Stories should import these handlers and pass them as Storybook args.
 * UX may tune *story args* (which handler to wire up) but should never edit
 * this file directly — it is regenerated every time the script runs.
 */

type Args = unknown[];

const enumerateUsbDevicesSample = [
  {
    isRemovable: true,
    label: 'Sample label',
    rootPath: '/sample/path',
    totalSizeBytes: 3.14,
  },
  {
    isRemovable: true,
    label: 'Sample label',
    rootPath: '/sample/path',
    totalSizeBytes: 3.14,
  },
  {
    isRemovable: true,
    label: 'Sample label',
    rootPath: '/sample/path',
    totalSizeBytes: 3.14,
  },
];

export async function defaultEnumerateUsbDevicesHandler(..._args: Args): Promise<unknown> {
  return enumerateUsbDevicesSample;
}

export async function emptyEnumerateUsbDevicesHandler(..._args: Args): Promise<unknown> {
  return [];
}

export async function OsStorageApiErrorEnumerateUsbDevicesHandler(..._args: Args): Promise<never> {
  throw { code: -32016, message: 'OS storage API error — very rare (IO_ERROR)' };
}
