/*
 * auto-generated by derive-storybook-mock.ts; do not edit by hand.
 *
 * Command: getCompareSourceContent
 * Callback kind: awaited
 *
 * Stories should import these handlers and pass them as Storybook args.
 * UX may tune *story args* (which handler to wire up) but should never edit
 * this file directly — it is regenerated every time the script runs.
 */

type Args = unknown[];

const getCompareSourceContentSample = {
  status: null,
  text: 'Lorem ipsum dolor sit amet',
};

export async function defaultGetCompareSourceContentHandler(..._args: Args): Promise<unknown> {
  return getCompareSourceContentSample;
}

export async function emptyGetCompareSourceContentHandler(..._args: Args): Promise<unknown> {
  return {};
}

export async function SessionidNotRecognizedInvalidGetCompareSourceContentHandler(
  ..._args: Args
): Promise<never> {
  throw { code: -32020, message: 'sessionId not recognized (INVALID_SESSION)' };
}

export async function SourcetokenNotRecognizedForGetCompareSourceContentHandler(
  ..._args: Args
): Promise<never> {
  throw { code: -32028, message: 'sourceToken not recognized for this session (INVALID_TOKEN)' };
}

export async function VerserefMalformedUnknownBookGetCompareSourceContentHandler(
  ..._args: Args
): Promise<never> {
  throw {
    code: -32029,
    message: 'verseRef malformed — unknown book id or negative chapter/verse (INVALID_VERSE_REF)',
  };
}

export async function UnderlyingIOErrorGetCompareSourceContentHandler(
  ..._args: Args
): Promise<never> {
  throw { code: -32016, message: 'Underlying I/O error reading from the backup source (IO_ERROR)' };
}
