/*
 * auto-generated by derive-storybook-mock.ts; do not edit by hand.
 *
 * Command: isDestinationPathWritable
 * Callback kind: data-retrieval
 *
 * Stories should import these handlers and pass them as Storybook args.
 * UX may tune *story args* (which handler to wire up) but should never edit
 * this file directly — it is regenerated every time the script runs.
 */

type Args = unknown[];

const isDestinationPathWritableSample = {
  reason: 'INVALID_PATH',
  writable: true,
};

export async function defaultIsDestinationPathWritableHandler(..._args: Args): Promise<unknown> {
  return isDestinationPathWritableSample;
}

export async function emptyIsDestinationPathWritableHandler(..._args: Args): Promise<unknown> {
  return {};
}
