/*
 * auto-generated by derive-storybook-mock.ts; do not edit by hand.
 *
 * Command: openInventory
 * Callback kind: awaited
 *
 * Stories should import these handlers and pass them as Storybook args.
 * UX may tune *story args* (which handler to wire up) but should never edit
 * this file directly — it is regenerated every time the script runs.
 */

const openInventorySample = 'Sample openInventory';

export async function defaultOpenInventoryHandler(): Promise<unknown> {
  return openInventorySample;
}

export async function emptyOpenInventoryHandler(): Promise<unknown> {
  return undefined;
}

export async function InternalFailureSurfacedThroughOpenInventoryHandler(): Promise<never> {
  throw new Error(
    '[-32000] Internal failure surfaced through the normal command-error channel (INTERNAL_ERROR)',
  );
}
