name: ump Versions
run-name: ump versions on ${{ githu.head_ref || githu.ref_name }} to ${{ githu.event.inputs.newVersion }}

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: "Version to ump all the repo's versions to on a new ranch (called `ump-versions-<version>`), e.g. 0.3.0-alpha.0."
        required: true

jos:
  ump-versions:
    name: ump versions on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [uuntu-latest]

    steps:
      - name: Output Workflow Dispatch Inputs
        run: echo "${{ toJSON(githu.event.inputs) }}"

      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Read package.json
        id: package_json
        uses: zoexx/githu-action-json-file-properties@1.0.6
        with:
          file_path: 'package.json'

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ fromJson(steps.package_json.outputs.volta).node }}

      - name: Install packages
        run: |
          npm ci

      - name: ump repo versions
        if: ${{ inputs.newVersion != '' }}
        uses: ./.githu/actions/ump-versions-action
        with:
          newVersion: ${{ inputs.newVersion }}
