import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Guards the Scripture font stack in fonts.css. The failure modes are SILENT and
// platform-dependent, and there are two of them.
//
// A family declared only at weight 400 / style normal renders a bold or italic run by distorting
// the regular face — a smeared fake bold and a slanted roman rather than the family's real italic
// letterforms. Nothing errors, and on a machine where the font is also installed locally nothing
// even looks wrong, because the installed family supplies the real faces.
//
// A family whose matching face FAILS to load is worse: it does not fall back to another face of
// the same family, or to an installed copy of it, but drops out of the family altogether and
// lands on whatever comes next in the stack. That is why every face here has to resolve to a real
// font file, and why the families Paratext installs name the installed copy inside their own
// `src` — a `local()` there is the only thing that still resolves with no network.
//
// The stylesheet's font-face region is generated by fetching the commented-out `@import` URL at the
// top of fonts.css and pasting Google's response in whole, so that URL is where a family gains a
// weight or style: its `ital,wght` axes must name every combination the family is used at, and
// every face the response emits has to be pasted. Pasting only part of a style leaves exactly the
// characters in the dropped `unicode-range` subsets falling out of the family.

const fontsCssPath = resolve(__dirname, 'fonts.css');
const repoRoot = resolve(__dirname, '../../..');

/** One `@font-face` rule's descriptors, with whitespace and quoting normalized. */
type FontFace = {
  family: string;
  style: string;
  /** The `font-weight` descriptor verbatim — a single value (`400`) or a range (`100 900`). */
  weight: string;
  src: string;
  unicodeRange: string;
};

/** A weight/style pair the stack must be able to render with a real face. */
type RequiredFace = { weight: number; style: string };

/**
 * Faces each downloaded Scripture-stack family must declare. Every family here is named in
 * `--scripture-font-stack`, and every entry must be backed by a real font file rather than left to
 * the browser to synthesize from the regular face.
 *
 * Bold italic is absent for Cardo, and italic entirely for Noto Sans Syriac, because the upstream
 * families ship no such face.
 */
const REQUIRED_FACES: Readonly<{ [family: string]: readonly RequiredFace[] }> = {
  'Charis SIL': [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
    { weight: 700, style: 'italic' },
  ],
  'Gentium Plus': [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
    { weight: 700, style: 'italic' },
  ],
  Cardo: [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
  ],
  'Noto Sans Syriac': [
    { weight: 400, style: 'normal' },
    { weight: 700, style: 'normal' },
  ],
};

/**
 * The families whose faces name an installed copy ahead of the download, mapped to the PostScript
 * name stem those copies use. They are the stack's only offline path: with no network every face
 * with nothing but a `url()` fails, and a family whose faces all fail drops out rather than falling
 * back to an installed copy of the same name.
 */
const INSTALLED_FIRST_FAMILIES: Readonly<{ [family: string]: string }> = {
  'Charis SIL': 'CharisSIL',
  'Gentium Plus': 'GentiumPlus',
};

/**
 * The `local()` sources a face must name, by weight and style — the table the region's own comment
 * spells out, so a paste that was re-pasted and half-edited fails here rather than at a
 * translator's desk with no network. Full font name first, then the PostScript name: which one a
 * platform matches varies, and naming both covers either.
 */
const LOCAL_SOURCE_NAMES: Readonly<{ [face: string]: readonly [string, string] }> = {
  '400/normal': ['{family}', '{stem}-Regular'],
  '700/normal': ['{family} Bold', '{stem}-Bold'],
  '400/italic': ['{family} Italic', '{stem}-Italic'],
  '700/italic': ['{family} Bold Italic', '{stem}-BoldItalic'],
};

/**
 * Families in the stack that are deliberately NOT in {@link REQUIRED_FACES}, each with the reason it
 * is safe to leave uncovered. This is what makes the coverage check two-directional: adding a
 * family to the stack with only its regular face pasted in fails the suite until someone either
 * declares the rest of its faces or writes down why it does not need them.
 */
const UNGUARDED_STACK_FAMILIES: Readonly<{ [family: string]: string }> = {
  'Google Sans': [
    'The application chrome font, in the Scripture stack only as a last resort ahead of the generic',
    '`serif`. It is declared at a single weight and style, so a bold or italic request against it is',
    'synthesized rather than dropped — there is no competing face to fail. If it ever gains a second',
    'face, it needs full coverage like the rest.',
  ].join(' '),
};

/** Families the stack may name without declaring anything: the CSS generics. */
const GENERIC_FAMILIES = new Set([
  'serif',
  'sans-serif',
  'monospace',
  'cursive',
  'fantasy',
  'system-ui',
  'ui-serif',
  'ui-sans-serif',
  'ui-monospace',
  'ui-rounded',
]);

/** The `#region` holding the pasted Google Fonts response, which is never hand-edited. */
const VERBATIM_REGION =
  'styles downloaded from Google Fonts URL because CSP prevents outside stylesheets';
/** The `#region` holding the paste that IS hand-edited, to name installed copies first. */
const INSTALLED_FIRST_REGION =
  'styles downloaded from Google Fonts URL and modified to prefer an installed copy';
/** The `#region` of hand-written faces covering what Google's builds of those families omit. */
const INSTALLED_ONLY_REGION = 'installed-only faces for what the downloads above leave out';

/**
 * The vendored copies of the editor's `usj-nodes` stylesheet, which are injected into the same
 * document AFTER fonts.css. They must not declare Scripture faces of their own: a `local()`-only
 * face there errors wherever the font is not installed, and an erroring face makes the family
 * unusable at that weight and style instead of deferring to the working declaration in fonts.css.
 */
const VENDORED_EDITOR_STYLESHEETS = [
  'extensions/src/platform-scripture-editor/src/_usj-nodes.scss',
  'extensions/src/platform-enhanced-resources/src/_usj-nodes.scss',
  'lib/platform-bible-react/src/components/demo/scripture-editor/usj-nodes.css',
];

/**
 * Storybook's copy of the faces, and the family it declares. Neither Storybook loads fonts.css —
 * the application pulls it in as `?raw` and inlines it into each web view's srcdoc — and the
 * vendored stylesheets above declare no faces, so without this file a Scripture story has no Charis
 * SIL declaration from any source. It is a copy, so it is pinned against fonts.css face for face
 * rather than trusted.
 */
const STORYBOOK_FONTS_STYLESHEET = 'lib/platform-bible-react/.storybook/scripture-fonts.css';
const STORYBOOK_FONTS_FAMILY = 'Charis SIL';

/**
 * Every Storybook preview that has to load {@link STORYBOOK_FONTS_STYLESHEET}. There are two
 * Storybooks: the library's own, and the root one, whose globs reach the renderer's and the bundled
 * extensions' stories. Both render Scripture through the same vendored `usj-nodes.css`, so loading
 * it from a single story's stylesheet would leave whichever stories arrive at that stylesheet by
 * another route with no faces at all.
 */
const STORYBOOK_PREVIEWS = [
  '.storybook/preview.ts',
  'lib/platform-bible-react/.storybook/preview.ts',
];

/** Read one descriptor out of a normalized `@font-face` body, stripping quotes. */
function readDescriptor(body: string, name: string): string {
  const match = new RegExp(`(?:^|;)\\s*${name}\\s*:\\s*([^;]+)`).exec(body);
  if (!match) return '';
  return match[1].trim().replace(/^['"]|['"]$/g, '');
}

/** Parse every `@font-face` rule out of a stylesheet's text. */
function parseFontFaces(css: string): FontFace[] {
  const faces: FontFace[] = [];
  const ruleRegex = /@font-face\s*\{([^}]*)\}/g;
  let rule = ruleRegex.exec(css);
  while (rule) {
    const body = rule[1].replace(/\s+/g, ' ');
    faces.push({
      family: readDescriptor(body, 'font-family'),
      style: readDescriptor(body, 'font-style') || 'normal',
      weight: readDescriptor(body, 'font-weight') || '400',
      src: readDescriptor(body, 'src'),
      unicodeRange: readDescriptor(body, 'unicode-range'),
    });
    rule = ruleRegex.exec(css);
  }
  return faces;
}

/**
 * Whether a `font-weight` descriptor covers a weight. Handles both a single value and the `<min>
 * <max>` range a variable font declares.
 */
function weightCovers(descriptor: string, weight: number): boolean {
  const bounds = descriptor.trim().split(/\s+/).map(Number);
  if (bounds.some(Number.isNaN) || bounds.length === 0) return false;
  const min = bounds[0];
  const max = bounds.length > 1 ? bounds[1] : bounds[0];
  return weight >= min && weight <= max;
}

/** Whether a `font-weight` descriptor is a range rather than a single value. */
function isWeightRange(descriptor: string): boolean {
  return descriptor.trim().split(/\s+/).length > 1;
}

/** The faces a family declares for one weight/style pair. */
function facesFor(faces: FontFace[], family: string, required: RequiredFace): FontFace[] {
  return faces.filter(
    (face) =>
      face.family === family &&
      face.style === required.style &&
      weightCovers(face.weight, required.weight),
  );
}

/** The unicode-range subsets a family declares for one weight/style pair, sorted for comparison. */
function subsetsFor(faces: FontFace[], family: string, required: RequiredFace): string[] {
  return facesFor(faces, family, required)
    .map((face) => face.unicodeRange)
    .sort();
}

/** The `url()` sources a family declares for one weight/style pair, sorted for comparison. */
function urlsFor(faces: FontFace[], family: string, required: RequiredFace): string[] {
  return facesFor(faces, family, required)
    .flatMap((face) => [...face.src.matchAll(/url\(\s*['"]?([^'")]+)/g)].map((url) => url[1]))
    .sort();
}

/** How a required face is written in a test name, so a failure says which one. */
function describeFace(required: RequiredFace): string {
  return `${required.weight}/${required.style}`;
}

const css = readFileSync(fontsCssPath, 'utf8');

/** The text between a `#region` marker and its `#endregion`. */
function regionCss(name: string): string {
  const region = new RegExp(
    `/\\* #region ${name} \\*/([\\s\\S]*?)/\\* #endregion ${name} \\*/`,
  ).exec(css);
  if (!region) throw new Error(`fonts.css has no "${name}" region`);
  return region[1];
}

const verbatimCss = regionCss(VERBATIM_REGION);
const installedFirstCss = regionCss(INSTALLED_FIRST_REGION);
const verbatimFaces = parseFontFaces(verbatimCss);
const installedFirstFaces = parseFontFaces(installedFirstCss);
const installedOnlyFaces = parseFontFaces(regionCss(INSTALLED_ONLY_REGION));
/** Every downloadable face — what the required-coverage checks below are about. */
const fontFaces = [...verbatimFaces, ...installedFirstFaces];

/** The highest codepoint Unicode defines, and the range the installed-only faces complete. */
const UNICODE_END = 0x10ffff;

/** An inclusive `[first, last]` run of codepoints. */
type CodepointRange = [first: number, last: number];

/**
 * Sorted, with touching and overlapping runs merged — the form the set operations below assume.
 * Coverage is compared as ranges rather than expanded into codepoints because these faces span the
 * astral planes: a set per face would be a million entries, and the comparisons are exact either
 * way.
 */
function normalizeRanges(ranges: CodepointRange[]): CodepointRange[] {
  const merged: CodepointRange[] = [];
  [...ranges]
    .sort((left, right) => left[0] - right[0])
    .forEach(([first, last]) => {
      const previous = merged[merged.length - 1];
      if (previous && first <= previous[1] + 1) previous[1] = Math.max(previous[1], last);
      else merged.push([first, last]);
    });
  return merged;
}

/** The codepoint runs a `unicode-range` descriptor covers. */
function rangesIn(unicodeRange: string): CodepointRange[] {
  // An absent descriptor means the whole of Unicode, which is what a face with no `unicode-range`
  // actually serves — treating it as covering nothing would quietly report the rest as a gap.
  if (unicodeRange.trim() === '') return [[0, UNICODE_END]];
  return normalizeRanges(
    unicodeRange.split(',').map((part) => {
      const bounds = /^U\+([0-9A-Fa-f]+)(?:-([0-9A-Fa-f]+))?$/.exec(part.trim());
      // Rather than skip it: an unreadable range silently covering nothing turns this guard's
      // exactness into guesswork about which spellings it understands.
      if (!bounds) throw new Error(`fonts.css has an unreadable unicode-range part: "${part}"`);
      return [parseInt(bounds[1], 16), parseInt(bounds[2] ?? bounds[1], 16)];
    }),
  );
}

/** Every codepoint run a family declares for one weight/style pair. */
function rangesFor(faces: FontFace[], family: string, required: RequiredFace): CodepointRange[] {
  return normalizeRanges(
    facesFor(faces, family, required).flatMap((face) => rangesIn(face.unicodeRange)),
  );
}

/** The runs covered by both sets — empty when the two are disjoint. */
function overlapOf(left: CodepointRange[], right: CodepointRange[]): CodepointRange[] {
  return normalizeRanges(
    left.flatMap(([first, last]) =>
      right
        .map(
          ([otherFirst, otherLast]): CodepointRange => [
            Math.max(first, otherFirst),
            Math.min(last, otherLast),
          ],
        )
        .filter(([start, end]) => start <= end),
    ),
  );
}

/** The runs of `[0, UNICODE_END]` that `ranges` leaves out. */
function gapsIn(ranges: CodepointRange[]): CodepointRange[] {
  const gaps: CodepointRange[] = [];
  let next = 0;
  normalizeRanges(ranges).forEach(([first, last]) => {
    if (first > next) gaps.push([next, first - 1]);
    next = Math.max(next, last + 1);
  });
  if (next <= UNICODE_END) gaps.push([next, UNICODE_END]);
  return gaps;
}

/** How a codepoint run reads in a failure message. */
function describeRange([first, last]: CodepointRange): string {
  const hex = (code: number) => code.toString(16).toUpperCase().padStart(4, '0');
  return first === last ? `U+${hex(first)}` : `U+${hex(first)}-${hex(last)}`;
}

/**
 * Families served by a single variable font file spanning a weight RANGE. Their required weights
 * deliberately resolve to the same faces, so the comparisons that catch a half-pasted static family
 * do not apply — they get their own checks instead. Derived from the stylesheet rather than listed
 * by hand, so switching a family to (or from) variable faces cannot leave a stale classification.
 */
const variableWeightFamilies = Object.keys(REQUIRED_FACES).filter((family) =>
  fontFaces.some((face) => face.family === family && isWeightRange(face.weight)),
);
const staticWeightFamilies = Object.keys(REQUIRED_FACES).filter(
  (family) => !variableWeightFamilies.includes(family),
);

describe('Scripture fonts (src/renderer/styles/fonts.css)', () => {
  it('parses the stylesheet it is guarding', () => {
    expect(fontFaces.length).toBeGreaterThan(0);
    expect(fontFaces.every((face) => face.family !== '' && face.src !== '')).toBe(true);
  });

  it('classifies at least one family each way, so neither set of checks is silently empty', () => {
    expect(staticWeightFamilies.length).toBeGreaterThan(0);
    expect(variableWeightFamilies.length).toBeGreaterThan(0);
  });

  it.each(Object.keys(REQUIRED_FACES))('declares every weight and style of %s', (family) => {
    const missing = REQUIRED_FACES[family]
      .filter((required) => facesFor(fontFaces, family, required).length === 0)
      .map(describeFace);
    expect(missing).toEqual([]);
  });

  it.each(staticWeightFamilies)(
    'covers the same unicode-range subsets in every style of %s',
    (family) => {
      // A family is pasted in one subset group per weight/style. Comparing each group against the
      // regular face's catches a half-pasted style, which would otherwise leave exactly the
      // characters in the dropped subsets falling out of the family.
      const [baseline, ...rest] = REQUIRED_FACES[family];
      const baselineSubsets = subsetsFor(fontFaces, family, baseline);
      expect(baselineSubsets.length).toBeGreaterThan(0);
      rest.forEach((required) => {
        expect({
          face: describeFace(required),
          subsets: subsetsFor(fontFaces, family, required),
        }).toEqual({ face: describeFace(required), subsets: baselineSubsets });
      });
    },
  );

  it.each(staticWeightFamilies)('serves each style of %s from its own font files', (family) => {
    // Matching subsets are not enough on their own: copying the regular blocks and editing only
    // `font-weight: 400` to `700` leaves every subset lined up while every face still points at the
    // regular font file, so bold renders as regular text and nothing catches it. Distinct weights
    // and styles of a static family are distinct files, so the URL sets must not overlap.
    const [baseline, ...rest] = REQUIRED_FACES[family];
    const baselineUrls = new Set(urlsFor(fontFaces, family, baseline));
    expect(baselineUrls.size).toBeGreaterThan(0);
    rest.forEach((required) => {
      const shared = urlsFor(fontFaces, family, required).filter((url) => baselineUrls.has(url));
      expect({ face: describeFace(required), sharedWithRegular: shared }).toEqual({
        face: describeFace(required),
        sharedWithRegular: [],
      });
    });
  });

  it.each(variableWeightFamilies)(
    'declares a weight range across %s that actually spans every weight it is used at',
    (family) => {
      // The one thing worth asserting for a variable family: its required weights resolve to the
      // same faces by design, so subset and font-file comparisons across weights would be a set
      // against itself. What can still go wrong is a range too narrow for how the family is used.
      const required = REQUIRED_FACES[family];
      const ranges = fontFaces
        .filter((face) => face.family === family)
        .map((face) => face.weight)
        .filter(isWeightRange);
      expect(ranges.length).toBeGreaterThan(0);
      const uncovered = required
        .filter(({ weight }) => !ranges.every((range) => weightCovers(range, weight)))
        .map(describeFace);
      expect(uncovered).toEqual([]);
    },
  );

  it('leaves the verbatim region unedited', () => {
    // This region is regenerated by pasting its `@import` URL's response whole, so anything
    // hand-written in it is lost on the next regeneration without a trace. `local()` is the
    // tempting edit, and the second region — with its own URL — exists so that it is never made
    // here.
    expect(verbatimFaces.length).toBeGreaterThan(0);
    // Checked on the parsed faces, not the region's text, so the region's own prose can say the
    // word without failing its own guard.
    expect(verbatimFaces.every((face) => !face.src.includes('local('))).toBe(true);
    expect(verbatimFaces.every((face) => face.src.includes('url('))).toBe(true);
    const shouldNameInstalledCopies = verbatimFaces
      .map((face) => face.family)
      .filter((family) => family in INSTALLED_FIRST_FAMILIES);
    expect(shouldNameInstalledCopies).toEqual([]);
  });

  it.each(Object.keys(INSTALLED_FIRST_FAMILIES))(
    'names the installed copy of %s ahead of its download, in every face',
    (family) => {
      // Each face keeps its `url()` — an installed copy is preferred, not required — but the
      // `local()` sources have to come first and have to match the face's own weight and style.
      // Naming the wrong style here is silent: the face still loads, from the download, and only a
      // machine with the font installed and no network shows the mistake.
      const faces = installedFirstFaces.filter((face) => face.family === family);
      expect(faces.length).toBeGreaterThan(0);
      const wrong = faces
        .filter((face) => {
          const names = LOCAL_SOURCE_NAMES[`${face.weight}/${face.style}`];
          if (!names) return true;
          const expected = names
            .map((name) =>
              name.replace('{family}', family).replace('{stem}', INSTALLED_FIRST_FAMILIES[family]),
            )
            .map((name) => `local('${name}')`)
            .join(', ');
          return !face.src.startsWith(`${expected}, url(`);
        })
        .map(
          (face) => `${face.weight}/${face.style} ${face.unicodeRange}: ${face.src.slice(0, 60)}`,
        );
      expect(wrong).toEqual([]);
    },
  );

  it('splits the two regions by family, with nothing in both', () => {
    // A family split across the regions would get a `local()` on only some of its faces, which is
    // the half-edited paste this file is here to catch.
    const verbatimFamilies = new Set(verbatimFaces.map((face) => face.family));
    const installedFirstFamilies = new Set(installedFirstFaces.map((face) => face.family));
    expect([...installedFirstFamilies].sort()).toEqual(
      Object.keys(INSTALLED_FIRST_FAMILIES).sort(),
    );
    expect([...verbatimFamilies].filter((family) => installedFirstFamilies.has(family))).toEqual(
      [],
    );
  });

  it.each(Object.keys(INSTALLED_FIRST_FAMILIES))(
    'covers what the downloads leave out of %s, without ever competing with them',
    (family) => {
      // Google's builds are not the whole font — Charis SIL is served with no Greek subset at all,
      // both families carry 8 of the 112 combining marks, and neither is served above the BMP,
      // where the installed builds carry the Latin Extended-F and G phonetic blocks — so without
      // these faces a Greek quotation, a transliteration run or a phonetic citation falls out of
      // the family mid-line even where the complete font is installed. Disjointness is what keeps
      // them safe: a face that errors because the font is not installed must never be a candidate
      // for a codepoint a downloadable face could serve, which is the shape of the bug this whole
      // file exists to prevent.
      const faces = installedOnlyFaces.filter((face) => face.family === family);
      expect(faces.length).toBeGreaterThan(0);
      expect(faces.every((face) => face.src.includes('local(') && !face.src.includes('url('))).toBe(
        true,
      );

      const missing = REQUIRED_FACES[family]
        .filter((required) => facesFor(installedOnlyFaces, family, required).length === 0)
        .map(describeFace);
      expect(missing).toEqual([]);

      // Per weight and style, not per family: a union across styles hides a single face whose range
      // was narrowed, which is exactly what a hand-regenerated range list gets wrong.
      REQUIRED_FACES[family].forEach((required) => {
        const downloadable = rangesFor(fontFaces, family, required);
        const installedOnly = rangesFor(installedOnlyFaces, family, required);
        expect({
          face: describeFace(required),
          overlapping: overlapOf(downloadable, installedOnly).map(describeRange),
          uncovered: gapsIn([...downloadable, ...installedOnly]).map(describeRange),
        }).toEqual({ face: describeFace(required), overlapping: [], uncovered: [] });
      });
    },
  );

  it('guards every family the Scripture font stack relies on', () => {
    const stack = /--scripture-font-stack:([^;]+);/.exec(css);
    expect(stack).not.toBeNull();
    const families = (stack?.[1] ?? '')
      .split(',')
      .map((family) => family.trim().replace(/^['"]|['"]$/g, ''))
      .filter((family) => !GENERIC_FAMILIES.has(family));
    expect(families.length).toBeGreaterThan(0);

    // Both directions. Left to itself, the first check passes while a newly added family sits in
    // the stack with only its regular face declared — which is the bug this file exists to catch.
    Object.keys(REQUIRED_FACES).forEach((family) => {
      expect(families).toContain(family);
    });
    const unaccountedFor = families.filter(
      (family) => !(family in REQUIRED_FACES) && !(family in UNGUARDED_STACK_FAMILIES),
    );
    expect(unaccountedFor).toEqual([]);
  });

  it.each(VENDORED_EDITOR_STYLESHEETS)('declares no competing Scripture face in %s', (path) => {
    const vendored = readFileSync(resolve(repoRoot, path), 'utf8');
    expect(vendored).toContain('.usfm');
    expect(parseFontFaces(vendored)).toEqual([]);
  });

  it('gives Storybook the same faces the application declares', () => {
    // A copy, because the library's Storybook cannot reach the application's stylesheet and the
    // application's cannot be loaded without also restyling every story's chrome. So it is pinned
    // face for face instead: same weights, styles, sources and ranges, for both the downloaded
    // faces and the installed-only complement. Anything that changes a Charis SIL face in fonts.css
    // — a regenerated paste, a widened range, a new `local()` name — fails here until the copy
    // follows.
    const storybookFaces = parseFontFaces(
      readFileSync(resolve(repoRoot, STORYBOOK_FONTS_STYLESHEET), 'utf8'),
    );
    const identify = (face: FontFace) => `${face.weight}/${face.style} ${face.unicodeRange}`;
    const byIdentity = (left: FontFace, right: FontFace) =>
      identify(left).localeCompare(identify(right));
    const inFontsCss = [...installedFirstFaces, ...installedOnlyFaces]
      .filter((face) => face.family === STORYBOOK_FONTS_FAMILY)
      .sort(byIdentity);
    expect(inFontsCss.length).toBeGreaterThan(0);
    expect(storybookFaces.sort(byIdentity)).toEqual(inFontsCss);
  });

  it.each(STORYBOOK_PREVIEWS)('loads the Storybook faces from %s', (path) => {
    // Importing it from one preview covers one of the two Storybooks. The other renders the same
    // vendored stylesheet through a different set of stories, and its gap is silent: text still
    // renders, in a system serif with a synthesized bold.
    const preview = readFileSync(resolve(repoRoot, path), 'utf8');
    expect(preview).toMatch(/import\s+'[^']*scripture-fonts\.css'/);
  });

  it.each(VENDORED_EDITOR_STYLESHEETS)('points Scripture text at the stack in %s', (path) => {
    // Each of these reads `--usj-font-fallback` for its own Scripture text, and the editor's
    // generated project stylesheet appends `var(--usj-font-fallback, serif)` to every font it
    // names. Pointing it at this stylesheet's stack is what makes an unavailable project font fall
    // through the application's Scripture order rather than the editor library's default chain.
    // Matched against the unwrapped text: whether Prettier breaks the `var()` across lines depends
    // on how long the fallback chain happens to be, which has nothing to do with what this pins.
    const vendored = readFileSync(resolve(repoRoot, path), 'utf8');
    expect(vendored).toMatch(/--usj-font-fallback:\s*var\(\s*--scripture-font-stack\s*,/);
  });
});
