import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Guards the Scripture font stack in fonts.css. The failure modes are SILENT and
// platform-dependent, and there are two of them.
//
// A family declared only at weight 400 / style normal renders a bold or italic run by distorting
// the regular face — a smeared fake bold and a slanted roman rather than the family's real italic
// letterforms. Nothing errors, and on a machine where the font is also installed locally nothing
// even looks wrong, because the installed family supplies the real faces.
//
// A family whose matching face FAILS to load is worse: it does not fall back to another face of
// the same family, or to an installed copy of it, but drops out of the family altogether and
// lands on whatever comes next in the stack. That is what the `*-Local` families are for — they
// are the only thing behind the downloaded families when there is no network — and it is why
// every face here has to resolve to a real font file.
//
// The stylesheet's font-face region is generated by fetching the commented-out `@import` URL at the
// top of fonts.css and pasting Google's response in whole, so that URL is where a family gains a
// weight or style: its `ital,wght` axes must name every combination the family is used at, and
// every face the response emits has to be pasted. Pasting only part of a style leaves exactly the
// characters in the dropped `unicode-range` subsets falling out of the family.

const fontsCssPath = resolve(__dirname, 'fonts.css');
const repoRoot = resolve(__dirname, '../../..');

/** One `@font-face` rule's descriptors, with whitespace and quoting normalized. */
type FontFace = {
  family: string;
  style: string;
  /** The `font-weight` descriptor verbatim — a single value (`400`) or a range (`100 900`). */
  weight: string;
  src: string;
  unicodeRange: string;
};

/** A weight/style pair the stack must be able to render with a real face. */
type RequiredFace = { weight: number; style: string };

/**
 * Faces each downloaded Scripture-stack family must declare. Every family here is named in
 * `--scripture-font-stack`, and every entry must be backed by a real font file rather than left to
 * the browser to synthesize from the regular face.
 *
 * Bold italic is absent for Cardo, and italic entirely for Noto Sans Syriac, because the upstream
 * families ship no such face.
 */
const REQUIRED_FACES: Readonly<{ [family: string]: readonly RequiredFace[] }> = {
  'Charis SIL': [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
    { weight: 700, style: 'italic' },
  ],
  'Gentium Plus': [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
    { weight: 700, style: 'italic' },
  ],
  Cardo: [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
  ],
  'Noto Sans Syriac': [
    { weight: 400, style: 'normal' },
    { weight: 700, style: 'normal' },
  ],
};

/**
 * The families that name an installed copy of a downloaded family, mapped to the family each one
 * stands in for. They are the stack's only offline path: with no network every downloaded family is
 * unusable, including on a machine where Paratext has installed the font.
 */
const INSTALLED_COPY_ALIASES: Readonly<{ [alias: string]: string }> = {
  'Charis SIL Local': 'Charis SIL',
  'Gentium Plus Local': 'Gentium Plus',
};

/**
 * Families in the stack that are deliberately NOT in {@link REQUIRED_FACES}, each with the reason it
 * is safe to leave uncovered. This is what makes the coverage check two-directional: adding a
 * family to the stack with only its regular face pasted in fails the suite until someone either
 * declares the rest of its faces or writes down why it does not need them.
 */
const UNGUARDED_STACK_FAMILIES: Readonly<{ [family: string]: string }> = {
  'Google Sans': [
    'The application chrome font, in the Scripture stack only as a last resort ahead of the generic',
    '`serif`. It is declared at a single weight and style, so a bold or italic request against it is',
    'synthesized rather than dropped — there is no competing face to fail. If it ever gains a second',
    'face, it needs full coverage like the rest.',
  ].join(' '),
};

/** Families the stack may name without declaring anything: the CSS generics. */
const GENERIC_FAMILIES = new Set([
  'serif',
  'sans-serif',
  'monospace',
  'cursive',
  'fantasy',
  'system-ui',
  'ui-serif',
  'ui-sans-serif',
  'ui-monospace',
  'ui-rounded',
]);

/** The `#region` holding the pasted Google Fonts response, which is never hand-edited. */
const DOWNLOADED_REGION =
  'styles downloaded from Google Fonts URL because CSP prevents outside stylesheets';
/** The `#region` holding the hand-written faces that name installed copies of those fonts. */
const INSTALLED_COPY_REGION =
  'installed copies of the Scripture fonts, for when the downloads above cannot be fetched';

/**
 * The vendored copies of the editor's `usj-nodes` stylesheet, which are injected into the same
 * document AFTER fonts.css. They must not declare Scripture faces of their own: a `local()`-only
 * face there errors wherever the font is not installed, and an erroring face makes the family
 * unusable at that weight and style instead of deferring to the working declaration in fonts.css.
 */
const VENDORED_EDITOR_STYLESHEETS = [
  'extensions/src/platform-scripture-editor/src/_usj-nodes.scss',
  'extensions/src/platform-enhanced-resources/src/_usj-nodes.scss',
  'lib/platform-bible-react/src/components/demo/scripture-editor/usj-nodes.css',
];

/** Read one descriptor out of a normalized `@font-face` body, stripping quotes. */
function readDescriptor(body: string, name: string): string {
  const match = new RegExp(`(?:^|;)\\s*${name}\\s*:\\s*([^;]+)`).exec(body);
  if (!match) return '';
  return match[1].trim().replace(/^['"]|['"]$/g, '');
}

/** Parse every `@font-face` rule out of a stylesheet's text. */
function parseFontFaces(css: string): FontFace[] {
  const faces: FontFace[] = [];
  const ruleRegex = /@font-face\s*\{([^}]*)\}/g;
  let rule = ruleRegex.exec(css);
  while (rule) {
    const body = rule[1].replace(/\s+/g, ' ');
    faces.push({
      family: readDescriptor(body, 'font-family'),
      style: readDescriptor(body, 'font-style') || 'normal',
      weight: readDescriptor(body, 'font-weight') || '400',
      src: readDescriptor(body, 'src'),
      unicodeRange: readDescriptor(body, 'unicode-range'),
    });
    rule = ruleRegex.exec(css);
  }
  return faces;
}

/**
 * Whether a `font-weight` descriptor covers a weight. Handles both a single value and the `<min>
 * <max>` range a variable font declares.
 */
function weightCovers(descriptor: string, weight: number): boolean {
  const bounds = descriptor.trim().split(/\s+/).map(Number);
  if (bounds.some(Number.isNaN) || bounds.length === 0) return false;
  const min = bounds[0];
  const max = bounds.length > 1 ? bounds[1] : bounds[0];
  return weight >= min && weight <= max;
}

/** Whether a `font-weight` descriptor is a range rather than a single value. */
function isWeightRange(descriptor: string): boolean {
  return descriptor.trim().split(/\s+/).length > 1;
}

/** The faces a family declares for one weight/style pair. */
function facesFor(faces: FontFace[], family: string, required: RequiredFace): FontFace[] {
  return faces.filter(
    (face) =>
      face.family === family &&
      face.style === required.style &&
      weightCovers(face.weight, required.weight),
  );
}

/** The unicode-range subsets a family declares for one weight/style pair, sorted for comparison. */
function subsetsFor(faces: FontFace[], family: string, required: RequiredFace): string[] {
  return facesFor(faces, family, required)
    .map((face) => face.unicodeRange)
    .sort();
}

/** The `url()` sources a family declares for one weight/style pair, sorted for comparison. */
function urlsFor(faces: FontFace[], family: string, required: RequiredFace): string[] {
  return facesFor(faces, family, required)
    .flatMap((face) => [...face.src.matchAll(/url\(\s*['"]?([^'")]+)/g)].map((url) => url[1]))
    .sort();
}

/** How a required face is written in a test name, so a failure says which one. */
function describeFace(required: RequiredFace): string {
  return `${required.weight}/${required.style}`;
}

const css = readFileSync(fontsCssPath, 'utf8');

/** The text between a `#region` marker and its `#endregion`. */
function regionCss(name: string): string {
  const region = new RegExp(
    `/\\* #region ${name} \\*/([\\s\\S]*?)/\\* #endregion ${name} \\*/`,
  ).exec(css);
  if (!region) throw new Error(`fonts.css has no "${name}" region`);
  return region[1];
}

const downloadedCss = regionCss(DOWNLOADED_REGION);
const fontFaces = parseFontFaces(downloadedCss);
const installedCopyFaces = parseFontFaces(regionCss(INSTALLED_COPY_REGION));

/**
 * Families served by a single variable font file spanning a weight RANGE. Their required weights
 * deliberately resolve to the same faces, so the comparisons that catch a half-pasted static family
 * do not apply — they get their own checks instead. Derived from the stylesheet rather than listed
 * by hand, so switching a family to (or from) variable faces cannot leave a stale classification.
 */
const variableWeightFamilies = Object.keys(REQUIRED_FACES).filter((family) =>
  fontFaces.some((face) => face.family === family && isWeightRange(face.weight)),
);
const staticWeightFamilies = Object.keys(REQUIRED_FACES).filter(
  (family) => !variableWeightFamilies.includes(family),
);

describe('Scripture fonts (src/renderer/styles/fonts.css)', () => {
  it('parses the stylesheet it is guarding', () => {
    expect(fontFaces.length).toBeGreaterThan(0);
    expect(fontFaces.every((face) => face.family !== '' && face.src !== '')).toBe(true);
  });

  it('classifies at least one family each way, so neither set of checks is silently empty', () => {
    expect(staticWeightFamilies.length).toBeGreaterThan(0);
    expect(variableWeightFamilies.length).toBeGreaterThan(0);
  });

  it.each(Object.keys(REQUIRED_FACES))('declares every weight and style of %s', (family) => {
    const missing = REQUIRED_FACES[family]
      .filter((required) => facesFor(fontFaces, family, required).length === 0)
      .map(describeFace);
    expect(missing).toEqual([]);
  });

  it.each(staticWeightFamilies)(
    'covers the same unicode-range subsets in every style of %s',
    (family) => {
      // A family is pasted in one subset group per weight/style. Comparing each group against the
      // regular face's catches a half-pasted style, which would otherwise leave exactly the
      // characters in the dropped subsets falling out of the family.
      const [baseline, ...rest] = REQUIRED_FACES[family];
      const baselineSubsets = subsetsFor(fontFaces, family, baseline);
      expect(baselineSubsets.length).toBeGreaterThan(0);
      rest.forEach((required) => {
        expect({
          face: describeFace(required),
          subsets: subsetsFor(fontFaces, family, required),
        }).toEqual({ face: describeFace(required), subsets: baselineSubsets });
      });
    },
  );

  it.each(staticWeightFamilies)('serves each style of %s from its own font files', (family) => {
    // Matching subsets are not enough on their own: copying the regular blocks and editing only
    // `font-weight: 400` to `700` leaves every subset lined up while every face still points at the
    // regular font file, so bold renders as regular text and nothing catches it. Distinct weights
    // and styles of a static family are distinct files, so the URL sets must not overlap.
    const [baseline, ...rest] = REQUIRED_FACES[family];
    const baselineUrls = new Set(urlsFor(fontFaces, family, baseline));
    expect(baselineUrls.size).toBeGreaterThan(0);
    rest.forEach((required) => {
      const shared = urlsFor(fontFaces, family, required).filter((url) => baselineUrls.has(url));
      expect({ face: describeFace(required), sharedWithRegular: shared }).toEqual({
        face: describeFace(required),
        sharedWithRegular: [],
      });
    });
  });

  it.each(variableWeightFamilies)(
    'declares a weight range across %s that actually spans every weight it is used at',
    (family) => {
      // The one thing worth asserting for a variable family: its required weights resolve to the
      // same faces by design, so subset and font-file comparisons across weights would be a set
      // against itself. What can still go wrong is a range too narrow for how the family is used.
      const required = REQUIRED_FACES[family];
      const ranges = fontFaces
        .filter((face) => face.family === family)
        .map((face) => face.weight)
        .filter(isWeightRange);
      expect(ranges.length).toBeGreaterThan(0);
      const uncovered = required
        .filter(({ weight }) => !ranges.every((range) => weightCovers(range, weight)))
        .map(describeFace);
      expect(uncovered).toEqual([]);
    },
  );

  it('leaves the downloaded region exactly as Google emits it', () => {
    // The region is regenerated by pasting the `@import` URL's response whole, so anything
    // hand-written in it is lost on the next regeneration without a trace. `local()` is the
    // tempting edit — it is how a face names an installed copy — and the `*-Local` families in the
    // region after it exist so that nobody has to make it.
    expect(downloadedCss).not.toContain('local(');
    expect(fontFaces.every((face) => face.src.includes('url('))).toBe(true);
  });

  it.each(Object.keys(INSTALLED_COPY_ALIASES))('names only an installed copy in %s', (alias) => {
    // A `local()`-only face resolves iff the font is installed, and otherwise fails invisibly and
    // hands the character on down the stack. Adding a `url()` here would defeat that: the face
    // would start downloading, which is exactly what these families exist to do without.
    const faces = installedCopyFaces.filter((face) => face.family === alias);
    expect(faces.length).toBeGreaterThan(0);
    expect(faces.every((face) => face.src.includes('local(') && !face.src.includes('url('))).toBe(
      true,
    );
  });

  it.each(Object.entries(INSTALLED_COPY_ALIASES))(
    'covers every weight and style of its family in %s',
    (alias, family) => {
      // An installed copy has the family's real faces, so a missing entry here means a bold or
      // italic run silently falls past the installed font to the next family in the stack.
      const missing = REQUIRED_FACES[family]
        .filter((required) => facesFor(installedCopyFaces, alias, required).length === 0)
        .map(describeFace);
      expect(missing).toEqual([]);
    },
  );

  it('guards every family the Scripture font stack relies on', () => {
    const stack = /--scripture-font-stack:([^;]+);/.exec(css);
    expect(stack).not.toBeNull();
    const families = (stack?.[1] ?? '')
      .split(',')
      .map((family) => family.trim().replace(/^['"]|['"]$/g, ''))
      .filter((family) => !GENERIC_FAMILIES.has(family));
    expect(families.length).toBeGreaterThan(0);

    // Both directions. Left to itself, the first check passes while a newly added family sits in
    // the stack with only its regular face declared — which is the bug this file exists to catch.
    Object.keys(REQUIRED_FACES).forEach((family) => {
      expect(families).toContain(family);
    });
    Object.keys(INSTALLED_COPY_ALIASES).forEach((alias) => {
      expect(families).toContain(alias);
    });
    const unaccountedFor = families.filter(
      (family) =>
        !(family in REQUIRED_FACES) &&
        !(family in INSTALLED_COPY_ALIASES) &&
        !(family in UNGUARDED_STACK_FAMILIES),
    );
    expect(unaccountedFor).toEqual([]);

    // Installed copies go last. A downloaded family must win while it can be fetched, so that
    // online rendering is exactly what it would be without these families at all.
    const firstAlias = families.findIndex((family) => family in INSTALLED_COPY_ALIASES);
    const downloadedAfterAlias = families
      .slice(firstAlias)
      .filter((family) => !(family in INSTALLED_COPY_ALIASES));
    expect(downloadedAfterAlias).toEqual([]);
  });

  it.each(VENDORED_EDITOR_STYLESHEETS)('declares no competing Scripture face in %s', (path) => {
    const vendored = readFileSync(resolve(repoRoot, path), 'utf8');
    expect(vendored).toContain('.usfm');
    expect(parseFontFaces(vendored)).toEqual([]);
  });

  it.each(VENDORED_EDITOR_STYLESHEETS)('hands the stack to the editor in %s', (path) => {
    // The editor's generated project stylesheet appends `var(--usj-font-fallback, serif)` to every
    // font it names. Pointing that at this stylesheet's stack is what makes a project whose own
    // font is unavailable fall through the application's Scripture order rather than the editor
    // library's default chain.
    const vendored = readFileSync(resolve(repoRoot, path), 'utf8').replace(/\s+/g, ' ');
    expect(vendored).toContain('--usj-font-fallback: var( --scripture-font-stack,');
  });
});
