import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Guards the Scripture font stack in fonts.css. The failure mode is SILENT and platform-dependent:
// a family declared only at weight 400 / style normal still renders regular text correctly, so
// nothing errors and nothing looks wrong on a machine where the font is also installed locally.
// On a machine where it is not, a bold or italic run selects a face the browser cannot produce and
// drops out of the family altogether, landing on an unrelated system font.
//
// The stylesheet's font-face region is generated by fetching the commented-out `@import` URL at the
// top of fonts.css and pasting Google's response in whole, so that URL is where a family gains a
// weight or style: its `ital,wght` axes must name every combination the family is used at, and
// every face the response emits has to be pasted. Pasting only part of a style leaves exactly the
// characters in the dropped `unicode-range` subsets falling out of the family.

const fontsCssPath = resolve(__dirname, 'fonts.css');

/** One `@font-face` rule's descriptors, with whitespace and quoting normalized. */
type FontFace = {
  family: string;
  style: string;
  /** The `font-weight` descriptor verbatim — a single value (`400`) or a range (`100 900`). */
  weight: string;
  src: string;
  unicodeRange: string;
};

/** A weight/style pair the stack must be able to render with a real face. */
type RequiredFace = { weight: number; style: string };

/**
 * Faces each Scripture-stack family must declare. Every family here is named in the
 * `.scripture-font` stack, and every entry must be backed by a real font file: a browser given a
 * family with no matching face does not fall back to another face of that family, it falls out of
 * the family and onto whatever comes next — which for the editor's project stylesheet is nothing at
 * all.
 *
 * Bold italic is absent for Cardo, and italic entirely for Noto Sans Syriac, because the upstream
 * families ship no such face.
 */
const REQUIRED_FACES: Readonly<{ [family: string]: readonly RequiredFace[] }> = {
  'Charis SIL': [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
    { weight: 700, style: 'italic' },
  ],
  'Gentium Plus': [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
    { weight: 700, style: 'italic' },
  ],
  Cardo: [
    { weight: 400, style: 'normal' },
    { weight: 400, style: 'italic' },
    { weight: 700, style: 'normal' },
  ],
  'Noto Sans Syriac': [
    { weight: 400, style: 'normal' },
    { weight: 700, style: 'normal' },
  ],
};

/** Read one descriptor out of a normalized `@font-face` body, stripping quotes. */
function readDescriptor(body: string, name: string): string {
  const match = new RegExp(`(?:^|;)\\s*${name}\\s*:\\s*([^;]+)`).exec(body);
  if (!match) return '';
  return match[1].trim().replace(/^['"]|['"]$/g, '');
}

/** Parse every `@font-face` rule out of a stylesheet's text. */
function parseFontFaces(css: string): FontFace[] {
  const faces: FontFace[] = [];
  const ruleRegex = /@font-face\s*\{([^}]*)\}/g;
  let rule = ruleRegex.exec(css);
  while (rule) {
    const body = rule[1].replace(/\s+/g, ' ');
    faces.push({
      family: readDescriptor(body, 'font-family'),
      style: readDescriptor(body, 'font-style') || 'normal',
      weight: readDescriptor(body, 'font-weight') || '400',
      src: readDescriptor(body, 'src'),
      unicodeRange: readDescriptor(body, 'unicode-range'),
    });
    rule = ruleRegex.exec(css);
  }
  return faces;
}

/**
 * Whether a `font-weight` descriptor covers a weight. Handles both a single value and the `<min>
 * <max>` range a variable font declares.
 */
function weightCovers(descriptor: string, weight: number): boolean {
  const bounds = descriptor.trim().split(/\s+/).map(Number);
  if (bounds.some(Number.isNaN) || bounds.length === 0) return false;
  const min = bounds[0];
  const max = bounds.length > 1 ? bounds[1] : bounds[0];
  return weight >= min && weight <= max;
}

/** The unicode-range subsets a family declares for one weight/style pair, sorted for comparison. */
function subsetsFor(faces: FontFace[], family: string, required: RequiredFace): string[] {
  return faces
    .filter(
      (face) =>
        face.family === family &&
        face.style === required.style &&
        weightCovers(face.weight, required.weight),
    )
    .map((face) => face.unicodeRange)
    .sort();
}

const css = readFileSync(fontsCssPath, 'utf8');
const fontFaces = parseFontFaces(css);

describe('Scripture fonts (src/renderer/styles/fonts.css)', () => {
  it('parses the stylesheet it is guarding', () => {
    expect(fontFaces.length).toBeGreaterThan(0);
    expect(fontFaces.every((face) => face.family !== '' && face.src !== '')).toBe(true);
  });

  it.each(Object.keys(REQUIRED_FACES))('declares every weight and style of %s', (family) => {
    const missing = REQUIRED_FACES[family].filter(
      (required) => subsetsFor(fontFaces, family, required).length === 0,
    );
    expect(missing).toEqual([]);
  });

  it.each(Object.keys(REQUIRED_FACES))(
    'covers the same unicode-range subsets in every style of %s',
    (family) => {
      // A family is pasted in one subset group per weight/style. Comparing each group against the
      // regular face's catches a half-pasted style, which would otherwise leave exactly the
      // characters in the dropped subsets falling out of the family.
      const [baseline, ...rest] = REQUIRED_FACES[family];
      const baselineSubsets = subsetsFor(fontFaces, family, baseline);
      expect(baselineSubsets.length).toBeGreaterThan(0);
      rest.forEach((required) => {
        expect(subsetsFor(fontFaces, family, required)).toEqual(baselineSubsets);
      });
    },
  );

  it('guards every family the Scripture font stack relies on', () => {
    const stack = /\.scripture-font\s*\{[^}]*font-family:([^;]+);/.exec(css);
    expect(stack).not.toBeNull();
    const families = (stack?.[1] ?? '')
      .split(',')
      .map((family) => family.trim().replace(/^['"]|['"]$/g, ''));
    Object.keys(REQUIRED_FACES).forEach((family) => {
      expect(families).toContain(family);
    });
  });
});
