/**
 * === FUNCTIONAL TESTS — UI-PKG-003: Menu Command + Web View Provider Registration ===
 *
 * Feature: keyboard-switching Work Package: UI-PKG-003 — the entry path into the keyboard-selection
 * dialog: project tab ≡ menu entry → `platform.openKeyboardSelection` command (openManageBooks
 * pattern: webViewId probe → projectId fallback) → `keyboardSelectionWebViewProvider` (title
 * 'Keyboard', `keyboardPreference: 'vernacular'`).
 *
 * Generated by: ui-test-writer (RED phase). Activated GREEN by component-builder (2026-06-12) with
 * Stage-3.5 navigation reconciliation — see the comment above `closeHomeOverlayIfOpen` below.
 *
 * Wiring under test:
 *
 * - `extensions/src/platform-scripture/src/keyboard-selection.web-view-provider.ts` (new —
 *   object-literal IWebViewProvider, title 'Keyboard', serves the UI-PKG-002 web view content)
 * - `extensions/src/platform-scripture/src/main.ts` — `openKeyboardSelection` +
 *   `registerCommand('platform.openKeyboardSelection', ...)` + `registerWebViewProvider`
 * - `extensions/src/platform-scripture-editor/contributions/menus.json` — "Keyboard..." entry on the
 *   project tab ≡ menu (BHV-300/BHV-301; contributed by the editor extension because the menu
 *   belongs to the `platformScriptureEditor.react` web-view type — combine-order-safe ownership)
 * - `extensions/src/platform-scripture/src/types/platform-scripture.d.ts` — command type entry
 *
 * Scope boundary: UI-PKG-002's functional tests pin all IN-DIALOG behavior (render variants,
 * dropdown semantics, OK/Cancel discard semantics, focus order). This file pins only the ENTRY PATH
 * and registration-level behavior observable via UI: menu entry presence/label, correct projectId
 * resolution per invoking tab (PT9 factory-args analog, TS-001/BHV-602), provider tab title,
 * registration durability across invocations, and post-close focus return.
 *
 * Not covered by E2E (see functional-test-plan-UI-PKG-003.md for full justification): TS-003 (no
 * Study Bible Publications fixture in PT10 — exclusion lives in the menu contribution's
 * groups/whenExpression keys), TS-004 (web-view-scoped menus are unreachable without a project tab,
 * so "visible but disabled" has no PT10 E2E analog), the `keyboardPreference: 'vernacular'`
 * FocusKeyboardRouter leg (OS keyboard activation is not DOM-observable; covered by CAP-014/017
 * backend tests + the app-runner runtime verification step), and the literal-projectId/undefined
 * branches of the probe (not reachable via visible UI; pinned by openKeyboardSelection unit tests).
 * The openManageBooks no-regression criterion is guarded by the existing, already-active
 * `e2e-tests/tests/manage-books/` suite — not duplicated here.
 *
 * Conventions:
 *
 * - Uses `cdp.fixture` only (NEVER papi.fixture or app.fixture).
 * - Navigates via visible UI only (NEVER sendPapiCommand).
 * - Every test has a `// @scenario TS-XXX` comment for traceability.
 * - Every entry-path-reachable Test-Contract evidence point has a `mainPage.screenshot()` call.
 * - Helper patterns mirror keyboard-switching-functional-UI-PKG-002.spec.ts (frame matcher,
 *   project-tab navigation) so both files activate against the same shipped wiring.
 */
import type { FrameLocator, Page } from '@playwright/test';
import { test, expect } from '../../fixtures/cdp.fixture';
import { waitForAppReady } from '../../fixtures/helpers';

const SCREENSHOT_BASE = 'proofs/component-evidence/UI-PKG-003';

/**
 * The keyboard-selection web view's iframe + dock-tab title. The provider registers `title:
 * 'Keyboard'` (UI-PKG-003 acceptance criterion); BHV-302 may append the project short-name from
 * inside the web view. The tolerant matcher spans both — GREEN-phase reconciliation tightens it.
 */
const KEYBOARD_FRAME = 'iframe[title*="Keyboard" i]';
const KEYBOARD_TAB_REGEX = /Keyboard/i;
/** The "Keyboard..." entry inside the project tab ≡ menu (BHV-300 designer literal, localized). */
const KEYBOARD_MENU_ITEM_REGEX = /Keyboard/i;

/**
 * Standard-shape fixture (editable Paratext 9 test project in this environment — exposes a
 * scripture projectInterface, so `hasScrText` holds and BHV-301 renders the entry enabled).
 */
const STANDARD_PROJECT = 'zzz6';

/**
 * Resource fixture (read-only). Resources still carry scripture text (`hasScrText === true`) and
 * are not Study Bible Publications projects, so per BHV-301 the Keyboard entry is visible AND
 * enabled on a resource tab too. Used to prove per-tab projectId resolution (the webViewId probe
 * resolves the INVOKING tab's project, not the first/last project opened).
 */
const RESOURCE_PROJECT = 'WEB';

/**
 * GREEN-phase navigation reconciliation (Stage 3.5, 2026-06-12): this environment runs the
 * simple-mode workspace — Home is a floating overlay toggled by the platform toolbar's house button
 * (no permanent Home dock tab), and the scripture editor renders its own TabToolbar INSIDE its
 * web-view iframe (trigger accessible name "Project"; the Radix dropdown portals into the same
 * iframe). The helpers below were tightened accordingly (mirroring
 * keyboard-switching-functional-UI-PKG-002.spec.ts); every test-body assertion is unchanged.
 */
const HOME_BUTTON_SELECTOR = 'button:has(svg.lucide-house)';

/**
 * Wait until the dock's tab titles have localized (no raw percent-delimited loc-key text). Right
 * after an app start the dock can render before the localization service resolves contributed
 * strings; raw keys (e.g. %home_dialog_title%) break every title-based matcher in these helpers.
 */
async function waitForLocalizedDockTitles(mainPage: Page): Promise<void> {
  await expect(mainPage.locator('.dock-tab', { hasText: '%' })).toHaveCount(0, {
    timeout: 60_000,
  });
}

/**
 * Close every Home tab (floating overlay or docked) — the Home overlay floats over the editor's
 * toolbar and would intercept pointer events aimed at the editor's ≡ Project trigger, and a
 * persisted layout from a previous failed run can carry several stacked Home web views. Bounded
 * loop; each close re-renders the dock, so only one tab reliably closes per pass.
 */
async function closeHomeOverlayIfOpen(mainPage: Page): Promise<void> {
  const floatHomeClose = mainPage
    .locator('.dock-tab', { hasText: 'Home' })
    .locator('.dock-tab-close-btn');
  const maxClosures = 8;
  for (let i = 0; i < maxClosures; i += 1) {
    // Sequential awaits intentional: each close re-renders the dock before the next pass.
    // eslint-disable-next-line no-await-in-loop
    if ((await floatHomeClose.count()) === 0) break;
    // Sequential awaits intentional (see loop comment above).
    // eslint-disable-next-line no-await-in-loop
    await floatHomeClose.first().dispatchEvent('click');
    // Sequential awaits intentional (see loop comment above).
    // eslint-disable-next-line no-await-in-loop
    await mainPage.waitForTimeout(300);
  }
}

/**
 * Open a project's editor tab from the Home view's project table. The Home web view
 * (platform-get-resources `home.web-view.tsx`) renders one table row per project with an "Open"
 * button that opens the scripture editor tab for that project.
 */
async function openProjectEditorTab(mainPage: Page, projectShortName: string): Promise<void> {
  await waitForLocalizedDockTitles(mainPage);

  // A tab for this project may already be open from an earlier step in the same test.
  const existingTab = mainPage.locator('.dock-tab', { hasText: projectShortName });
  if ((await existingTab.count()) > 0) {
    await closeHomeOverlayIfOpen(mainPage);
    await existingTab.first().click();
    return;
  }

  // Deterministic Home state: close any Home tabs left by earlier navigation or a persisted
  // layout (stacked Home web views break title-based frame matching), then open exactly ONE
  // fresh Home via the house button. Right after an app start the first click can land before
  // the Home web-view provider has registered (waitForAppReady only covers the dock layout +
  // core RPC), so retry the click until the Home tab appears.
  await closeHomeOverlayIfOpen(mainPage);
  const homeTab = mainPage.locator('.dock-tab', { hasText: 'Home' });
  const maxHomeOpenAttempts = 6;
  for (let attempt = 0; attempt < maxHomeOpenAttempts; attempt += 1) {
    // Sequential awaits intentional: each click needs to settle before re-checking.
    // eslint-disable-next-line no-await-in-loop
    if ((await homeTab.count()) > 0) break;
    // Sequential awaits intentional (see loop comment above).
    // eslint-disable-next-line no-await-in-loop
    await mainPage.locator(HOME_BUTTON_SELECTOR).first().click();
    // Sequential awaits intentional (see loop comment above).
    // eslint-disable-next-line no-await-in-loop
    await mainPage.waitForTimeout(2_000);
  }
  await expect(homeTab.first()).toBeVisible({ timeout: 15_000 });
  // :visible guards against stale hidden Home iframes left by earlier navigation.
  const homeFrame = mainPage.frameLocator('iframe[title*="Home" i]:visible');
  // Generous timeout: right after an app start the PT9 project scan can take a while before the
  // Home table populates (it renders "0 items" until enumeration completes).
  const projectRow = homeFrame.getByRole('row').filter({ hasText: projectShortName }).first();
  await expect(projectRow).toBeVisible({ timeout: 60_000 });
  await projectRow.getByRole('button', { name: /Open/i }).click();

  // The editor tab title carries the project short-name.
  await expect(mainPage.locator('.dock-tab', { hasText: projectShortName }).first()).toBeVisible({
    timeout: 30_000,
  });
  // The Home overlay stays open after "Open" and covers the editor's toolbar — dismiss it, then
  // make sure the editor tab is the active one.
  await closeHomeOverlayIfOpen(mainPage);
  await mainPage.locator('.dock-tab', { hasText: projectShortName }).first().click();
}

/**
 * Open the project tab's ≡ menu. The scripture editor renders its TabToolbar inside its web-view
 * iframe (`tab-toolbar.component.tsx` passes `tabLabel="Project"` for the trigger's accessible
 * name), and the Radix dropdown portals into that same iframe — so both the trigger click and the
 * subsequent menu-item clicks must be scoped to the editor's FrameLocator (returned here).
 */
async function openProjectTabMenu(mainPage: Page, projectShortName: string): Promise<FrameLocator> {
  const editorFrame = mainPage.frameLocator(`iframe[title*="${projectShortName}" i]`);
  await editorFrame.getByRole('button', { name: 'Project', exact: true }).click();
  return editorFrame;
}

/**
 * Navigate to the keyboard-selection dialog for the given project via visible UI: open the
 * project's editor tab, open its ≡ Project menu, click "Keyboard...". Returns a FrameLocator scoped
 * to the dialog's web-view iframe.
 */
async function openKeyboardDialog(mainPage: Page, projectShortName: string): Promise<FrameLocator> {
  await openProjectEditorTab(mainPage, projectShortName);
  const editorFrame = await openProjectTabMenu(mainPage, projectShortName);
  await editorFrame.getByRole('menuitem', { name: KEYBOARD_MENU_ITEM_REGEX }).click();
  await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toBeVisible({
    timeout: 15_000,
  });
  return mainPage.frameLocator(KEYBOARD_FRAME);
}

/**
 * Wait until the provider-served web view content has actually loaded inside the iframe — the
 * description element is the first stable element of the UI-PKG-002 component. Proves the provider
 * (BHV-602's PT10 analog) served real content, not an empty/broken frame.
 */
async function waitForDialogContentLoaded(frame: FrameLocator): Promise<void> {
  await expect(frame.getByTestId('keyboard-selection-description')).toBeVisible({
    timeout: 15_000,
  });
}

test.describe('Keyboard Switching Functional Tests (UI-PKG-003 — Menu Command + Provider Registration)', () => {
  // Close stale Keyboard dialog tabs so each test starts without an already-open dialog.
  //
  // GREEN-phase reconciliation (Stage 3.5): the RED-phase cleanup closed EVERY non-Home tab, but
  // in this simple-mode workspace that triggers the dock's default-layout restore (placeholder
  // panels re-appear mid-loop), racing the cleanup loop and stranding the workspace with no
  // Scripture Editor panel for the next project bind — the next "Open" click then never produces
  // a project tab. The tests only require that no stale Keyboard dialog is open; project/editor
  // tabs are reused (or replaced) by openProjectEditorTab. No test assertion changed.
  test.beforeEach(async ({ mainPage }) => {
    // Escape twice closes any lingering menu dropdown / Radix popover / open Select from a
    // previous test (no-op when nothing is open).
    await mainPage.keyboard.press('Escape');
    await mainPage.keyboard.press('Escape');

    const staleKeyboardClose = mainPage
      .locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })
      .locator('.dock-tab-close-btn');
    // Bounded cleanup: at most one dialog can be open per invocation; the cap prevents a runaway
    // loop if the dock close handler regresses.
    const maxClosures = 4;
    for (let i = 0; i < maxClosures; i += 1) {
      // Sequential awaits intentional: count() must complete before deciding to break, and each
      // close re-renders the dock before the next pass.
      // eslint-disable-next-line no-await-in-loop
      const remaining = await staleKeyboardClose.count();
      if (remaining === 0) break;
      // Closing a tab re-renders the dock, so each close must complete before the next pass.
      // eslint-disable-next-line no-await-in-loop
      await staleKeyboardClose.first().dispatchEvent('click');
      // Brief settle to let React commit the dock-layout state change before re-counting.
      // eslint-disable-next-line no-await-in-loop
      await mainPage.waitForTimeout(300);
    }
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 1: Navigation — the registered command is reachable through the
  // project tab ≡ menu and opens the provider-served dialog (BHV-300, BHV-602)
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-001 (BHV-300 single entry point; BHV-602 provider is the sole instantiation
  // path — the opened frame must contain the UI-PKG-002 component, proving the provider served
  // real content for the registered web-view type)
  test('should open the Keyboard dialog from the project tab menu via the registered command', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await openProjectEditorTab(mainPage, STANDARD_PROJECT);

    const editorFrame = await openProjectTabMenu(mainPage, STANDARD_PROJECT);

    // EVD-001: project tab menu open with the "Keyboard..." item visible.
    await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-001-menu-open.png` });

    const keyboardItem = editorFrame.getByRole('menuitem', { name: KEYBOARD_MENU_ITEM_REGEX });
    await expect(keyboardItem).toBeVisible({ timeout: 10_000 });
    await keyboardItem.click();

    // The command opened the web view: a dock tab appears for it...
    await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toBeVisible({
      timeout: 15_000,
    });

    // ...and the provider served the UI-PKG-002 content (not an empty frame): the description
    // and primary controls are present inside the iframe.
    const frame = mainPage.frameLocator(KEYBOARD_FRAME);
    await waitForDialogContentLoaded(frame);
    await expect(frame.getByRole('button', { name: /^OK$/i })).toBeVisible();
    await expect(frame.getByRole('button', { name: /Cancel/i })).toBeVisible();
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 2: Render / Registration — localized menu label, provider title
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-001, TS-002 (BHV-300 designer literal "Keyboard..." via localizedStrings —
  // UI-PKG-001; provider acceptance criterion: `title: 'Keyboard'` on the WebViewDefinition)
  test('should register a localized menu label and the provider-supplied "Keyboard" tab title', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await openProjectEditorTab(mainPage, STANDARD_PROJECT);
    const editorFrame = await openProjectTabMenu(mainPage, STANDARD_PROJECT);

    // The menu label is the LOCALIZED string, not a raw percent-wrapped loc-key leak, and matches the PT9
    // designer literal "Keyboard..." (tolerant of '...' vs '…' — GREEN tightens).
    const keyboardItem = editorFrame.getByRole('menuitem', { name: KEYBOARD_MENU_ITEM_REGEX });
    await expect(keyboardItem).toBeVisible({ timeout: 10_000 });
    const label = (await keyboardItem.innerText()).trim();
    expect(label).not.toContain('%');
    expect(label).toMatch(/^Keyboard(\.{3}|…)?$/i);

    await keyboardItem.click();
    const keyboardTab = mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX }).first();
    await expect(keyboardTab).toBeVisible({ timeout: 15_000 });

    // The dock-tab title comes from the provider's `title: 'Keyboard'` (BHV-302 may append the
    // project short-name from inside the web view — the prefix is what this WP pins). No raw
    // loc-key leak in the title either.
    const tabText = (await keyboardTab.innerText()).trim();
    expect(tabText).toMatch(/^Keyboard/i);
    expect(tabText).not.toContain('%');

    // EVD-002: dialog opened (standard project) with provider-served content fully loaded.
    const frame = mainPage.frameLocator(KEYBOARD_FRAME);
    await waitForDialogContentLoaded(frame);
    await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-002-window-loaded.png` });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 3: Data Wiring — the command resolves the INVOKING tab's projectId
  // (webViewId probe via getOpenWebViewDefinition → def.projectId)
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-001, TS-018 (PT9 factory-args analog: CreateKeyboardSelectionWindow received the
  // menu's scrText — in PT10 the menu passes the invoking editor's webViewId, the command probes
  // it for projectId, and the dialog description interpolates that project's short-name)
  test("should resolve the invoking tab's project into the dialog (webViewId probe)", async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
    await waitForDialogContentLoaded(frame);

    // The description interpolates the REAL project short-name resolved from the invoking
    // tab's webViewId — wired data, not a placeholder and not empty.
    const description = frame.getByTestId('keyboard-selection-description');
    await expect(description).toContainText(STANDARD_PROJECT);
    const descriptionText = (await description.innerText()).trim();
    expect(descriptionText).not.toBe('');
    expect(descriptionText).not.toContain('%');
  });

  // @scenario TS-001, TS-002 (per-tab resolution: the probe resolves the project of the tab whose
  // menu was clicked — NOT the first/last opened project. Also pins BHV-301 on a resource tab:
  // resources have scrText and are not Study Bible Publications, so the entry is visible+enabled)
  test('should resolve projectId per invoking tab, not globally (second project, resource tab)', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);

    // Open the standard project FIRST so a wrong "first/global project" implementation would
    // leak zzz6 into the dialog below.
    await openProjectEditorTab(mainPage, STANDARD_PROJECT);

    // Now open the resource tab and invoke Keyboard from ITS menu.
    await openProjectEditorTab(mainPage, RESOURCE_PROJECT);
    const editorFrame = await openProjectTabMenu(mainPage, RESOURCE_PROJECT);

    // BHV-301 on a resource tab: visible AND enabled (hasScrText, not SBP).
    const keyboardItem = editorFrame.getByRole('menuitem', { name: KEYBOARD_MENU_ITEM_REGEX });
    await expect(keyboardItem).toBeVisible({ timeout: 10_000 });
    await expect(keyboardItem).toBeEnabled();
    await keyboardItem.click();

    await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toBeVisible({
      timeout: 15_000,
    });
    const frame = mainPage.frameLocator(KEYBOARD_FRAME);
    await waitForDialogContentLoaded(frame);

    // The dialog names the INVOKING tab's project — the resource, not the earlier project.
    const description = frame.getByTestId('keyboard-selection-description');
    await expect(description).toContainText(RESOURCE_PROJECT);
    await expect(description).not.toContainText(STANDARD_PROJECT);
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 4: Interaction — entry-path round trips (close + focus return,
  // registration durability). In-dialog OK/Cancel semantics live in UI-PKG-002.
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-016, TS-018 (entry-path slice of the gm-009 orchestration: OK → closeWebView →
  // focus returns to the invoking project surface per FN-014. The setProjectDefaultKeyboard
  // write legs are pinned by UI-PKG-002 TS-013 and the cross-WP journey test)
  test('should close on OK and return focus to the invoking project tab', async ({ mainPage }) => {
    await waitForAppReady(mainPage);
    const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
    await waitForDialogContentLoaded(frame);

    await frame.getByRole('button', { name: /^OK$/i }).click();

    // closeWebView ran: the dialog's dock tab is gone.
    await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
      timeout: 15_000,
    });

    // Focus restoration: the invoking project tab is the active tab again (FN-014 — restore on
    // close fires on positive close).
    await expect(mainPage.locator('.dock-tab', { hasText: STANDARD_PROJECT }).first()).toHaveClass(
      /dock-tab-active/,
      { timeout: 10_000 },
    );

    // EVD-009: post-OK state — dialog gone, focus back on the invoking project tab.
    await mainPage.screenshot({
      path: `${SCREENSHOT_BASE}/EVD-009-after-ok-focus-returned.png`,
    });
  });

  // @scenario TS-017 (entry-path slice: Cancel closes via closeWebView, and the registration is
  // DURABLE — a second menu invocation re-opens the dialog with content. The no-writes discard
  // assertion lives in UI-PKG-002's Cancel test)
  test('should support repeated invocation: Cancel, then reopen from the menu', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    let frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
    await waitForDialogContentLoaded(frame);

    await frame.getByRole('button', { name: /Cancel/i }).click();
    await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
      timeout: 15_000,
    });

    // EVD-010: post-Cancel state — dialog gone, project tab back in front.
    await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-010-after-cancel.png` });

    // Second invocation through the same menu path: the command + provider registrations are
    // still live (registerCommand/registerWebViewProvider are session-long), so the dialog
    // opens again with full content and the same project context.
    frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
    await waitForDialogContentLoaded(frame);
    await expect(frame.getByTestId('keyboard-selection-description')).toContainText(
      STANDARD_PROJECT,
    );
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 5: Validation
  //
  // No VAL-XXX entries apply to this WP: the keyboard-selection screen has no field-level
  // validation by design (ui-spec "Validation Rules"), and the registration layer's conditional
  // rules are BHV-301 menu visibility (Category 6 below + the documented TS-003/TS-004
  // non-coverage in functional-test-plan-UI-PKG-003.md).
  // ═══════════════════════════════════════════════════════════════════════════

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 6: Edge Cases — BHV-301 visibility, entry-path console hygiene
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-002 (BHV-301 happy path: standard project tab → Visible=true, Enabled=true.
  // TS-003/TS-004 variants are not E2E-reachable in PT10 — see the file header)
  test('should show the Keyboard menu item visible and enabled for a standard project tab', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);
    await openProjectEditorTab(mainPage, STANDARD_PROJECT);
    const editorFrame = await openProjectTabMenu(mainPage, STANDARD_PROJECT);

    const keyboardItem = editorFrame.getByRole('menuitem', { name: KEYBOARD_MENU_ITEM_REGEX });
    await expect(keyboardItem).toBeVisible({ timeout: 10_000 });
    // Enabled both as a control state and in the a11y tree (no aria-disabled grey-out).
    await expect(keyboardItem).toBeEnabled();
    await expect(keyboardItem).not.toHaveAttribute('aria-disabled', 'true');

    // Close the menu without invoking, leaving the dock clean for the next test.
    await mainPage.keyboard.press('Escape');
  });

  // @scenario TS-001 (registration hygiene: command + provider registration failures, probe
  // errors, and missing-loc-key warnings all land on the console — the full entry path
  // menu → open → loaded → Cancel-close must stay clean)
  test('should not leak console errors during the menu → open → close entry path', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);

    const consoleErrors: string[] = [];
    mainPage.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });

    const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
    await waitForDialogContentLoaded(frame);
    await frame.getByRole('button', { name: /Cancel/i }).click();
    await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
      timeout: 15_000,
    });

    const criticalErrors = consoleErrors.filter(
      (e) =>
        !e.includes('DevTools') &&
        !e.includes('favicon') &&
        !e.includes('source map') &&
        !e.includes('net::ERR_'),
    );
    expect(criticalErrors).toHaveLength(0);
  });
});
