/**
 * === RED PHASE FUNCTIONAL TESTS — UI-PKG-002: Keyboard Selection Web View (wiring) ===
 *
 * Feature: keyboard-switching Work Package: UI-PKG-002 — web-view entry
 * (`keyboard-selection.web-view.tsx`) consuming the pre-built, UX-approved presentational component
 * (`extensions/src/platform-scripture/src/keyboard-selection.component.tsx`).
 *
 * Generated by: ui-test-writer (RED phase — all tests use test.fixme()).
 *
 * Wiring under test (NOT YET IMPLEMENTED — that's why every test is .fixme):
 *
 * - `extensions/src/platform-scripture/src/keyboard-selection.web-view.tsx` — useData reads
 *   (ProjectDefaultKeyboards / LastUsedKeyboards / AvailableKeyboards), projectLookup metadata for
 *   projectInterfaces, OK = per-surface setProjectDefaultKeyboard loop + closeWebView, Cancel =
 *   closeWebView only, errors → papi.notifications (dialog stays open).
 * - Navigation depends on UI-PKG-003 (menu command `platform.openKeyboardSelection` + provider
 *   registration). Per the strategic-plan coordination note, these tests navigate via the project
 *   tab ≡ "Project" menu → "Keyboard..." item (the interaction-map path) so they activate cleanly
 *   once UI-PKG-003 lands.
 *
 * Selector strategy: data-testids confirmed against the existing presentational component (Test
 * Contract in ui-spec-keyboard-selection.md): keyboard-selection-description,
 * keyboard-selection-text-label, keyboard-selection-text-keyboard, keyboard-selection-notes-label,
 * keyboard-selection-notes-keyboard, keyboard-selection-loading, keyboard-selection-empty-hint,
 * keyboard-selection-sentinel-item. OK / Cancel / dropdown items via role + accessible name.
 *
 * Environment note (Linux CI / WSL — NO IBus): `AvailableKeyboards` enumerates EMPTY here, so the
 * gm-012 empty-state hint is the reachable real-data path. Empty-state rendering, OK-enabled, and
 * sentinel semantics are asserted directly. Populated-dropdown variants (TS-008 ordering beyond the
 * sentinel, TS-010 RTL names, TS-013 persisted initial selection) carry in-body
 * `test.skip(noKeyboards, ...)` guards: they execute fully on hosts with a real OS keyboard layer
 * and skip with a documented env requirement here (visual variants are pinned by the Storybook
 * stories from phase-3-ui-design).
 *
 * Not covered by E2E (see functional-test-plan-UI-PKG-002.md for justification): TS-006/EVD-004
 * (note-type shape — dormant in PT10, Storybook-verified), TS-015/EVD-011/EVD-012 (missing
 * persisted keyboard + throttled notification — precondition cannot be created via visible UI;
 * backend behavior covered by Vitest, dialog fallback by Storybook).
 *
 * Conventions:
 *
 * - Uses `cdp.fixture` only (NEVER papi.fixture or app.fixture).
 * - Navigates via visible UI only (NEVER sendPapiCommand).
 * - Every test has a `// @scenario TS-XXX` comment for traceability.
 * - Every reachable Test-Contract evidence point (EVD-XXX) has a `mainPage.screenshot()` call.
 */
import type { FrameLocator, Page } from '@playwright/test';
import { test, expect } from '../../fixtures/cdp.fixture';
import { waitForAppReady } from '../../fixtures/helpers';

const SCREENSHOT_BASE = 'proofs/component-evidence/UI-PKG-002';

/**
 * The keyboard-selection web view's iframe + dock-tab title. The provider pattern in
 * ui-alignment.md registers `title: 'Keyboard'`; the Test Contract proposed "Keyboard Selection".
 * The tolerant matcher spans both — GREEN-phase reconciliation tightens it to the shipped title.
 */
const KEYBOARD_FRAME = 'iframe[title*="Keyboard" i]';
const KEYBOARD_TAB_REGEX = /Keyboard/i;
/** The "Keyboard..." entry inside the project tab ≡ menu (wired by UI-PKG-003). */
const KEYBOARD_MENU_ITEM_REGEX = /Keyboard/i;

/**
 * Standard-shape fixture (scripture + comments interfaces → both dropdowns). `zzz6` is an editable
 * Paratext 9 test project present in this environment's `~/.platform.bible/projects/Paratext 9
 * Projects/`. Editable Paratext projects expose both a scripture projectInterface and the
 * legacy-comment-manager comments projectInterface, so the dialog renders the gm-001 standard
 * shape.
 */
const STANDARD_PROJECT = 'zzz6';

/**
 * Resource-shape fixture (scripture but NO comments interface → single dropdown, "Keyboard:"
 * label). `WEB` is the read-only resource fixture in this environment (its editable sibling is
 * `WEB_edit`). Per the paranext-core PR #2342 factory split, resources do not get the comments
 * projectInterface. GREEN phase reconciles the fixture if its interfaces differ.
 */
const RESOURCE_PROJECT = 'WEB';

/** Sentinel display text (RF-001 resolution: parens REMOVED from PT9's KeyboardSelectionForm_4). */
const SENTINEL_TEXT_REGEX = /Do not switch keyboard/i;
/** Sentinel screen-reader name (FN-007 part b). */
const SENTINEL_A11Y_NAME_REGEX = /Use system default/i;

/**
 * Open a project's editor tab from the Home tab's project table. The Home web view
 * (platform-get-resources `home.web-view.tsx`) renders one table row per project with an "Open"
 * button that opens the scripture editor tab for that project.
 */
async function openProjectEditorTab(mainPage: Page, projectShortName: string): Promise<void> {
  // A tab for this project may already be open from an earlier step in the same test.
  const existingTab = mainPage.locator('.dock-tab', { hasText: projectShortName });
  if ((await existingTab.count()) > 0) {
    await existingTab.first().click();
    return;
  }

  // Activate the Home tab, then open the project from its table row.
  await mainPage.locator('.dock-tab', { hasText: 'Home' }).first().click();
  const homeFrame = mainPage.frameLocator('iframe[title*="Home" i]');
  const projectRow = homeFrame.getByRole('row').filter({ hasText: projectShortName }).first();
  await expect(projectRow).toBeVisible({ timeout: 15_000 });
  await projectRow.getByRole('button', { name: /Open/i }).click();

  // The editor tab title carries the project short-name.
  await expect(mainPage.locator('.dock-tab', { hasText: projectShortName }).first()).toBeVisible({
    timeout: 30_000,
  });
}

/**
 * Open the project tab's ≡ menu (the TabToolbar dropdown trigger with accessible name "Project" —
 * `tab-toolbar.component.tsx` passes `tabLabel="Project"`). Only the active tab renders a visible
 * toolbar, so the first visible match is the focused project tab's trigger.
 */
async function openProjectTabMenu(mainPage: Page): Promise<void> {
  await mainPage
    .getByRole('button', { name: 'Project', exact: true })
    .locator('visible=true')
    .first()
    .click();
}

/**
 * Navigate to the keyboard-selection dialog for the given project via visible UI: open the
 * project's editor tab, open its ≡ Project menu, click "Keyboard...". Returns a FrameLocator scoped
 * to the dialog's web-view iframe.
 */
async function openKeyboardDialog(mainPage: Page, projectShortName: string): Promise<FrameLocator> {
  await openProjectEditorTab(mainPage, projectShortName);
  await openProjectTabMenu(mainPage);
  await mainPage.getByRole('menuitem', { name: KEYBOARD_MENU_ITEM_REGEX }).click();
  await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toBeVisible({
    timeout: 15_000,
  });
  return mainPage.frameLocator(KEYBOARD_FRAME);
}

/**
 * Wait until keyboard enumeration settles (the loading indicator is gone and the text dropdown is
 * interactable). The dialog renders chrome immediately and enumerates async (FN-013).
 */
async function waitForKeyboardsSettled(frame: FrameLocator): Promise<void> {
  await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toBeVisible({
    timeout: 15_000,
  });
  await expect(frame.getByTestId('keyboard-selection-loading')).toHaveCount(0, { timeout: 15_000 });
}

/**
 * Open the text-keyboard dropdown and return the number of REAL (non-sentinel) keyboard options —
 * i.e., the live OS enumeration count. Leaves the dropdown open; callers close it (Escape) or
 * select an item.
 */
async function openTextDropdownAndCountRealKeyboards(frame: FrameLocator): Promise<number> {
  await frame.getByTestId('keyboard-selection-text-keyboard').click();
  await expect(frame.getByTestId('keyboard-selection-sentinel-item')).toBeVisible({
    timeout: 10_000,
  });
  const allOptions = await frame.locator('[role="option"]').count();
  // Each dropdown renders exactly one sentinel item at index 0; the rest are OS keyboards.
  return allOptions - 1;
}

test.describe('Keyboard Switching Functional Tests (UI-PKG-002 — Keyboard Selection Web View)', () => {
  // Close all tabs except Home to start from a clean state. Platform.Bible persists the dock
  // layout across sessions, so a stale Keyboard dialog or editor tab from a previous test would
  // otherwise pollute these tests. Each test opens its own project tab via openProjectEditorTab.
  test.beforeEach(async ({ mainPage }) => {
    // Escape twice closes any lingering menu dropdown / Radix popover / open Select from a
    // previous test (no-op when nothing is open).
    await mainPage.keyboard.press('Escape');
    await mainPage.keyboard.press('Escape');

    const staleCloseBtn = mainPage
      .locator('.dock-tab')
      .filter({ hasNotText: 'Home' })
      .locator('.dock-tab-close-btn');
    // Bounded cleanup: a real environment never has more than a handful of stale tabs; the cap
    // prevents a runaway loop if the dock close handler regresses.
    const maxClosures = 8;
    for (let i = 0; i < maxClosures; i += 1) {
      // Sequential awaits intentional: count() must complete before deciding to break, and each
      // close re-renders the dock before the next pass.
      // eslint-disable-next-line no-await-in-loop
      const remaining = await staleCloseBtn.count();
      if (remaining === 0) break;
      // Closing a tab re-renders the dock, so each close must complete before the next pass.
      // eslint-disable-next-line no-await-in-loop
      await staleCloseBtn.first().dispatchEvent('click');
      // Brief settle to let React commit the dock-layout state change before re-counting.
      // eslint-disable-next-line no-await-in-loop
      await mainPage.waitForTimeout(300);
    }
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 1: Navigation — project tab ≡ menu → "Keyboard..." opens the dialog
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-007 (standard project reaches the dialog; the menu wiring itself is UI-PKG-003 —
  // BHV-300/BHV-602 single entry point — these tests consume that path per the interaction map)
  test.fixme(
    'should open the keyboard-selection dialog from the project tab menu',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      await openProjectEditorTab(mainPage, STANDARD_PROJECT);

      await openProjectTabMenu(mainPage);

      // EVD-001: project tab menu open with the "Keyboard..." item visible.
      await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-001-menu-open.png` });

      const keyboardItem = mainPage.getByRole('menuitem', { name: KEYBOARD_MENU_ITEM_REGEX });
      await expect(keyboardItem).toBeVisible({ timeout: 10_000 });
      await keyboardItem.click();

      // The dialog opens as a web view — its dock tab carries the keyboard title (BHV-302: the
      // title interpolates the project short-name, e.g. "Keyboard: zzz6"; tolerant matcher here).
      await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toBeVisible({
        timeout: 15_000,
      });
    },
  );

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 2: Render — layout variants from real projectInterfaces metadata
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-007 (gm-001 standard shape — BHV-303/BHV-304 default branch)
  test.fixme(
    'should render the standard shape for a standard project: both dropdowns visible and enabled',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      // Both labels with their full project-flow text (qualifiers present because the comments
      // dropdown is rendered).
      await expect(frame.getByTestId('keyboard-selection-text-label')).toHaveText(
        /Keyboard for text:/i,
      );
      await expect(frame.getByTestId('keyboard-selection-notes-label')).toHaveText(
        /Keyboard for notes:/i,
      );

      // Both dropdowns visible AND enabled (VAL-B-01 standard branch).
      const textDropdown = frame.getByTestId('keyboard-selection-text-keyboard');
      const notesDropdown = frame.getByTestId('keyboard-selection-notes-keyboard');
      await expect(textDropdown).toBeVisible();
      await expect(textDropdown).toBeEnabled();
      await expect(notesDropdown).toBeVisible();
      await expect(notesDropdown).toBeEnabled();

      // Description interpolates the REAL project short-name (data wired from the open args /
      // project metadata — not a placeholder).
      await expect(frame.getByTestId('keyboard-selection-description')).toContainText(
        STANDARD_PROJECT,
      );

      // OK and Cancel present.
      await expect(frame.getByRole('button', { name: /^OK$/i })).toBeVisible();
      await expect(frame.getByRole('button', { name: /Cancel/i })).toBeVisible();

      // EVD-002: standard variant fully rendered.
      await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-002-standard-shape.png` });
    },
  );

  // @scenario TS-005 (gm-002 resource shape — BHV-303)
  test.fixme(
    'should render the resource shape for a resource project: single dropdown, notes controls omitted',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, RESOURCE_PROJECT);
      await waitForKeyboardsSettled(frame);

      // Label simplifies to "Keyboard:" (loc key %keyboardSelection_textKeyboardLabelResource% /
      // PT9 KeyboardSelectionForm_3) — the "for text" qualifier only exists to disambiguate from
      // the comments dropdown, which is not rendered here.
      await expect(frame.getByTestId('keyboard-selection-text-label')).toHaveText(/^Keyboard:$/i);
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toBeEnabled();

      // Notes label + dropdown are OMITTED from the layout entirely (not just hidden) — PT9
      // Visible=false parity per the acceptance criteria.
      await expect(frame.getByTestId('keyboard-selection-notes-label')).toHaveCount(0);
      await expect(frame.getByTestId('keyboard-selection-notes-keyboard')).toHaveCount(0);

      // Description interpolates the resource short-name.
      await expect(frame.getByTestId('keyboard-selection-description')).toContainText(
        RESOURCE_PROJECT,
      );

      // EVD-003: resource variant rendered.
      await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-003-resource-shape.png` });
    },
  );

  // @scenario TS-009 (gm-012 empty state — the reachable real-data path on this no-IBus host)
  test.fixme(
    'should show the empty-state hint with OK still enabled when the OS reports no keyboards',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      const realKeyboardCount = await openTextDropdownAndCountRealKeyboards(frame);
      await mainPage.keyboard.press('Escape'); // close the dropdown again
      test.skip(
        realKeyboardCount > 0,
        'Empty-state path requires a host with NO OS keyboards enumerated (no IBus). ' +
          'This host has keyboards installed — the empty-state variant is pinned by the ' +
          'Storybook EmptyState story instead.',
      );

      // FN-008 / gm-012: the empty-state hint is visible once enumeration settles empty.
      const emptyHint = frame.getByTestId('keyboard-selection-empty-hint');
      await expect(emptyHint).toBeVisible();
      await expect(emptyHint).toContainText(/No keyboards/i);

      // The dropdown points at the hint for assistive tech (aria-describedby contains the hint's
      // id — asserted via the id round-trip).
      const hintId = await emptyHint.getAttribute('id');
      expect(hintId).toBeTruthy();
      const describedBy = await frame
        .getByTestId('keyboard-selection-text-keyboard')
        .getAttribute('aria-describedby');
      expect(describedBy ?? '').toContain(hintId ?? '__missing__');

      // OK stays ENABLED — "no keyboard switching" (sentinel everywhere) is a legitimate choice.
      await expect(frame.getByRole('button', { name: /^OK$/i })).toBeEnabled();

      // EVD-006: empty state rendered.
      await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-006-empty-state.png` });
    },
  );

  // @scenario TS-011, TS-012 (BHV-306 sentinel at index 0; FN-007 part b styled-placeholder a11y)
  test.fixme(
    'should render the sentinel as the first dropdown item, as a styled placeholder without parens',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      // Open the text-keyboard dropdown.
      await frame.getByTestId('keyboard-selection-text-keyboard').click();

      // TS-011 / INV-B1-03: sentinel is ALWAYS present and is the FIRST option.
      const sentinelItem = frame.getByTestId('keyboard-selection-sentinel-item');
      await expect(sentinelItem).toBeVisible({ timeout: 10_000 });
      const firstOption = frame.locator('[role="option"]').first();
      await expect(firstOption).toHaveAttribute('data-testid', 'keyboard-selection-sentinel-item');

      // TS-012 / RF-001 resolution: display text has NO literal parentheses ("Do not switch
      // keyboard", not PT9's "(Do not switch keyboard)").
      await expect(sentinelItem).toContainText(SENTINEL_TEXT_REGEX);
      const sentinelText = (await sentinelItem.innerText()).trim();
      expect(sentinelText).not.toMatch(/[()]/);

      // TS-012 / FN-007 part b: screen-reader name is the meaningful "Use system default" — the
      // a11y tree must not verbalize placeholder styling conventions.
      const ariaLabel = await sentinelItem.getAttribute('aria-label');
      expect(ariaLabel ?? '').toMatch(SENTINEL_A11Y_NAME_REGEX);

      // Close the dropdown; the COLLAPSED display shows the sentinel as placeholder styling (the
      // sentinel is the initial selection on a never-configured project — TS-014 overlap).
      await mainPage.keyboard.press('Escape');
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toContainText(
        SENTINEL_TEXT_REGEX,
      );
    },
  );

  // @scenario TS-008 (FN-013 loading state — async enumeration; spinner is transient so the
  // deterministic assertion targets the always-in-DOM polite live region and the settled state)
  test.fixme(
    'should announce loading politely and enable controls once enumeration settles',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);

      // EVD-005 (best-effort): captured immediately after open — on slow enumeration this shows
      // the spinner + disabled dropdowns; on fast enumeration it shows the settled dialog. The
      // deterministic loading-variant visual is pinned by the Storybook Loading story.
      await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-005-loading-or-settled.png` });

      // The polite live region (role=status) is ALWAYS in the DOM so screen readers track its
      // content changes (FN-013 contract).
      await expect(frame.getByRole('status')).toBeAttached({ timeout: 15_000 });

      // After enumeration settles: loading indicator gone, dropdown + OK enabled, live region
      // emptied (no stale "Loading keyboards" announcement).
      await waitForKeyboardsSettled(frame);
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toBeEnabled();
      await expect(frame.getByRole('button', { name: /^OK$/i })).toBeEnabled();
      await expect(frame.getByRole('status')).toHaveText('');
    },
  );

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 3: Data Wiring — real backend data (no placeholders, no stubs)
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-008, TS-009 (gm-004 dropdown population from the REAL OS enumeration via
  // useData('platform.keyboard').AvailableKeyboards — sentinel + OS keyboards in OS order)
  test.fixme(
    'should populate the dropdown from the real OS keyboard enumeration (sentinel first)',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      const realKeyboardCount = await openTextDropdownAndCountRealKeyboards(frame);

      // Shape contract that holds on EVERY host: the sentinel is item 0 and is the only
      // non-OS item. On this no-IBus host realKeyboardCount === 0 (graceful-degradation
      // contract, BHV-305 OS layer); with a real OS layer it is > 0.
      expect(realKeyboardCount).toBeGreaterThanOrEqual(0);
      const firstOption = frame.locator('[role="option"]').first();
      await expect(firstOption).toHaveAttribute('data-testid', 'keyboard-selection-sentinel-item');

      // Every real item displays a non-empty OS-reported name (wired data, not placeholders).
      const optionTexts = await frame.locator('[role="option"]').allInnerTexts();
      optionTexts.slice(1).forEach((text) => {
        expect(text.trim()).not.toBe('');
      });

      await mainPage.keyboard.press('Escape');
    },
  );

  // @scenario TS-013 (gm-007/gm-011 initial selection matches persisted keyboard — requires a
  // populated OS enumeration so a real keyboard can be persisted first via the UI)
  test.fixme(
    'should pre-select the persisted keyboard on reopen after saving a selection',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      let frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      const realKeyboardCount = await openTextDropdownAndCountRealKeyboards(frame);
      test.skip(
        realKeyboardCount === 0,
        'Requires ≥1 OS keyboard enumerated (no IBus on this Linux CI/WSL host). Persisted ' +
          'initial selection is pinned by the Storybook stories + component unit tests; this ' +
          'test runs for real on hosts with an OS keyboard layer.',
      );

      // Pick the first REAL keyboard (option index 1 — index 0 is the sentinel).
      const firstRealOption = frame.locator('[role="option"]').nth(1);
      const pickedName = (await firstRealOption.innerText()).trim();
      await firstRealOption.click();

      // EVD-007: collapsed display shows the new selection.
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toContainText(pickedName);
      await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-007-selection-changed.png` });

      // Persist via OK (per-surface setProjectDefaultKeyboard loop) — dialog closes.
      await frame.getByRole('button', { name: /^OK$/i }).click();
      await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
        timeout: 15_000,
      });

      // Reopen: the initial selection is the persisted keyboard (string-compare on KeyboardId —
      // VAL-B-03), proving the ProjectDefaultKeyboards read wiring round-trips real data.
      frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toContainText(pickedName);

      // Cleanup: restore the sentinel so this test is re-runnable (select sentinel + OK).
      await frame.getByTestId('keyboard-selection-text-keyboard').click();
      await frame.getByTestId('keyboard-selection-sentinel-item').click();
      await frame.getByRole('button', { name: /^OK$/i }).click();
      await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
        timeout: 15_000,
      });
    },
  );

  // @scenario TS-014 (VAL-B-03: no persisted keyboard → sentinel pre-selected)
  test.fixme(
    'should pre-select the sentinel when the project has no persisted keyboard',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      // Never-configured project: the collapsed display of BOTH dropdowns shows the sentinel as
      // a styled placeholder, NOT a real selection (gm-006).
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toContainText(
        SENTINEL_TEXT_REGEX,
      );
      await expect(frame.getByTestId('keyboard-selection-notes-keyboard')).toContainText(
        SENTINEL_TEXT_REGEX,
      );
    },
  );

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 4: Interaction — OK / Cancel / keyboard shortcuts
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-016 (BHV-308 OK accepts and closes — per-surface write loop + closeWebView)
  test.fixme('should close the dialog when OK is clicked', async ({ mainPage }) => {
    await waitForAppReady(mainPage);
    const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
    await waitForKeyboardsSettled(frame);

    await frame.getByRole('button', { name: /^OK$/i }).click();

    // OK = setProjectDefaultKeyboard per rendered surface, then closeWebView: the dock tab goes
    // away. (Sentinel selections write `undefined` = keep/remove no association — still a valid,
    // succeeding write path.)
    await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
      timeout: 15_000,
    });

    // EVD-009: post-OK state — dialog gone, focus back on the project surface.
    await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-009-after-ok.png` });
  });

  // @scenario TS-016 (BHV-308 Enter accepts — native button activation on the focused OK button;
  // Enter on a CLOSED Select trigger is consumed by Radix to open the dropdown, so the
  // deterministic Enter path is via the OK button, matching PT9's AcceptButton semantics)
  test.fixme(
    'should accept the dialog when Enter is pressed on the OK button',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      await frame.getByRole('button', { name: /^OK$/i }).focus();
      await mainPage.keyboard.press('Enter');

      await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
        timeout: 15_000,
      });
    },
  );

  // @scenario TS-017 (BHV-309 Cancel discards — closeWebView only, NO setProjectDefaultKeyboard
  // writes; verified user-visibly by reopening and observing the selection unchanged)
  test.fixme(
    'should discard selection changes on Cancel — reopening shows the previous selection',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      let frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      // Make a user interaction before cancelling. With a populated enumeration pick the first
      // real keyboard (the strong variant of this test); on an empty host re-affirm the sentinel
      // (interaction still exercised; the unchanged-on-reopen assertion still pins BHV-309).
      const realKeyboardCount = await openTextDropdownAndCountRealKeyboards(frame);
      if (realKeyboardCount > 0) {
        await frame.locator('[role="option"]').nth(1).click();
      } else {
        await frame.getByTestId('keyboard-selection-sentinel-item').click();
      }

      await frame.getByRole('button', { name: /Cancel/i }).click();

      // Dialog closes with NO writes.
      await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
        timeout: 15_000,
      });

      // EVD-010: post-Cancel state — dialog gone.
      await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-010-after-cancel.png` });

      // Reopen: the selection is UNCHANGED (sentinel — nothing was ever persisted for this
      // project), proving Cancel made no setProjectDefaultKeyboard writes.
      frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toContainText(
        SENTINEL_TEXT_REGEX,
      );
    },
  );

  // @scenario TS-017 (BHV-308/BHV-309 Escape cancels)
  test.fixme('should cancel the dialog when Escape is pressed', async ({ mainPage }) => {
    await waitForAppReady(mainPage);
    const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
    await waitForKeyboardsSettled(frame);

    // Initial focus is inside the dialog (on the text dropdown trigger — FN-009), so Escape
    // bubbles to the dialog-wide handler (the dropdown is closed; Radix does not consume it).
    await mainPage.keyboard.press('Escape');

    await expect(mainPage.locator('.dock-tab', { hasText: KEYBOARD_TAB_REGEX })).toHaveCount(0, {
      timeout: 15_000,
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 5: Validation
  //
  // This screen has NO field-level validation by design (ui-spec "Validation Rules": every
  // dropdown option is valid, the sentinel is explicitly valid per VAL-B-02, OK always succeeds,
  // there is no error provider). VAL-B-01 (variant rendering) is pinned by the Category 2 render
  // tests; VAL-B-03 (initial selection) by the Category 3 data-wiring tests. The
  // setProjectDefaultKeyboard error path (notification + dialog stays open) cannot be induced
  // through visible UI against the real backend — it is covered by the web-view unit tests.
  // ═══════════════════════════════════════════════════════════════════════════

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 6: Edge Cases — focus, tab order, RTL, console hygiene
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-007 (gm-010 / FN-009 initial focus on the first ENABLED content control)
  test.fixme(
    'should place initial focus on the text-keyboard dropdown for a standard project',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      // Focus lands on the first enabled interactive CONTENT control (PT9 fix: NOT the OK
      // button) once enumeration resolves.
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toBeFocused({
        timeout: 10_000,
      });
    },
  );

  // @scenario TS-007 (tab order follows visual reading order — FIX from PT9's TabIndex 0=OK)
  test.fixme(
    'should tab through controls in reading order: text → notes → OK → Cancel',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      // Start from the initially-focused text dropdown (FN-009).
      await expect(frame.getByTestId('keyboard-selection-text-keyboard')).toBeFocused();

      await mainPage.keyboard.press('Tab');
      await expect(frame.getByTestId('keyboard-selection-notes-keyboard')).toBeFocused();

      await mainPage.keyboard.press('Tab');
      await expect(frame.getByRole('button', { name: /^OK$/i })).toBeFocused();

      await mainPage.keyboard.press('Tab');
      await expect(frame.getByRole('button', { name: /Cancel/i })).toBeFocused();
    },
  );

  // @scenario TS-010 (gm-005 / FN-012 RTL keyboard names render with per-item bidi isolation)
  test.fixme(
    'should render RTL keyboard names with per-item bidi isolation',
    async ({ mainPage }) => {
      await waitForAppReady(mainPage);
      const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
      await waitForKeyboardsSettled(frame);

      const realKeyboardCount = await openTextDropdownAndCountRealKeyboards(frame);
      // RTL-script detector: any strongly-RTL character (Hebrew / Arabic blocks).
      const optionTexts = await frame.locator('[role="option"]').allInnerTexts();
      const hasRtlName = optionTexts.some((text) => /[֐-ࣿ]/.test(text));
      test.skip(
        realKeyboardCount === 0 || !hasRtlName,
        'Requires an OS-enumerated keyboard with an RTL-script name (e.g., Arabic "العربية" via ' +
          'IBus) — not available on this host. The RTL variant is pinned by the Storybook RTL ' +
          'story (LTR + RTL captures per FN-012).',
      );

      // Each OS-supplied name is wrapped in a bidi-isolating element (<bdi> per the component
      // contract) so an RTL name renders with its own base direction inside the list.
      const rtlOption = frame.locator('[role="option"]').filter({ hasText: /[֐-ࣿ]/ }).first();
      await expect(rtlOption.locator('bdi')).toHaveCount(1);

      // EVD-008: RTL keyboard name rendered in the open dropdown.
      await mainPage.screenshot({ path: `${SCREENSHOT_BASE}/EVD-008-rtl-keyboard-names.png` });

      // Selecting it: the COLLAPSED display also renders with proper bidi isolation.
      await rtlOption.click();
      await expect(
        frame.getByTestId('keyboard-selection-text-keyboard').locator('bdi'),
      ).toHaveCount(1);
    },
  );

  // @scenario TS-007 (acceptance criterion: no console errors / missing-loc-key warnings when
  // rendered against the real papi.keyboard and real localizedStrings.json)
  test.fixme('should open and render without console errors', async ({ mainPage }) => {
    await waitForAppReady(mainPage);

    const consoleErrors: string[] = [];
    mainPage.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });

    const frame = await openKeyboardDialog(mainPage, STANDARD_PROJECT);
    await waitForKeyboardsSettled(frame);

    const criticalErrors = consoleErrors.filter(
      (e) =>
        !e.includes('DevTools') &&
        !e.includes('favicon') &&
        !e.includes('source map') &&
        !e.includes('net::ERR_'),
    );
    expect(criticalErrors).toHaveLength(0);
  });
});
