/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript. DO NOT MODIFY IT BY HAND.
 * Instead, modify the source JSONSchema file, and run json-schema-to-typescript to regenerate this
 * file.
 */

/**
 * Things changed in the schema:
 *
 * 1. Added "allOf": [ { "$ref": "#/$defs/multiColumnMenu" } ] where multiColumnMenu is used because
 *    otherwise it generates multiple of them. Did the same for singleColumnMenu
 * 2. Added tsType property for LocalizeKey and ReferencedItem because they use pattern and those types
 *    were generated as string
 *
 * Things changed in the types manually:
 *
 * 1. Changed types that are referenced via patternProperties to their respective type- LocalizeKey or
 *    ReferencedItem
 */

/** Identifier for a string that will be localized in a menu based on the user's UI language */
export type LocalizeKey = `%${string}%`;

/** Name of some UI element (i.e., tab, column, group, menu item) or some PAPI object (i.e., command) */
export type ReferencedItem = `${string}.${string}`;

/** Menu that can contain multiple columns with headers */
export type MultiColumnMenu = GroupsAndItems & {
  columns: ColumnsWithHeaders;
  [k: string]: unknown;
};
/** Single item in a menu that can be clicked on to take an action or can be the parent of a submenu */
export type MenuItem = {
  /** Key that represents the text of this menu item to display */
  label: LocalizeKey;
  /** Key that represents the text to display if a mouse pointer hovers over the menu item */
  tooltip?: LocalizeKey;
  /**
   * Key that represents additional words the platform should reference when users are searching for
   * menu items
   */
  searchTerms?: LocalizeKey;
  /** Additional information provided by developers to help people who perform localization */
  localizeNotes?: string;
  /** Group to which this menu item belongs */
  group: ReferencedItem;
  /**
   * Relative order of this menu item compared to other menu items in the same group (sorted
   * ascending)
   */
  order: number;
  [k: string]: unknown;
} & MenuItem1;
export type MenuItem1 =
  | {
      /** ID for this menu item that holds a submenu */
      id: ReferencedItem;
      [k: string]: unknown;
    }
  | {
      /** Name of the PAPI command to run when this menu item is selected. */
      command: ReferencedItem;
      /** Path to the icon to display on the left side of the menu text */
      iconPathBefore?: string;
      /** Path to the icon to display on the right side of the menu text */
      iconPathAfter?: string;
      [k: string]: unknown;
    };
/** Menu that contains a column without a header */
export type SingleColumnMenu = GroupsAndItems;

export interface PlatformBibleMenus {
  /** Top level menu for the application */
  mainMenu?: MultiColumnMenu;
  /** Default top menu for web views that don't specify their own */
  defaultWebViewTopMenu?: MultiColumnMenu;
  /** Default context menu for web views that don't specify their own */
  defaultWebViewContextMenu?: SingleColumnMenu;
  /** Menus that apply per web view in the application */
  webViewMenus?: {
    [k: ReferencedItem]: MenusForOneWebView;
  };
}
/** Core schema for a column */
export interface GroupsAndItems {
  groups: MenuGroups;
  /** List of menu items that belong in this menu */
  items: MenuItem[];
  [k: string]: unknown;
}
/** Groups that belong in this menu */
export interface MenuGroups {
  /**
   * Single group that contains menu items
   *
   * This interface was referenced by `MenuGroups`'s JSON-Schema definition via the
   * `patternProperty` "^[\w-]+.[\w-]+$".
   */
  [k: ReferencedItem]:
    | {
        /** Column where this group belongs, not required for single column menus */
        column?: ReferencedItem;
        /**
         * Relative order of this group compared to other groups in the same column or submenu
         * (sorted ascending)
         */
        order: number;
        /** Defines whether contributions are allowed to add menu items to this menu group */
        isExtensible?: boolean;
      }
    | {
        /** Menu item that anchors the submenu where this group belongs */
        menuItem: ReferencedItem;
        /**
         * Relative order of this group compared to other groups in the same column or submenu
         * (sorted ascending)
         */
        order: number;
        /** Defines whether contributions are allowed to add menu items to this menu group */
        isExtensible?: boolean;
      };
}
/** Columns that belong in this menu */
export interface ColumnsWithHeaders {
  /** Defines whether contributions are allowed to add columns to this multi-column menu */
  isExtensible?: boolean;
  /**
   * Single column with a header string
   *
   * This interface was referenced by `ColumnsWithHeaders`'s JSON-Schema definition via the
   * `patternProperty` "^[\w-]+.[\w-]+$".
   */
  [k: ReferencedItem]: {
    /** Header text for this this column in the UI */
    label: LocalizeKey;
    /** Additional information provided by developers to help people who perform localization */
    localizeNotes?: string;
    /** Relative order of this column compared to other columns (sorted ascending) */
    order: number;
    /** Defines whether contributions are allowed to add menu groups to this column */
    isExtensible?: boolean;
  };
}
/**
 * Set of menus that are associated with a single tab
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition via the `patternProperty`
 * "^[\w-]+.[\w-]+$".
 */
export interface MenusForOneWebView {
  /** Indicates whether the platform default menus should be included for this webview */
  includeDefaults?: boolean;
  /** Menu that opens when you click on the top left corner of a tab */
  topMenu?: MultiColumnMenu;
  /** Menu that opens when you right click on the main body/area of a tab */
  contextMenu?: SingleColumnMenu;
}
