/**
 * Enhanced Resources — Cross-WP Journey Tests (RED phase)
 *
 * Generated by: e2e-test-writer mode=write
 *
 * These tests exercise flows that span 2+ work packages. All tests are `test.fixme` until each
 * participating WP has been implemented and the e2e-test-writer is re-run in `verify` mode.
 *
 * Rules (do NOT relax during verify):
 *
 * - Import only from '../../fixtures/cdp.fixture' — never papi.fixture
 * - Drive everything through visible UI (menu, button, keyboard) — no sendPapiCommand or direct
 *   JSON-RPC calls
 * - Selectors come from each WP's ui-spec Test Contract; do not invent new test ids during verify,
 *   request them from the component-builder
 *
 * Forward notes that shape these flows: FN-015 — BCV control wiring (toolbar BCV ↔ scroll group)
 * FN-016 — info-icon → guide-open command registration FN-017 — H/G display-mode controls live in
 * the hamburger menu FN-020 — EnhancedResourceWebView integrated state machine: word-overlay
 * propagation, tab-switch propagation, clear-filter FN-021 — Dictionary domain row → SDV
 * filtered-by-domain dialog FN-022 — Sense-level occurrences link with descriptive tooltip
 */
import { test, expect } from '../../fixtures/cdp.fixture';
import { waitForAppReady } from '../../fixtures/helpers';
import { closeAllNonHomeDockTabs } from './test-helpers';

// Per the Test Contract in every ER ui-spec, the main window iframe is
// titled "Enhanced Resource". The guide (UI-PKG-008) renders via the
// paranext-core overlay service Dialog, NOT as its own iframe — so guide
// selectors run on `mainPage`, while ER-window selectors run inside the
// "Enhanced Resource" iframe.
//
// Strategic plan UI-PKG-009 / RF-SP-010 (resolved): the menu entry lives
// in the main app `app.title` menu ("Platform.bible"). The localized label
// for the command is the canonical "Open Enhanced Resource" wording from
// PT9 (matching the legacy WindowCollection.OpenEnhancedResourceWindowFor
// entry point); revisit during verify if the registered label differs.
const APP_MENU_NAME = /Platform\.bible/i;
const OPEN_ER_MENU_NAME = /Open\s+Enhanced\s+Resource/i;

/**
 * Open the ER window from the app menu. Idempotent: if a tab already exists (a previous test left
 * it open), this still works because the menu entry is a "create or reuse" command per BHV-616.
 */
async function openEnhancedResource(mainPage: import('@playwright/test').Page) {
  const appMenu = mainPage.getByRole('menuitem', { name: APP_MENU_NAME });
  await appMenu.click();
  const openItem = mainPage.getByRole('menuitem', { name: OPEN_ER_MENU_NAME });
  await openItem.click();
  // Tab title may include the resource name; match loosely.
  const tab = mainPage.locator('.dock-tab', { hasText: /Enhanced Resource/i });
  await expect(tab).toBeVisible({ timeout: 15_000 });
  return tab;
}

test.describe('Enhanced Resources Journey Tests', () => {
  test.beforeEach(async ({ mainPage }) => {
    await waitForAppReady(mainPage);
    await closeAllNonHomeDockTabs(mainPage);
  });

  // ═══════════════════════════════════════════════════════════════
  // Happy Path Flows
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-001 (covers TS-043, TS-044, EVD-001)
  // WPs: UI-PKG-009 (menu/command) → UI-PKG-001 (window shell)
  test.fixme(
    'opens ER window from app menu and renders main shell with default state',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);

      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Scripture pane present (ui-spec-marble-form: data-testid er-scripture-pane)
      await expect(er.getByTestId('er-scripture-pane')).toBeVisible({ timeout: 15_000 });

      // All four research tabs are present, dictionary is the default-active tab
      // (ui-spec-marble-form Default State Wireframe; TS-058 default-active dictionary).
      await expect(er.getByRole('tab', { name: /Dictionary/i })).toHaveAttribute(
        'aria-selected',
        'true',
      );
      await expect(er.getByRole('tab', { name: /Encyclopedia/i })).toBeVisible();
      await expect(er.getByRole('tab', { name: /Media/i })).toBeVisible();
      await expect(er.getByRole('tab', { name: /Maps/i })).toBeVisible();

      // Dictionary tab has a populated entry list (UI-PKG-002 entryList testid).
      await expect(er.getByTestId('dictionary-entry-list')).toBeVisible();

      await mainPage.screenshot({
        path: 'proofs/component-evidence/journey/JEVD-001-er-default-shell.png',
      });
    },
  );

  // @scenario TS-J-002 (covers TS-044, BHV-616)
  // WPs: UI-PKG-009 (menu) → UI-PKG-001 (window reuse)
  test.fixme(
    'reuses existing ER tab when menu invoked again for same resource',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const initialTabCount = await mainPage
        .locator('.dock-tab', { hasText: /Enhanced Resource/i })
        .count();
      expect(initialTabCount).toBe(1);

      // Re-invoke the menu — should activate, not duplicate.
      await openEnhancedResource(mainPage);
      const finalTabCount = await mainPage
        .locator('.dock-tab', { hasText: /Enhanced Resource/i })
        .count();
      expect(finalTabCount).toBe(1);
    },
  );

  // ═══════════════════════════════════════════════════════════════
  // Cross-WP Data Flow — Word filter propagation (FN-020)
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-010 (covers FN-020 sub-task c, BHV-302, BHV-601, EVD-002, EVD-022)
  // WPs: UI-PKG-001 (scripture pane + lower toolbar filter) → UI-PKG-002 (DictionaryTab SLI filtering)
  test.fixme(
    'word click in scripture pane populates filter and filters dictionary tab',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Step 1 (UI-PKG-001): click a linked word in the scripture pane.
      // Linked words are rendered with role="link" inside the editor's
      // marble-aware annotation layer (FN-014). We click the first one.
      const firstLinkedWord = er.getByTestId('er-scripture-pane').getByRole('link').first();
      await firstLinkedWord.click();

      // Step 2 (UI-PKG-001): the lower-toolbar filter box appears with the
      // transliterated word, and the clear-filter X is now visible.
      const filterBox = er.getByTestId('er-filter-box');
      await expect(filterBox).toBeVisible();
      await expect(filterBox).not.toHaveText('');
      await expect(er.getByRole('button', { name: /Turn off word\/phrase filter/i })).toBeVisible();

      // Step 3 (UI-PKG-001 → UI-PKG-002): the active dictionary tab now
      // shows the entry detail open for the clicked word's lemma — i.e.,
      // SLI applied the filter AND opened the detail view (FN-020 (c)).
      const dictionaryList = er.getByTestId('dictionary-entry-list');
      await expect(dictionaryList).toBeVisible();
      // The clear-filter button being present here is the cheapest stable
      // assertion that the SLI is in filtered state — the entry list
      // collapses to (typically) a single matching entry.
      const dictionaryEntries = dictionaryList.locator('[data-testid^="dictionary-entry-"]');
      await expect(dictionaryEntries).not.toHaveCount(0);

      await mainPage.screenshot({
        path: 'proofs/component-evidence/journey/JEVD-010-word-click-filters-dict.png',
      });
    },
  );

  // @scenario TS-J-011 (covers FN-020 sub-task d, BHV-601)
  // WPs: UI-PKG-001 (filter state owner) → UI-PKG-002 → UI-PKG-003 → UI-PKG-004
  test.fixme(
    'word filter propagates across tab switches (Dictionary -> Encyclopedia -> Media)',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Establish filter from scripture pane (covered separately by TS-J-010,
      // re-asserted here as setup for the propagation check).
      await er.getByTestId('er-scripture-pane').getByRole('link').first().click();
      const filterBox = er.getByTestId('er-filter-box');
      await expect(filterBox).toBeVisible();
      const filterTextAfterClick = await filterBox.textContent();
      expect(filterTextAfterClick?.trim().length ?? 0).toBeGreaterThan(0);

      // Switch to Encyclopedia tab — same filter must remain active.
      await er.getByRole('tab', { name: /Encyclopedia/i }).click();
      await expect(er.getByTestId('encyclopedia-entry-list')).toBeVisible();
      await expect(filterBox).toHaveText(filterTextAfterClick ?? '');

      // Switch to Media tab — filter still active.
      await er.getByRole('tab', { name: /Media/i }).click();
      // Media tab renders thumbnail-variant SLI; tolerate either an entry
      // grid or the empty-state message (the filter may yield no images
      // for the test verse), but the filter box must still be populated.
      await expect(filterBox).toHaveText(filterTextAfterClick ?? '');

      await mainPage.screenshot({
        path: 'proofs/component-evidence/journey/JEVD-011-filter-propagates-across-tabs.png',
      });
    },
  );

  // @scenario TS-J-012 (covers FN-020 sub-task e, EVD-005)
  // WPs: UI-PKG-001 (clear filter button) → UI-PKG-002 (SLI clears + collapses detail)
  test.fixme(
    'clear-filter button clears toolbar filter and dictionary detail view',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Establish filter
      await er.getByTestId('er-scripture-pane').getByRole('link').first().click();
      const filterBox = er.getByTestId('er-filter-box');
      await expect(filterBox).toBeVisible();

      // Click clear-filter X
      await er.getByRole('button', { name: /Turn off word\/phrase filter/i }).click();

      // Filter box hidden (or empty), and the dictionary entry list is
      // back to unfiltered state (more entries than 1, or returns from the
      // single-entry detail to the full list).
      await expect(filterBox).toBeHidden();
      const dictionaryList = er.getByTestId('dictionary-entry-list');
      await expect(dictionaryList).toBeVisible();
    },
  );

  // ═══════════════════════════════════════════════════════════════
  // Cross-WP Data Flow — Scope dropdown (BHV-305, BHV-601)
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-020 (covers TS-048, BHV-305, BHV-601, EVD-003)
  // WPs: UI-PKG-001 (scope selector) → UI-PKG-002/003/004 (tabs reload)
  test.fixme('scope change propagates to research tabs', async ({ mainPage }) => {
    await openEnhancedResource(mainPage);
    const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

    // Capture default-scope dictionary entry count.
    const dictionaryList = er.getByTestId('dictionary-entry-list');
    await expect(dictionaryList).toBeVisible();
    const verseScopeCount = await dictionaryList
      .locator('[data-testid^="dictionary-entry-"]')
      .count();

    // Change scope from Current Verse → Current Chapter via the scope
    // selector (ui-spec-marble-form: combobox name "Verses filter").
    const scopeSelector = er.getByRole('combobox', { name: /Verses filter/i });
    await scopeSelector.click();
    await er.getByRole('option', { name: /Current Chapter/i }).click();

    // The dictionary list reloads — at chapter scope, the entry count
    // should be ≥ verse-scope count (chapter contains the verse).
    await expect(dictionaryList).toBeVisible();
    const chapterScopeCount = await dictionaryList
      .locator('[data-testid^="dictionary-entry-"]')
      .count();
    expect(chapterScopeCount).toBeGreaterThanOrEqual(verseScopeCount);

    await mainPage.screenshot({
      path: 'proofs/component-evidence/journey/JEVD-020-scope-change-propagates.png',
    });
  });

  // ═══════════════════════════════════════════════════════════════
  // Cross-WP Overlay Launch — Dictionary → SemanticDomainViewer
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-030 (covers FN-021, BHV-456, EVD-050)
  // WPs: UI-PKG-002 (DictionarySenseItem domain link) → UI-PKG-007 (SDV filtered)
  test.fixme(
    'clicking a dictionary domain row opens SemanticDomainViewer filtered by that domain',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Expand the first dictionary entry to surface the sense rows.
      const firstEntry = er
        .getByTestId('dictionary-entry-list')
        .locator('[data-testid^="dictionary-entry-"]')
        .first();
      await firstEntry.click();

      // Click the first Domain row. Per FN-021, the Domain value cell is
      // wrapped in a Button variant=link; we locate by its accessible row
      // label "Domain:" + a sibling link.
      const domainRow = firstEntry.getByRole('row', { name: /Domain:?/i }).first();
      const domainLink = domainRow.getByRole('link').first();
      await domainLink.click();

      // SemanticDomainViewer opens (overlay Drawer/Dialog inside the same
      // iframe). Per ui-spec-semantic-domain-viewer Test Contract:
      //   - role="navigation" breadcrumb, role="tree" container
      //   - the dictionary entries pane rendered via SLI
      await expect(er.getByRole('navigation')).toBeVisible();
      await expect(er.getByRole('tree')).toBeVisible();

      // The breadcrumb shows the path to the clicked domain — i.e., it
      // contains text (we don't assert exact path because that depends on
      // backend data; we only assert the cross-component handoff worked).
      const breadcrumbItems = er.getByRole('navigation').getByRole('listitem');
      await expect(breadcrumbItems.first()).toBeVisible();

      await mainPage.screenshot({
        path: 'proofs/component-evidence/journey/JEVD-030-domain-row-opens-sdv.png',
      });
    },
  );

  // ═══════════════════════════════════════════════════════════════
  // Cross-WP Overlay Launch — Encyclopedia → ArticleViewer
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-040 (covers TS-064, BHV-457, EVD-032, EVD-060)
  // WPs: UI-PKG-003 (encyclopedia entry list) → UI-PKG-006 (ArticleViewer)
  test.fixme(
    'clicking an encyclopedia article title opens ArticleViewer with article content',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Switch to Encyclopedia tab.
      await er.getByRole('tab', { name: /Encyclopedia/i }).click();
      const encyclopediaList = er.getByTestId('encyclopedia-entry-list');
      await expect(encyclopediaList).toBeVisible();

      // Click the first article title link. Per ui-spec-encyclopedia-tab
      // Test Contract, articleLink uses role=link inside an entry row.
      const firstArticleLink = encyclopediaList
        .locator('[data-testid^="encyclopedia-entry-"]')
        .first()
        .getByRole('link')
        .first();
      await firstArticleLink.click();

      // ArticleViewer drawer opens with rendered article content
      // (ui-spec-article-viewer: data-testid article-viewer-content).
      const articleContent = er.getByTestId('article-viewer-content');
      await expect(articleContent).toBeVisible();
      // Article must have actual content (more than the loading skeleton).
      const articleText = await articleContent.textContent();
      expect((articleText ?? '').trim().length).toBeGreaterThan(0);

      await mainPage.screenshot({
        path: 'proofs/component-evidence/journey/JEVD-040-encyclopedia-opens-article-viewer.png',
      });
    },
  );

  // @scenario TS-J-041 (covers BHV-457, EVD-061)
  // WPs: UI-PKG-006 (ArticleViewer verse link) → UI-PKG-001 (scripture pane navigates)
  test.fixme(
    'clicking a verse link in ArticleViewer navigates the scripture pane',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Open an article (setup — same as TS-J-040)
      await er.getByRole('tab', { name: /Encyclopedia/i }).click();
      const encyclopediaList = er.getByTestId('encyclopedia-entry-list');
      await expect(encyclopediaList).toBeVisible();
      await encyclopediaList
        .locator('[data-testid^="encyclopedia-entry-"]')
        .first()
        .getByRole('link')
        .first()
        .click();

      const articleContent = er.getByTestId('article-viewer-content');
      await expect(articleContent).toBeVisible();

      // Click the first verse-reference link inside the article. Per
      // ui-spec-article-viewer, verseLink uses data-testid="verse-link-{ref}".
      const verseLink = articleContent.locator('[data-testid^="verse-link-"]').first();
      const verseRefAttr = await verseLink.getAttribute('data-testid');
      expect(verseRefAttr).toMatch(/^verse-link-/);
      await verseLink.click();

      // Scripture pane should now reflect the navigated reference. The
      // simplest cross-WP assertion is that the BCV reference label in the
      // upper toolbar updates to a non-empty value (FN-015 wires this).
      // The exact selector here matches the BCV slot once FN-015 is wired;
      // if reconciliation finds a different slot during verify, update.
      const scripturePane = er.getByTestId('er-scripture-pane');
      await expect(scripturePane).toBeVisible();
    },
  );

  // ═══════════════════════════════════════════════════════════════
  // Cross-WP Overlay Launch — Media tab → MediaViewer
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-050 (covers TS-062, EVD-040)
  // WPs: UI-PKG-004 (MediaImagesTab thumbnails) → UI-PKG-005 (MediaViewer)
  test.fixme(
    'clicking a media thumbnail opens MediaViewer with image and controls',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Switch to Media tab — UI-PKG-004 deferred-loading: thumbnails only
      // render once tab is visible (BHV-359).
      await er.getByRole('tab', { name: /Media/i }).click();

      // Click the first thumbnail. Media entry rows are rendered through
      // ResourceList (thumbnail variant); the role of the thumbnail is button.
      const thumbnails = er.locator('[data-testid^="media-entry-"]');
      // Skip if the test verse has no media — this is acceptable for a
      // first-pass journey but during verify the test data should be chosen
      // to ensure at least one media entry exists.
      if ((await thumbnails.count()) === 0) {
        test.skip(
          true,
          'No media entries for the default ER reference; choose a verse with media for verify.',
        );
        return;
      }
      await thumbnails.first().click();

      // MediaViewer opens with the image, title, prev/next/zoom controls.
      await expect(er.getByTestId('media-viewer-image')).toBeVisible();
      await expect(er.getByTestId('media-viewer-zoom-in')).toBeVisible();
      await expect(er.getByTestId('media-viewer-zoom-out')).toBeVisible();

      await mainPage.screenshot({
        path: 'proofs/component-evidence/journey/JEVD-050-media-thumbnail-opens-viewer.png',
      });
    },
  );

  // ═══════════════════════════════════════════════════════════════
  // Info-icon → MarbleGuideForm (FN-016)
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-060 (covers TS-065, FN-016, BHV-461, EVD-011)
  // WPs: UI-PKG-001 (info button + command) → UI-PKG-008 (Guide dialog)
  test.fixme('clicking the info icon toggles MarbleGuideForm visibility', async ({ mainPage }) => {
    await openEnhancedResource(mainPage);
    const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

    // Defensive: if the guide auto-opened on first ER open this session
    // (TS-065), close it first so we test the explicit toggle path.
    const initialGuide = mainPage.getByTestId('marble-guide');
    if (await initialGuide.isVisible().catch(() => false)) {
      await mainPage.getByTestId('marble-guide-close').click();
      await expect(initialGuide).toBeHidden();
    }

    // Click info icon in upper toolbar.
    await er.getByRole('button', { name: /Show\/Hide Enhanced Resource Guide/i }).click();

    // Per ui-spec-marble-guide-form: guide is rendered via paranext-core
    // overlay service Dialog (app-wide, NOT inside the ER iframe). Use
    // the existing testid from the implemented MarbleGuide component.
    const guide = mainPage.getByTestId('marble-guide');
    await expect(guide).toBeVisible({ timeout: 10_000 });
    await expect(mainPage.getByTestId('marble-guide-content')).toBeVisible();

    // Toggle off
    await er.getByRole('button', { name: /Show\/Hide Enhanced Resource Guide/i }).click();
    await expect(guide).toBeHidden();

    await mainPage.screenshot({
      path: 'proofs/component-evidence/journey/JEVD-060-info-icon-toggles-guide.png',
    });
  });

  // @scenario TS-J-061 (covers TS-066, BHV-461, BHV-465, EVD-012)
  // WPs: UI-PKG-008 (Guide checkbox + persistence) → UI-PKG-009 (relaunch path)
  test.fixme(
    '"Don\'t show this again" persists across relaunch of ER window',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Open the guide via info icon
      await er.getByRole('button', { name: /Show\/Hide Enhanced Resource Guide/i }).click();
      const guide = mainPage.getByTestId('marble-guide');
      await expect(guide).toBeVisible();

      // Check "Don't show this again" then close
      await mainPage.getByTestId('marble-guide-never-show-again').check();
      await mainPage.getByTestId('marble-guide-close').click();
      await expect(guide).toBeHidden();

      // Close ER tab and reopen — guide must NOT auto-show.
      await mainPage
        .locator('.dock-tab', { hasText: /Enhanced Resource/i })
        .locator('.dock-tab-close-btn')
        .first()
        .dispatchEvent('click');
      await mainPage.waitForTimeout(500);
      await openEnhancedResource(mainPage);

      // After short settle window, guide should still be hidden.
      await mainPage.waitForTimeout(1500);
      await expect(mainPage.getByTestId('marble-guide')).toBeHidden();
    },
  );

  // ═══════════════════════════════════════════════════════════════
  // Hamburger menu → Display modes (FN-017, FN-020 sub-task b)
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-070 (covers FN-017, FN-020 (b), BHV-319, EVD-004)
  // WPs: UI-PKG-001 (hamburger menu + ScripturePane reactivity)
  test.fixme(
    'toggling "Show footnotes" in hamburger menu shows the footnote pane',
    async ({ mainPage }) => {
      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Open hamburger (TabMenu Button) in upper toolbar.
      const hamburger = er.getByRole('button', { name: /Menu|More options|Hamburger/i }).first();
      await hamburger.click();

      // Click the "Show footnotes" menu item (toggle).
      await er.getByRole('menuitem', { name: /Show footnotes/i }).click();

      // Footnote pane (ui-spec-marble-form: data-testid er-footnotes-pane)
      // becomes visible.
      await expect(er.getByTestId('er-footnotes-pane')).toBeVisible();

      await mainPage.screenshot({
        path: 'proofs/component-evidence/journey/JEVD-070-footnotes-toggled.png',
      });
    },
  );

  // ═══════════════════════════════════════════════════════════════
  // Smoke: cross-component render without console errors
  // ═══════════════════════════════════════════════════════════════

  // @scenario TS-J-080 (covers EVD-001 + EVD-020 + EVD-030 cross-render smoke)
  // WPs: UI-PKG-001 + UI-PKG-002 + UI-PKG-003 + UI-PKG-004 (all tabs render together)
  test.fixme(
    'switching across all four research tabs renders without console errors',
    async ({ mainPage }) => {
      const consoleErrors: string[] = [];
      mainPage.on('console', (msg) => {
        if (msg.type() === 'error') consoleErrors.push(msg.text());
      });

      await openEnhancedResource(mainPage);
      const er = mainPage.frameLocator(`iframe[title*="Enhanced Resource"]`);

      // Visit each tab and let it settle. Sequential by intent — each tab
      // must finish settling before the next click — so we await inside
      // reduce(). Using `reduce` instead of a for-of loop satisfies the
      // project's no-restricted-syntax rule.
      const tabNames = ['Dictionary', 'Encyclopedia', 'Media', 'Maps'] as const;
      await tabNames.reduce<Promise<void>>(async (prev, tabName) => {
        await prev;
        await er.getByRole('tab', { name: new RegExp(tabName, 'i') }).click();
        await mainPage.waitForTimeout(750);
      }, Promise.resolve());

      const criticalErrors = consoleErrors.filter(
        (e) =>
          !e.includes('DevTools') &&
          !e.includes('favicon') &&
          !e.includes('source map') &&
          !e.includes('net::ERR_'),
      );
      expect(criticalErrors).toEqual([]);
    },
  );
});
