import { test, expect } from '../../fixtures/cdp.fixture';
import { waitForAppReady } from '../../fixtures/helpers';
import { closeAllNonHomeDockTabs, openEnhancedResource } from './test-helpers';

// Feature: enhanced-resources
// Work Package: UI-PKG-002: DictionaryTab (Research Pane)
// Generated by: ui-test-writer (RED phase — all tests use test.fixme)
//
// Source artifacts:
//   ui-spec: ui-specifications/ui-spec-dictionary-tab.md (Test Contract)
//   state contract: ui-specifications/ui-state-contracts.md § DictionaryTab
//   scenarios: TS-056, TS-057, TS-058, TS-059, TS-060, TS-069, TS-070 (+ TS-051 edge case)
//   behaviors: BHV-352, BHV-353, BHV-354, BHV-601, BHV-615
//   forward notes (in-scope for this WP): FN-018, FN-019, FN-020 (c+d+e), FN-021, FN-022
//
// Selector strategy:
//   - Top window navigation uses platform-bible main menu (visible UI only).
//   - Webview frame title is the localized %enhancedResources_shell_title% — test matches loosely.
//   - data-testid values mirror the storybook-designer output already on disk:
//       dictionary-tab, dictionary-entry-{tokenId}, dictionary-entry-detail-{tokenId},
//       dictionary-entry-detail-source-{tokenId}, dictionary-entry-detail-all-occurrences-{tokenId},
//       dictionary-entry-detail-give-feedback-{tokenId}, dictionary-sense-{senseId},
//       dictionary-sense-occurrences-{senseId}.
//   - Tab triggers use role=tab + aria-label (localized "Dictionary"/"Encyclopedia"/etc.).

test.describe('Enhanced Resources Functional Tests (UI-PKG-002 DictionaryTab)', () => {
  test.beforeEach(async ({ mainPage }) => {
    await closeAllNonHomeDockTabs(mainPage);
  });

  /**
   * Helper: open the Enhanced Resource window via the platform main menu and switch to the
   * Dictionary tab inside the webview. Returns the FrameLocator scoped to the webview iframe.
   *
   * The launcher menu (UI-PKG-009) registers an entry under the `Resources` (or equivalent) main
   * menu group; final label is whatever ER ships with — implementation pass adjusts the regex below
   * to match the registered command name.
   */
  async function openDictionaryTab(mainPage: import('@playwright/test').Page) {
    await openEnhancedResource(mainPage);
    const frame = mainPage.frameLocator('iframe[title="Enhanced Resource"]');
    // Lower-toolbar tab trigger; aria-label is the localized "Dictionary" string.
    await frame.getByRole('tab', { name: /Dictionary/i }).click();
    // Confirm the tab body mounted.
    await expect(frame.getByTestId('dictionary-tab')).toBeVisible({ timeout: 10_000 });
    return frame;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 1: Navigation
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-060
  // BHV-354 (BeforeNavigate URL Routing — entry into the tab via main menu navigation)
  test('should reach DictionaryTab through the Enhanced Resource window menu', async ({
    mainPage,
  }) => {
    await waitForAppReady(mainPage);

    // Step 1: Open the menu group that hosts the Enhanced Resource launcher (UI-PKG-009).
    await mainPage.getByRole('menuitem', { name: /^Platform$/i }).click();
    // EVD-020 (pre): menu opened with launcher visible.
    await mainPage.screenshot({
      path: 'proofs/component-evidence/UI-PKG-002/EVD-020a-menu-open.png',
    });
    await mainPage.keyboard.press('Escape');

    // Step 2 & 3: Open ER (helper handles menu navigation + auto-show guide dismissal).
    await openEnhancedResource(mainPage);

    // Step 4: Switch to the Dictionary tab via visible UI (lower toolbar tabs).
    const frame = mainPage.frameLocator('iframe[title*="Enhanced Resource"]');
    await frame.getByRole('tab', { name: /Dictionary/i }).click();

    // Step 5: Dictionary tab body is visible.
    await expect(frame.getByTestId('dictionary-tab')).toBeVisible({ timeout: 10_000 });

    // EVD-020: Dictionary tab active with header visible.
    await mainPage.screenshot({
      path: 'proofs/component-evidence/UI-PKG-002/EVD-020-tab-active.png',
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 2: Render
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-060, TS-069
  // BHV-353/-354/-364 (DictionaryTab structure + dictionary label visible)
  test('should render the Dictionary tab structural elements', async ({ mainPage }) => {
    const frame = await openDictionaryTab(mainPage);

    // Tab container present.
    const tab = frame.getByTestId('dictionary-tab');
    await expect(tab).toBeVisible();

    // Dictionary label header (SDBH for OT default per BHV-364 / TS-069).
    // Header is announced as the tab's aria-label and rendered as visible UPPERCASE text.
    const tabAriaLabel = await tab.getAttribute('aria-label');
    expect(tabAriaLabel).toMatch(/SDBH|SDBG|Dictionary/i);

    // The SourceLanguageIndexedList scroll region is the entry list.
    // (Used by spec § Test Contract row "entryList".)
    const entryList = tab.getByRole('listbox').or(tab.locator('[role="list"]'));
    await expect(entryList.first()).toBeVisible();

    // EVD-020: dictionary tab fully rendered.
    await mainPage.screenshot({
      path: 'proofs/component-evidence/UI-PKG-002/EVD-020-window-loaded.png',
    });
  });

  // @scenario TS-069
  // BHV-353/-364 — SDBH dictionary selected for OT books
  test('should display the SDBH dictionary label when navigated to an OT book', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    // The webview is opened against the platform's current scroll-group reference. By default
    // the test profile starts in Genesis (OT) so SDBH is expected. Component-builder phase will
    // wire `useWebViewScrollGroupScrRef` (FN-015) to seed this.
    const dictionaryTab = frame.getByTestId('dictionary-tab');
    const ariaLabel = await dictionaryTab.getAttribute('aria-label');
    expect(ariaLabel).toMatch(/SDBH/i);
  });

  // FIXME(GAP-bcv-control-wiring): BCV combobox to switch reference is not yet wired (FN-015).
  // @scenario TS-070
  // BHV-353/-364 — SDBG dictionary selected for NT/DC books
  test.fixme(
    'should display the SDBG dictionary label when navigated to an NT book',
    async ({ mainPage }) => {
      const frame = await openDictionaryTab(mainPage);

      // Component-builder phase will provide a way to switch the scroll-group reference via
      // visible UI (BCV control wired per FN-015). Until then the assertion documents the
      // expected behavior — switching to John must update the dictionary label to SDBG.
      // Switch reference to a NT book (e.g., John 1:1) through the webview's BCV control.
      // The exact selector depends on FN-015's BCV wiring; placeholder uses role+name.
      const bcv = frame.getByRole('combobox', { name: /Reference|Book/i });
      await bcv.click();
      await frame.getByRole('option', { name: /John/i }).first().click();

      const dictionaryTab = frame.getByTestId('dictionary-tab');
      // The aria-label must update to reflect SDBG once data loads.
      await expect(dictionaryTab).toHaveAttribute('aria-label', /SDBG/i, { timeout: 10_000 });
    },
  );

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 3: Data Wiring
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-060, TS-069
  // BHV-601 (Scope-Based Link Filtering — entries reflect current scope)
  // BHV-615 (POS translation — translated POS visible on detail rows)
  test('should populate dictionary entries from backend for current scope', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    // At least one entry row must appear (default scope = current verse, default ref = Gen 1:1
    // which has multiple linked words — TS-069 / BHV-601). Entries are addressed by tokenId via
    // data-testid="dictionary-entry-{tokenId}".
    const anyEntryRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
    await expect(anyEntryRow).toBeVisible({ timeout: 15_000 });

    // The entry row's source-language word is non-empty (real lemma text from backend).
    const sourceText = await anyEntryRow.locator('button[aria-label]').first().innerText();
    expect(sourceText.trim().length).toBeGreaterThan(0);

    // Open the detail panel by clicking the row body (single-select expansion).
    await anyEntryRow.click();

    // Detail panel must mount with at least one sense; sense IDs come from backend
    // (DictionaryEntryData via M-006 readDictionaryEntry).
    const detail = frame.locator('[data-testid^="dictionary-entry-detail-"]').first();
    await expect(detail).toBeVisible({ timeout: 10_000 });
    const senseRow = detail.locator('[data-testid^="dictionary-sense-"]').first();
    await expect(senseRow).toBeVisible();

    // Sense definition text non-empty.
    const senseDefinition = await senseRow.innerText();
    expect(senseDefinition.trim().length).toBeGreaterThan(0);

    // EVD-021: expanded entry detail with senses visible.
    await mainPage.screenshot({
      path: 'proofs/component-evidence/UI-PKG-002/EVD-021-entry-expanded.png',
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 4: Interaction
  // ═══════════════════════════════════════════════════════════════════════════

  // @scenario TS-060
  // BHV-354 — clicking source word filters MarbleForm + opens detail (FN-020 c)
  test('clicking a source-language word should filter MarbleForm to that word', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    // Click the source-text button on the first entry row.
    const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
    await expect(firstRow).toBeVisible({ timeout: 15_000 });
    const sourceWordBtn = firstRow.locator('button[aria-label]').first();
    const lemma = (await sourceWordBtn.innerText()).trim();
    expect(lemma.length).toBeGreaterThan(0);

    await sourceWordBtn.click();

    // The lower-toolbar filter input (search bar) must reflect the clicked lemma. The filter
    // input lives in the EnhancedResourceTabBar (UI-PKG-001) — selector by role=searchbox or
    // textbox with the localized "Filter" placeholder.
    const filterInput = frame
      .getByRole('searchbox')
      .or(frame.getByRole('textbox', { name: /Filter|Search/i }));
    await expect(filterInput.first()).toHaveValue(new RegExp(lemma, 'i'), { timeout: 5_000 });

    // EVD-022: filter applied — only matching entries visible.
    await mainPage.screenshot({
      path: 'proofs/component-evidence/UI-PKG-002/EVD-022-filter-applied.png',
    });
  });

  // @scenario TS-060
  // BHV-354 — entry-level "Occurrences in all books" link routes to MarbleForm reference change
  test('clicking entry-level all-occurrences link should navigate MarbleForm', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    // Open detail panel for first entry.
    const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
    await expect(firstRow).toBeVisible({ timeout: 15_000 });
    await firstRow.click();

    const detail = frame.locator('[data-testid^="dictionary-entry-detail-"]').first();
    await expect(detail).toBeVisible({ timeout: 10_000 });

    const allOccLink = detail.locator('[data-testid^="dictionary-entry-detail-all-occurrences-"]');
    await expect(allOccLink).toBeVisible();

    // The link label includes the total count, e.g. "Occurrences in all books (24)".
    const linkText = await allOccLink.innerText();
    expect(linkText).toMatch(/\d+/); // contains a number (count)

    // Clicking it triggers a navigation through onAllOccurrencesClick — verified by the
    // BCV/reference indicator updating. The MarbleForm reference indicator selector is
    // owned by UI-PKG-001 — assert generic visibility of detail closing or filter dropping.
    await allOccLink.click();
    // Expect we have navigated (detail panel may or may not stay; key invariant is no error
    // banner appeared).
    await expect(detail).toBeVisible({ timeout: 5_000 });
  });

  // @scenario TS-060
  // BHV-354 / FN-022 — sense-level occurrences (number-only label + tooltip)
  test('sense-level occurrences link should show count-only with descriptive tooltip', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
    await expect(firstRow).toBeVisible({ timeout: 15_000 });
    await firstRow.click();

    const detail = frame.locator('[data-testid^="dictionary-entry-detail-"]').first();
    await expect(detail).toBeVisible({ timeout: 10_000 });

    const senseOccLink = detail.locator('[data-testid^="dictionary-sense-occurrences-"]').first();
    await expect(senseOccLink).toBeVisible();

    // FN-022: visible label is "(N)" — number only, wrapped in parentheses.
    const linkText = (await senseOccLink.innerText()).trim();
    expect(linkText).toMatch(/^\(\d+\)$/);

    // FN-022: hover tooltip text matches "Find sense {n} of {lexeme} in all books ({x} occurrences)".
    await senseOccLink.hover();
    const tooltip = frame.getByRole('tooltip');
    await expect(tooltip).toBeVisible();
    const tooltipText = await tooltip.innerText();
    expect(tooltipText).toMatch(/Find sense \d+ of .+ in all books \(\d+ occurrences\)/i);
  });

  // FIXME(GAP-context-menu-wiring): Editorial's onClick fires on left-click only; right-click context menu requires upstream Editorial change or DOM-level delegation.
  // @scenario TS-058
  // BHV-353 — Right-click + Copy surface form (Original / Hebrew script for OT books)
  test.fixme(
    'right-click on Hebrew entry should expose Copy surface form > Original script',
    async ({ mainPage }) => {
      const frame = await openDictionaryTab(mainPage);

      const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
      await expect(firstRow).toBeVisible({ timeout: 15_000 });
      await firstRow.click({ button: 'right' });

      // EVD-024: context menu visible with Copy surface form / Copy lemma items.
      await mainPage.screenshot({
        path: 'proofs/component-evidence/UI-PKG-002/EVD-024-context-menu.png',
      });

      // Top-level context-menu items (per dictionary-display-item.component.tsx):
      //   Copy surface form > [Original / Transliteration]
      //   Copy lemma > [Original / Transliteration]
      //   Find sense / Find lemma / Find text
      const copySurfaceForm = frame.getByRole('menuitem', { name: /Copy surface form/i });
      await expect(copySurfaceForm).toBeVisible();

      // Hover to expose the sub-menu, then click the Original-script entry.
      await copySurfaceForm.hover();
      const originalItem = frame.getByRole('menuitem', { name: /Original|Hebrew|Greek/i }).first();
      await expect(originalItem).toBeVisible();
      await originalItem.click();

      // Verify clipboard contains the surface form (JSDOM-style read; CDP grants permission via
      // the renderer context). If the harness denies clipboard reads, fall back to checking that
      // the menu closed without error.
      const clipboard = await mainPage
        .evaluate(() => navigator.clipboard.readText())
        .catch(() => '');
      // Source form is non-empty — exact value comes from real Marble data.
      if (clipboard) expect(clipboard.trim().length).toBeGreaterThan(0);
    },
  );

  // FIXME(GAP-context-menu-wiring): Editorial's onClick fires on left-click only; right-click context menu requires upstream Editorial change or DOM-level delegation. Also depends on GAP-bcv-control-wiring.
  // @scenario TS-059
  // BHV-353 — Right-click + Copy lemma (Greek lemma + transliteration for NT books)
  test.fixme(
    'right-click on Greek entry should expose Copy lemma > Original / Transliteration',
    async ({ mainPage }) => {
      const frame = await openDictionaryTab(mainPage);

      // Switch reference to a NT book to ensure Greek lemmas (TS-059 = JHN). FN-015 wires BCV.
      const bcv = frame.getByRole('combobox', { name: /Reference|Book/i });
      await bcv.click();
      await frame.getByRole('option', { name: /John/i }).first().click();

      // Wait for SDBG entries to load.
      const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
      await expect(firstRow).toBeVisible({ timeout: 15_000 });

      await firstRow.click({ button: 'right' });

      const copyLemma = frame.getByRole('menuitem', { name: /Copy lemma/i });
      await expect(copyLemma).toBeVisible();
      await copyLemma.hover();

      // Sub-menu shows two options.
      const subOriginal = frame.getByRole('menuitem', { name: /Original|Greek/i }).first();
      const subTranslit = frame.getByRole('menuitem', { name: /Transliteration/i }).first();
      await expect(subOriginal).toBeVisible();
      await expect(subTranslit).toBeVisible();

      // Click Transliteration variant to verify both branches register.
      await subTranslit.click();
    },
  );

  // @scenario TS-060 (cross-component propagation)
  // FN-020 (d) — switching tabs propagates the active filter to the new tab's SLI
  test('switching tabs after a word click should retain the word filter on the new tab', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    // Click a source word in the dictionary tab to set the filter.
    const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
    await expect(firstRow).toBeVisible({ timeout: 15_000 });
    const sourceWordBtn = firstRow.locator('button[aria-label]').first();
    const lemma = (await sourceWordBtn.innerText()).trim();
    await sourceWordBtn.click();

    // Switch to Encyclopedia tab. The same lemma must be applied to its filter input.
    await frame.getByRole('tab', { name: /Encyclopedia/i }).click();

    const filterInput = frame
      .getByRole('searchbox')
      .or(frame.getByRole('textbox', { name: /Filter|Search/i }));
    await expect(filterInput.first()).toHaveValue(new RegExp(lemma, 'i'), { timeout: 5_000 });

    // Return to Dictionary; filter still applied (filtered list visible).
    await frame.getByRole('tab', { name: /Dictionary/i }).click();
    await expect(frame.getByTestId('dictionary-tab')).toBeVisible();
    await expect(filterInput.first()).toHaveValue(new RegExp(lemma, 'i'));
  });

  // @scenario TS-060
  // FN-020 (e) — clear-filter button clears input and dismisses any open detail
  test('clearing the filter should reset the dictionary list and hide the open detail', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
    await expect(firstRow).toBeVisible({ timeout: 15_000 });
    await firstRow.locator('button[aria-label]').first().click();

    // Detail open after click.
    const detail = frame.locator('[data-testid^="dictionary-entry-detail-"]').first();
    await expect(detail).toBeVisible({ timeout: 10_000 });

    // Clear filter via the X button on the search input.
    const filterInput = frame
      .getByRole('searchbox')
      .or(frame.getByRole('textbox', { name: /Filter|Search/i }));
    const clearBtn = frame.getByRole('button', { name: /Clear filter|Clear/i });
    await clearBtn.click();

    await expect(filterInput.first()).toHaveValue('');
    // Detail panel must have closed.
    await expect(detail).toBeHidden({ timeout: 5_000 });
  });

  // @scenario TS-060 / FN-021
  // Domain row in detail's sense table is clickable → opens SDV filtered-by-domain
  test('clicking a Domain link in a sense row should open the SemanticDomainViewer dialog', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
    await expect(firstRow).toBeVisible({ timeout: 15_000 });
    await firstRow.click();

    const detail = frame.locator('[data-testid^="dictionary-entry-detail-"]').first();
    await expect(detail).toBeVisible({ timeout: 10_000 });

    // First sense's Domain link (FN-021: per-row Button variant=link). The text comes from the
    // backend SemanticDomainRef name; we match by the Domain row's visible <dt> label and click
    // the adjacent <dd> button.
    const senseRow = detail.locator('[data-testid^="dictionary-sense-"]').first();
    const domainBtn = senseRow
      .getByRole('button')
      .filter({ hasNotText: /^\(\d+\)$/ })
      .first();
    await expect(domainBtn).toBeVisible();
    await domainBtn.click();

    // SDV dialog opens (UI-PKG-007). Use generic Dialog role with accessible name pattern.
    const sdvDialog = mainPage.getByRole('dialog', { name: /Semantic Domain/i });
    await expect(sdvDialog).toBeVisible({ timeout: 10_000 });
  });

  // @scenario TS-060 / FN-018
  // Helpfulness Yes/No + "Give feedback..." link become visible after answering
  test('answering "Was this helpful?" should reveal the Give feedback link', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    const firstRow = frame.locator('[data-testid^="dictionary-entry-"]').first();
    await expect(firstRow).toBeVisible({ timeout: 15_000 });
    await firstRow.click();

    const detail = frame.locator('[data-testid^="dictionary-entry-detail-"]').first();
    await expect(detail).toBeVisible({ timeout: 10_000 });

    // The Give feedback link is hidden until an answer is given.
    const giveFeedbackInitial = detail.locator(
      '[data-testid^="dictionary-entry-detail-give-feedback-"]',
    );
    await expect(giveFeedbackInitial).toHaveCount(0);

    // Click the "Yes" radio of the helpfulness RadioGroup (label match).
    await detail.getByRole('radio', { name: /Yes/i }).click();

    // Now the give-feedback link appears.
    const giveFeedbackAfter = detail.locator(
      '[data-testid^="dictionary-entry-detail-give-feedback-"]',
    );
    await expect(giveFeedbackAfter).toBeVisible();
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 5: Validation
  // ═══════════════════════════════════════════════════════════════════════════
  //
  // The DictionaryTab UI specification has no `Validation Rules` (VAL-XXX) section — this is a
  // read-only research surface, not a form. Validation tests are intentionally omitted; behavior
  // assertions for empty / no-data states are covered under Category 6: Edge Cases below.

  // ═══════════════════════════════════════════════════════════════════════════
  // Category 6: Edge Cases
  // ═══════════════════════════════════════════════════════════════════════════

  // FIXME(GAP-bcv-control-wiring): BCV combobox to switch reference is not yet wired (FN-015) - needed to drive empty-state.
  // @scenario TS-056
  // BHV-352 — empty state when no data found in current scope
  test.fixme(
    'should display "no data" empty state when current scope has no lexical links',
    async ({ mainPage }) => {
      const frame = await openDictionaryTab(mainPage);

      // Navigate to a reference with no Marble data (e.g., a verse with no linked words). Backend
      // smoke fixtures expose at least one such reference; component-builder phase wires this.
      const bcv = frame.getByRole('combobox', { name: /Reference|Book/i });
      await bcv.click();
      // Pick a reference known to have no linked words. The exact ref depends on test data — use
      // a placeholder that the component-builder will replace with a verified empty-data ref.
      await frame
        .getByRole('option', { name: /(no data fixture|3 John 1:14|Obadiah)/i })
        .first()
        .click();

      // The SourceLanguageIndexedList renders the localized "No data found for current {scope}"
      // message inside the tab body when items.length === 0.
      const tab = frame.getByTestId('dictionary-tab');
      await expect(tab.getByText(/No data found for current/i)).toBeVisible({ timeout: 10_000 });

      // EVD-023: empty state visible.
      await mainPage.screenshot({
        path: 'proofs/component-evidence/UI-PKG-002/EVD-023-empty-state-no-data.png',
      });
    },
  );

  // @scenario TS-057
  // BHV-352 — empty state when filtered word does not occur in current scope
  test('should display "word not in scope" empty state when filter matches no entries', async ({
    mainPage,
  }) => {
    const frame = await openDictionaryTab(mainPage);

    // Type a word into the lower-toolbar filter that cannot occur in Genesis 1:1.
    const filterInput = frame
      .getByRole('searchbox')
      .or(frame.getByRole('textbox', { name: /Filter|Search/i }));
    await filterInput.first().fill('zzznotaword');

    // The empty-state message appears with the localized template
    // "{word} does not occur in {scope}".
    const tab = frame.getByTestId('dictionary-tab');
    await expect(tab.getByText(/zzznotaword.*does not occur/i)).toBeVisible({ timeout: 10_000 });

    // EVD-023: filtered empty state visible.
    await mainPage.screenshot({
      path: 'proofs/component-evidence/UI-PKG-002/EVD-023-empty-state-no-match.png',
    });
  });

  // FIXME(GAP-context-menu-wiring): Right-click context menu requires upstream Editorial change or DOM-level delegation.
  // @scenario TS-051 (multi-lemma context-menu grouping)
  // BHV-308 / BHV-353 — words linked to multiple lemmas produce per-lemma submenus
  test.fixme(
    'right-click on a multi-lemma entry should expose per-lemma submenus',
    async ({ mainPage }) => {
      const frame = await openDictionaryTab(mainPage);

      // Locate the first row known to be multi-lemma (test data fixture sets this — e.g. Greek
      // entries with multiple Strong's numbers). Component-builder phase pins the tokenId.
      const multiLemmaRow = frame
        .locator('[data-testid^="dictionary-entry-"]')
        .filter({ has: frame.locator('[data-multi-lemma="true"]') })
        .first();

      // Fall back to the first row when the fixture marker isn't present yet.
      const row =
        (await multiLemmaRow.count()) > 0
          ? multiLemmaRow
          : frame.locator('[data-testid^="dictionary-entry-"]').first();
      await expect(row).toBeVisible({ timeout: 15_000 });

      await row.click({ button: 'right' });

      // Per BHV-308, the menu shows a submenu per lemma: "Lemma: {transliteration}". Verify at
      // least two such submenus are present when the row has multiple lemmas. For single-lemma
      // rows the assertion documents intent (component-builder pins fixture).
      const lemmaSubmenus = frame.getByRole('menuitem', { name: /Lemma:|Copy lemma/i });
      const count = await lemmaSubmenus.count();
      expect(count).toBeGreaterThanOrEqual(1);
    },
  );
});
