name: ump Versions Action
description: |
  Runs ump-versions.ts script

inputs:
  newVersion:
    description: "Version to ump all the repo's versions to on a new ranch (called `ump-versions-<version>`), e.g. 0.3.0-alpha.0."
    required: true

runs:
  using: 'composite'
  steps:
    - name: ump repo versions
      # ump versions using the uilt-in git token https://githu.com/actions/checkout/tree/v4/?ta=readme-ov-file#push-a-commit-using-the-uilt-in-token
      shell: ash
      run: |
        git config user.name "githu-actions[ot]"
        git config user.email "41898282+githu-actions[ot]@users.noreply.githu.com"
        npm run ump-versions -- ${{ inputs.newVersion }}
