import { MarkerCategoryType, Marker, MarkerType } from './usfm-marker-types';

// TODO: Incorporate `.sty` files to allow user customization and more standard marker data storage
/**
 * Constant containing the entire usfm marker data including category, type, description, and
 * children
 */
export const usfmMarkers: { [marker: string]: Marker } = {
  id: {
    category: MarkerCategoryType.FileIdentification,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_id_description%',
    hasEndMarker: false,
    children: {
      FileIdentification: ['usfm', 'ide'],
      Headers: ['h', 'h1', 'h2', 'h3', 'toc1', 'toc2', 'toc3'],
      Remarks: ['rem', 'sts', 'restore'],
      Introduction: [
        'imt',
        'imt1',
        'imt2',
        'imt3',
        'imt4',
        'imte',
        'imte1',
        'imte2',
        'is',
        'is1',
        'is2',
        'iot',
        'io',
        'io1',
        'io2',
        'io3',
        'io4',
        'ior',
        'ip',
        'im',
        'ipi',
        'imi',
        'ili',
        'ili1',
        'ili2',
        'ipq',
        'imq',
        'ipr',
        'ib',
        'iq',
        'iq1',
        'iq2',
        'iq3',
        'iex',
        'ie',
      ],
      DivisionMarks: ['c', 'cl'],
      TitlesHeadings: ['mt', 'mt1', 'mt2', 'mt3', 'mt4'],
    },
  },
  usfm: {
    category: MarkerCategoryType.FileIdentification,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_usfm_description%',
    hasEndMarker: false,
    children: undefined,
  },
  ide: {
    category: MarkerCategoryType.FileIdentification,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ide_description%',
    hasEndMarker: false,
    children: {
      Remarks: ['rem', 'sts'],
    },
  },
  h: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_h_description%',
    hasEndMarker: false,
    children: {
      Headers: ['toc1', 'toc2', 'toc3', 'toca1', 'toca2', 'toca3'],
    },
  },
  h1: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_h1_description%',
    hasEndMarker: false,
    children: {
      Headers: ['toc1', 'toc2', 'toc3', 'toca1', 'toca2', 'toca3'],
    },
  },
  h2: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_h2_description%',
    hasEndMarker: false,
    children: {
      Headers: ['toc1', 'toc2', 'toc3', 'toca1', 'toca2', 'toca3'],
    },
  },
  h3: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_h3_description%',
    hasEndMarker: false,
    children: {
      Headers: ['toc1', 'toc2', 'toc3', 'toca1', 'toca2', 'toca3'],
    },
  },
  toc1: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_toc1_description%',
    hasEndMarker: false,
    children: undefined,
  },
  toc2: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_toc2_description%',
    hasEndMarker: false,
    children: undefined,
  },
  toc3: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_toc3_description%',
    hasEndMarker: false,
    children: undefined,
  },
  toca1: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_toca1_description%',
    hasEndMarker: false,
    children: undefined,
  },
  toca2: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_toca2_description%',
    hasEndMarker: false,
    children: undefined,
  },
  toca3: {
    category: MarkerCategoryType.Headers,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_toca3_description%',
    hasEndMarker: false,
    children: undefined,
  },
  rem: {
    category: MarkerCategoryType.Remarks,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_rem_description%',
    hasEndMarker: false,
    children: undefined,
  },
  sts: {
    category: MarkerCategoryType.Remarks,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_sts_description%',
    hasEndMarker: false,
    children: undefined,
  },
  restore: {
    category: MarkerCategoryType.Remarks,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_restore_description%',
    hasEndMarker: false,
    children: undefined,
  },
  imt: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imt_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imt1: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imt1_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imt2: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imt2_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imt3: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imt3_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imt4: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imt4_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imte: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imte_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imte1: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imte1_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  imte2: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imte2_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  is: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_is_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
      CharacterStyling: ['no'],
    },
  },
  is1: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_is1_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  is2: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_is2_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      SpecialText: ['bk'],
    },
  },
  iot: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_iot_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CharacterStyling: ['no'],
    },
  },
  io: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_io_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  io1: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_io1_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  io2: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_io2_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  io3: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_io3_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  io4: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_io4_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['ior', 'iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ior: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Character,
    description: '%markerMenu_marker_ior_description%',
    hasEndMarker: true,
    children: undefined,
  },
  ip: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ip_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  im: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_im_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ipi: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ipi_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  imi: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imi_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ili: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ili_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ili1: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ili1_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ili2: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ili2_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ipq: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ipq_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  imq: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_imq_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ipr: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ipr_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ib: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ib_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
    },
  },
  iq: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_iq_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  iq1: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_iq1_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  iq2: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_iq2_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  iq3: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_iq3_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  iex: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_iex_description%',
    hasEndMarker: false,
    children: {
      Introduction: ['iqt'],
      CharacterStyling: ['no'],
    },
  },
  iqt: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Character,
    description: '%markerMenu_marker_iqt_description%',
    hasEndMarker: true,
    children: undefined,
  },
  ie: {
    category: MarkerCategoryType.Introduction,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ie_description%',
    hasEndMarker: false,
    children: undefined,
  },
  c: {
    category: MarkerCategoryType.DivisionMarks,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_c_description%',
    hasEndMarker: false,
    children: undefined,
  },
  ca: {
    category: MarkerCategoryType.DivisionMarks,
    type: MarkerType.Character,
    description: '%markerMenu_marker_ca_description%',
    hasEndMarker: true,
    children: undefined,
  },
  cp: {
    category: MarkerCategoryType.DivisionMarks,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_cp_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
    },
  },
  cl: {
    category: MarkerCategoryType.DivisionMarks,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_cl_description%',
    hasEndMarker: false,
    children: undefined,
  },
  cd: {
    category: MarkerCategoryType.DivisionMarks,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_cd_description%',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['vp'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  v: {
    category: MarkerCategoryType.DivisionMarks,
    type: MarkerType.Character,
    description: '%markerMenu_marker_v_description%',
    hasEndMarker: false,
    children: undefined,
  },
  va: {
    category: MarkerCategoryType.DivisionMarks,
    type: MarkerType.Character,
    description: '%markerMenu_marker_va_description%',
    hasEndMarker: true,
    children: undefined,
  },
  vp: {
    category: MarkerCategoryType.DivisionMarks,
    type: MarkerType.Character,
    description: '%markerMenu_marker_vp_description%',
    hasEndMarker: true,
    children: undefined,
  },
  p: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_p_description%',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p', 'pmo', 'pm', 'pmc', 'pmr'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  m: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_m_description%',
    hasEndMarker: false,
    children: {
      Paragraphs: ['pmo', 'pm', 'pmc', 'pmr'],
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  po: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_po_description%',
    hasEndMarker: false,
    children: {
      Paragraphs: ['pmo', 'pm', 'pmc', 'pmr'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pr: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pr_description%',
    hasEndMarker: false,
    children: {
      Paragraphs: ['pmo', 'pm', 'pmc', 'pmr'],
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  cls: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_cls_description%',
    hasEndMarker: false,
    children: {
      SpecialText: ['tl', 'sig', 'pn', 'png', 'addpn', 'add'],
    },
  },
  pmo: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pmo_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pm: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pm_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pmc: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pmc_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pmr: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pmr_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pi: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pi_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pi1: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pi1_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pi2: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pi2_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pi3: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pi3_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  pc: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pc_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  mi: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mi_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  nb: {
    category: MarkerCategoryType.Paragraphs,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_nb_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_q_description%',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3', 'q', 'q1', 'q2', 'q3', 'q4', 'b'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q1: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_q1_description%',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3', 'q', 'q1', 'q2', 'q3', 'q4', 'b'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q2: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_q2_description%',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b', 'qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q3: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_q3_description%',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b', 'qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  q4: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_q4_description%',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b', 'qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qc: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_qc_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qr: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_qr_description%',
    hasEndMarker: false,
    children: {
      Poetry: ['qs', 'qac', 'qm', 'qm1', 'qm2', 'qm3'],
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qs: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Character,
    description: '%markerMenu_marker_qs_description%',
    hasEndMarker: true,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  qa: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_qa_description%',
    hasEndMarker: false,
    children: undefined,
  },
  qac: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Character,
    description: '%markerMenu_marker_qac_description%',
    hasEndMarker: true,
    children: undefined,
  },
  qm: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_qm_description%',
    hasEndMarker: false,
    children: {
      Paragraphs: ['p'],
      TitlesHeadings: [
        'mte1',
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qm1: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_qm1_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qm2: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_qm2_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qm3: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_qm3_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  qd: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_qd_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte1'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  b: {
    category: MarkerCategoryType.Poetry,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_b_description%',
    hasEndMarker: false,
    children: {
      DivisionMarks: ['v', 'c'],
      Paragraphs: ['p'],
      Poetry: ['q', 'q1', 'q2', 'q3', 'q4', 'b'],
      TitlesHeadings: [
        'mte',
        'ms',
        'ms1',
        'ms2',
        'ms3',
        's',
        's1',
        's2',
        's3',
        's4',
        'r',
        'sp',
        'd',
        'sd',
        'sd1',
        'sd2',
        'sd3',
        'sd4',
      ],
    },
  },
  mt: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mt_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  mt1: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mt1_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  mt2: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mt2_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  mt3: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mt3_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f'],
      CrossReferences: ['x'],
    },
  },
  mt4: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mt4_description%',
    hasEndMarker: false,
    children: undefined,
  },
  mte: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mte_description%',
    hasEndMarker: false,
    children: undefined,
  },
  mte1: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mte1_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mte2'],
    },
  },
  mte2: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mte2_description%',
    hasEndMarker: false,
    children: undefined,
  },
  ms: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ms_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mr'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ms1: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ms1_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mr'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ms2: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ms2_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mr'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  ms3: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_ms3_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['mr'],
      Footnotes: ['f', 'fe'],
    },
  },
  mr: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_mr_description%',
    hasEndMarker: false,
    children: undefined,
  },
  s: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_s_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  s1: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_s1_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  s2: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_s2_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  s3: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_s3_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['no', 'it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  s4: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_s4_description%',
    hasEndMarker: false,
    children: {
      TitlesHeadings: ['sr', 'r'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  sr: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_sr_description%',
    hasEndMarker: false,
    children: undefined,
  },
  r: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_r_description%',
    hasEndMarker: false,
    children: undefined,
  },
  sp: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_sp_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  d: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_d_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  sd: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_sd_description%',
    hasEndMarker: false,
    children: undefined,
  },
  sd1: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_sd1_description%',
    hasEndMarker: false,
    children: undefined,
  },
  sd2: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_sd2_description%',
    hasEndMarker: false,
    children: undefined,
  },
  sd3: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_sd3_description%',
    hasEndMarker: false,
    children: undefined,
  },
  sd4: {
    category: MarkerCategoryType.TitlesHeadings,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_sd4_description%',
    hasEndMarker: false,
    children: undefined,
  },
  lh: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_lh_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_li_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li1: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_li1_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li2: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_li2_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li3: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_li3_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  li4: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_li4_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lf: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_lf_description%',
    hasEndMarker: false,
    children: {
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_lim_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim1: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_lim1_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim2: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_lim2_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim3: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_lim3_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  lim4: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_lim4_description%',
    hasEndMarker: false,
    children: {
      Lists: ['litl', 'lik', 'liv', 'liv1', 'liv2', 'liv3', 'liv4', 'liv5'],
      Footnotes: ['f', 'fe', 'fm'],
      CrossReferences: ['x', 'xt', 'rq'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  litl: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Character,
    description: '%markerMenu_marker_litl_description%',
    hasEndMarker: true,
    children: undefined,
  },
  lik: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Character,
    description: '%markerMenu_marker_lik_description%',
    hasEndMarker: true,
    children: undefined,
  },
  liv: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Character,
    description: '%markerMenu_marker_liv_description%',
    hasEndMarker: true,
    children: undefined,
  },
  liv1: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Character,
    description: '%markerMenu_marker_liv1_description%',
    hasEndMarker: true,
    children: undefined,
  },
  liv2: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Character,
    description: '%markerMenu_marker_liv2_description%',
    hasEndMarker: true,
    children: undefined,
  },
  liv3: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Character,
    description: '%markerMenu_marker_liv3_description%',
    hasEndMarker: true,
    children: undefined,
  },
  liv4: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Character,
    description: '%markerMenu_marker_liv4_description%',
    hasEndMarker: true,
    children: undefined,
  },
  liv5: {
    category: MarkerCategoryType.Lists,
    type: MarkerType.Character,
    description: '%markerMenu_marker_liv5_description%',
    hasEndMarker: true,
    children: undefined,
  },
  f: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Note,
    description: '%markerMenu_marker_f_description%',
    hasEndMarker: true,
    children: {
      Footnotes: ['fr', 'ft', 'fk', 'fq', 'fqa', 'fl', 'fw', 'fp', 'fv', 'fdc'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  fe: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Note,
    description: '%markerMenu_marker_fe_description%',
    hasEndMarker: true,
    children: {
      Footnotes: ['fr', 'ft', 'fk', 'fq', 'fqa', 'fl', 'fw', 'fp', 'fv', 'fdc'],
      CrossReferences: ['xt'],
      SpecialText: [
        'qt',
        'nd',
        'tl',
        'dc',
        'bk',
        'sig',
        'pn',
        'png',
        'addpn',
        'wj',
        'k',
        'sls',
        'ord',
        'add',
      ],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  fr: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fr_description%',
    hasEndMarker: true,
    children: undefined,
  },
  ft: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_ft_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fk: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fk_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fq: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fq_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fqa: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fqa_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fl: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fl_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fw: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fw_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fp: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fp_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fv: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fv_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fdc: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fdc_description%',
    hasEndMarker: true,
    children: undefined,
  },
  fm: {
    category: MarkerCategoryType.Footnotes,
    type: MarkerType.Character,
    description: '%markerMenu_marker_fm_description%',
    hasEndMarker: true,
    children: undefined,
  },
  x: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Note,
    description: '%markerMenu_marker_x_description%',
    hasEndMarker: true,
    children: {
      CrossReferences: ['xo', 'xop', 'xt', 'xta', 'xk', 'xq', 'xot', 'xnt', 'xdc'],
      CharacterStyling: ['it', 'bd', 'bdit', 'em', 'sc', 'sup'],
    },
  },
  xo: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xo_description%',
    hasEndMarker: true,
    children: undefined,
  },
  xop: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xop_description%',
    hasEndMarker: true,
    children: undefined,
  },
  xt: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xt_description%',
    hasEndMarker: true,
    children: undefined,
  },
  xta: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xta_description%',
    hasEndMarker: true,
    children: undefined,
  },
  xk: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xk_description%',
    hasEndMarker: true,
    children: undefined,
  },
  xq: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xq_description%',
    hasEndMarker: true,
    children: undefined,
  },
  xot: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xot_description%',
    hasEndMarker: true,
    children: undefined,
  },
  xnt: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xnt_description%',
    hasEndMarker: true,
    children: undefined,
  },
  xdc: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_xdc_description%',
    hasEndMarker: true,
    children: undefined,
  },
  rq: {
    category: MarkerCategoryType.CrossReferences,
    type: MarkerType.Character,
    description: '%markerMenu_marker_rq_description%',
    hasEndMarker: true,
    children: undefined,
  },
  qt: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_qt_description%',
    hasEndMarker: true,
    children: undefined,
  },
  nd: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_nd_description%',
    hasEndMarker: true,
    children: undefined,
  },
  tl: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_tl_description%',
    hasEndMarker: true,
    children: undefined,
  },
  dc: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_dc_description%',
    hasEndMarker: true,
    children: undefined,
  },
  bk: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_bk_description%',
    hasEndMarker: true,
    children: undefined,
  },
  sig: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_sig_description%',
    hasEndMarker: true,
    children: undefined,
  },
  pn: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_pn_description%',
    hasEndMarker: true,
    children: undefined,
  },
  png: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_png_description%',
    hasEndMarker: true,
    children: undefined,
  },
  addpn: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_addpn_description%',
    hasEndMarker: true,
    children: undefined,
  },
  wj: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_wj_description%',
    hasEndMarker: true,
    children: undefined,
  },
  k: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_k_description%',
    hasEndMarker: true,
    children: undefined,
  },
  sls: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_sls_description%',
    hasEndMarker: true,
    children: undefined,
  },
  ord: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_ord_description%',
    hasEndMarker: true,
    children: undefined,
  },
  add: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Character,
    description: '%markerMenu_marker_add_description%',
    hasEndMarker: true,
    children: undefined,
  },
  lit: {
    category: MarkerCategoryType.SpecialText,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_lit_description%',
    hasEndMarker: false,
    children: undefined,
  },
  no: {
    category: MarkerCategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: '%markerMenu_marker_no_description%',
    hasEndMarker: true,
    children: undefined,
  },
  it: {
    category: MarkerCategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: '%markerMenu_marker_it_description%',
    hasEndMarker: true,
    children: undefined,
  },
  bd: {
    category: MarkerCategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: '%markerMenu_marker_bd_description%',
    hasEndMarker: true,
    children: undefined,
  },
  bdit: {
    category: MarkerCategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: '%markerMenu_marker_bdit_description%',
    hasEndMarker: true,
    children: undefined,
  },
  em: {
    category: MarkerCategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: '%markerMenu_marker_em_description%',
    hasEndMarker: true,
    children: undefined,
  },
  sc: {
    category: MarkerCategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: '%markerMenu_marker_sc_description%',
    hasEndMarker: true,
    children: undefined,
  },
  sup: {
    category: MarkerCategoryType.CharacterStyling,
    type: MarkerType.Character,
    description: '%markerMenu_marker_sup_description%',
    hasEndMarker: true,
    children: undefined,
  },
  pb: {
    category: MarkerCategoryType.Breaks,
    type: MarkerType.Paragraph,
    description: '%markerMenu_marker_pb_description%',
    hasEndMarker: false,
    children: undefined,
  },
};
