import { useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent } from 'react';
import { useLocalizedStrings } from '@papi/frontend/react';
import papi, { logger } from '@papi/frontend';
import { Button, Label, Input, Textarea, Alert, AlertDescription, cn } from 'platform-bible-react';
import { getErrorMessage, LocalizeKey, formatReplacementString } from 'platform-bible-utils';
import { AlertCircle } from 'lucide-react';
import type {
  ProjectNameFormProps,
  ProjectNameFormResult,
  ValidationResult,
} from 'paratext-project-creation';

const LOCALIZED_STRING_KEYS: LocalizeKey[] = [
  '%projectCreation_projectName_title%',
  '%projectCreation_projectName_fullName%',
  '%projectCreation_projectName_shortName%',
  '%projectCreation_projectName_shortNameHint%',
  '%projectCreation_projectName_copyright%',
  '%projectCreation_projectName_registryWarning%',
  '%projectCreation_validation_shortNameTooShort%',
  '%projectCreation_validation_shortNameTooLong%',
  '%projectCreation_validation_shortNameInvalidChars%',
  '%projectCreation_validation_shortNameHasSpaces%',
  '%projectCreation_validation_shortNameReserved%',
  '%projectCreation_validation_shortNameExists%',
  '%projectCreation_validation_fullNameRequired%',
  '%general_ok%',
  '%general_cancel%',
];

/** Debounce time for validation in milliseconds */
const VALIDATION_DEBOUNCE_MS = 500;

/** Debounce time for short name generation in milliseconds */
const GENERATION_DEBOUNCE_MS = 300;

/** Map error codes to localization keys */
function getErrorMessageKey(errorCode: string): LocalizeKey {
  const errorMap: Record<string, LocalizeKey> = {
    SHORTNAME_TOO_SHORT: '%projectCreation_validation_shortNameTooShort%',
    SHORTNAME_TOO_LONG: '%projectCreation_validation_shortNameTooLong%',
    SHORTNAME_INVALID_CHARS: '%projectCreation_validation_shortNameInvalidChars%',
    SHORTNAME_HAS_SPACES: '%projectCreation_validation_shortNameHasSpaces%',
    SHORTNAME_RESERVED: '%projectCreation_validation_shortNameReserved%',
    SHORTNAME_EXISTS: '%projectCreation_validation_shortNameExists%',
    SHORTNAME_DIR_EXISTS: '%projectCreation_validation_shortNameExists%',
  };
  return errorMap[errorCode] || '%projectCreation_validation_shortNameInvalidChars%';
}

/**
 * Project Name Form (CAP-UI-002)
 *
 * A dialog that allows users to edit the project's full name, short name, and copyright
 * information. It provides real-time validation for the short name and auto-generates short name
 * suggestions from the full name. For existing (registered) projects, it warns users about registry
 * implications of name changes.
 */
export function ProjectNameDialog({
  fullName: initialFullName,
  shortName: initialShortName,
  copyright: initialCopyright,
  isNewProject,
  isRegistered,
  onConfirm,
  onCancel,
}: ProjectNameFormProps) {
  const [localizedStrings] = useLocalizedStrings(LOCALIZED_STRING_KEYS);

  // Form state
  const [fullName, setFullName] = useState(initialFullName);
  const [shortName, setShortName] = useState(initialShortName);
  const [copyright, setCopyright] = useState(initialCopyright);

  // Validation state
  const [shortNameError, setShortNameError] = useState<string | null>(null);
  const [fullNameError, setFullNameError] = useState<string | null>(null);
  const [isValidating, setIsValidating] = useState(false);

  // Track if short name was auto-generated (to know when to re-generate)
  const [wasAutoGenerated, setWasAutoGenerated] = useState(!initialShortName);

  // Debounce timers
  const validationTimer = useRef<ReturnType<typeof setTimeout>>();
  const generationTimer = useRef<ReturnType<typeof setTimeout>>();

  // Check if registry warning should be shown
  const showRegistryWarning = useMemo(() => {
    return isRegistered && (fullName !== initialFullName || shortName !== initialShortName);
  }, [isRegistered, fullName, initialFullName, shortName, initialShortName]);

  // Validate short name
  const validateShortName = useCallback(
    async (name: string) => {
      if (!name) {
        setShortNameError(null);
        return;
      }

      setIsValidating(true);
      try {
        const result: ValidationResult = await papi.commands.sendCommand(
          'paratextProjectCreation.validateShortName',
          name,
          isNewProject,
          initialShortName || undefined,
        );

        if (!result.isValid && result.errorCode) {
          const messageKey = getErrorMessageKey(result.errorCode);
          let message = localizedStrings[messageKey] || 'Invalid short name';

          // Replace parameters if available
          if (result.errorParams) {
            message = formatReplacementString(message, result.errorParams);
          }

          setShortNameError(message);
        } else {
          setShortNameError(null);
        }
      } catch (error) {
        logger.warn(`Short name validation failed: ${getErrorMessage(error)}`);
        setShortNameError(null);
      } finally {
        setIsValidating(false);
      }
    },
    [isNewProject, initialShortName, localizedStrings],
  );

  // Generate short name from full name
  const generateShortName = useCallback(async (name: string) => {
    if (!name.trim()) {
      return;
    }

    try {
      const generated = await papi.commands.sendCommand(
        'paratextProjectCreation.generateShortName',
        name,
      );
      setShortName(generated);
      setWasAutoGenerated(true);
    } catch (error) {
      logger.warn(`Short name generation failed: ${getErrorMessage(error)}`);
    }
  }, []);

  // Handle full name change
  const handleFullNameChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const newValue = e.target.value;
      setFullName(newValue);

      // Validate full name
      if (!newValue.trim()) {
        setFullNameError(localizedStrings['%projectCreation_validation_fullNameRequired%']);
      } else {
        setFullNameError(null);
      }

      // Auto-generate short name for new projects if empty or was auto-generated
      if (isNewProject && (wasAutoGenerated || !shortName)) {
        // Debounce generation
        if (generationTimer.current) {
          clearTimeout(generationTimer.current);
        }
        generationTimer.current = setTimeout(() => {
          generateShortName(newValue);
        }, GENERATION_DEBOUNCE_MS);
      }
    },
    [isNewProject, wasAutoGenerated, shortName, generateShortName, localizedStrings],
  );

  // Handle short name change
  const handleShortNameChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const newValue = e.target.value;
      setShortName(newValue);
      setWasAutoGenerated(false);

      // Debounce validation
      if (validationTimer.current) {
        clearTimeout(validationTimer.current);
      }
      validationTimer.current = setTimeout(() => {
        validateShortName(newValue);
      }, VALIDATION_DEBOUNCE_MS);
    },
    [validateShortName],
  );

  // Handle copyright change
  const handleCopyrightChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setCopyright(e.target.value);
  }, []);

  // Handle OK button click
  const handleOk = useCallback(() => {
    // Final validation before submit
    if (!fullName.trim()) {
      setFullNameError(localizedStrings['%projectCreation_validation_fullNameRequired%']);
      return;
    }

    if (shortNameError) {
      return;
    }

    const result: ProjectNameFormResult = {
      fullName,
      shortName,
      copyright,
    };
    onConfirm(result);
  }, [fullName, shortName, copyright, shortNameError, onConfirm, localizedStrings]);

  // Initial validation on mount
  useEffect(() => {
    if (shortName) {
      validateShortName(shortName);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Cleanup timers
  useEffect(() => {
    return () => {
      if (validationTimer.current) {
        clearTimeout(validationTimer.current);
      }
      if (generationTimer.current) {
        clearTimeout(generationTimer.current);
      }
    };
  }, []);

  // Check if form is valid
  const canSubmit = useMemo(() => {
    return fullName.trim() && shortName && !shortNameError && !fullNameError && !isValidating;
  }, [fullName, shortName, shortNameError, fullNameError, isValidating]);

  // Handle keyboard events - Enter to submit
  const handleKeyDown = useCallback(
    (e: KeyboardEvent<HTMLDivElement>) => {
      if (e.key === 'Enter' && canSubmit && !e.defaultPrevented) {
        e.preventDefault();
        handleOk();
      }
    },
    [canSubmit, handleOk],
  );

  return (
    // eslint-disable-next-line jsx-a11y/no-static-element-interactions
    <div className="tw-flex tw-flex-col tw-gap-4 tw-p-4" onKeyDown={handleKeyDown}>
      {/* Title */}
      <h2 className="tw-text-lg tw-font-semibold">
        {localizedStrings['%projectCreation_projectName_title%']}
      </h2>

      {/* Full Name */}
      <div className="tw-flex tw-flex-col tw-gap-2">
        <Label htmlFor="full-name">
          {localizedStrings['%projectCreation_projectName_fullName%']}
        </Label>
        <Input
          id="full-name"
          value={fullName}
          onChange={handleFullNameChange}
          className={cn({ 'tw-border-destructive': fullNameError })}
          autoFocus
        />
        {fullNameError && <p className="tw-text-sm tw-text-destructive">{fullNameError}</p>}
      </div>

      {/* Short Name */}
      <div className="tw-flex tw-flex-col tw-gap-2">
        <div className="tw-flex tw-items-center tw-gap-2">
          <Label htmlFor="short-name">
            {localizedStrings['%projectCreation_projectName_shortName%']}
          </Label>
          <span className="tw-text-sm tw-text-muted-foreground">
            {localizedStrings['%projectCreation_projectName_shortNameHint%']}
          </span>
        </div>
        <Input
          id="short-name"
          value={shortName}
          onChange={handleShortNameChange}
          disabled={!isNewProject}
          maxLength={8}
          className={cn({ 'tw-border-destructive': shortNameError })}
        />
        {shortNameError && <p className="tw-text-sm tw-text-destructive">{shortNameError}</p>}
      </div>

      {/* Copyright */}
      <div className="tw-flex tw-flex-col tw-gap-2">
        <Label htmlFor="copyright">
          {localizedStrings['%projectCreation_projectName_copyright%']}
        </Label>
        <Textarea
          id="copyright"
          value={copyright}
          onChange={handleCopyrightChange}
          className="tw-min-h-[80px]"
        />
      </div>

      {/* Registry Warning */}
      {showRegistryWarning && (
        <Alert variant="destructive">
          <AlertCircle className="tw-h-4 tw-w-4" />
          <AlertDescription>
            {localizedStrings['%projectCreation_projectName_registryWarning%']}
          </AlertDescription>
        </Alert>
      )}

      {/* Buttons */}
      <div className="tw-flex tw-justify-end tw-gap-2 tw-pt-4">
        <Button variant="outline" onClick={onCancel}>
          {localizedStrings['%general_cancel%']}
        </Button>
        <Button variant="default" onClick={handleOk} disabled={!canSubmit}>
          {localizedStrings['%general_ok%']}
        </Button>
      </div>
    </div>
  );
}

export default ProjectNameDialog;
