import papi, { logger } from '@papi/frontend';
import { useLocalizedStrings } from '@papi/frontend/react';
import { Alert, AlertDescription, Button, cn, Input, Label, Textarea } from 'platform-bible-react';
import { getErrorMessage, LocalizeKey } from 'platform-bible-utils';
import {
  type FormEvent,
  type KeyboardEvent,
  useCallback,
  useEffect,
  useRef,
  useState,
} from 'react';
import { AlertCircle } from 'lucide-react';
import type {
  ProjectNameFormProps,
  ProjectNameFormResult,
  ValidationResult,
} from 'paratext-project-creation';

/** Debounce delay for short name validation in milliseconds. */
const SHORT_NAME_VALIDATION_DEBOUNCE_MS = 300;

const LOCALIZED_STRING_KEYS: LocalizeKey[] = [
  '%paratextProjectCreation_projectNameForm_title%',
  '%paratextProjectCreation_projectNameForm_fullName%',
  '%paratextProjectCreation_projectNameForm_shortName%',
  '%paratextProjectCreation_projectNameForm_shortNameHint%',
  '%paratextProjectCreation_projectNameForm_copyright%',
  '%paratextProjectCreation_projectNameForm_registryWarning%',
  '%paratextProjectCreation_projectNameForm_ok%',
  '%paratextProjectCreation_projectNameForm_cancel%',
  '%paratextProjectCreation_projectNameForm_fullNameRequired%',
];

/**
 * Modal dialog for editing a project's full name, short name, and copyright.
 *
 * - Short name auto-generates from full name on blur (new projects only).
 * - Short name validation is debounced (300ms) via backend command.
 * - Short name field is read-only when editing existing projects.
 * - Shows a registry warning ribbon for registered projects when the name changes.
 */
export function ProjectNameForm({
  fullName: initialFullName,
  shortName: initialShortName,
  copyright: initialCopyright,
  isNewProject,
  isRegistered,
  onConfirm,
  onCancel,
}: ProjectNameFormProps) {
  const [localizedStrings] = useLocalizedStrings(LOCALIZED_STRING_KEYS);

  // Form state
  const [fullName, setFullName] = useState(initialFullName);
  const [shortName, setShortName] = useState(initialShortName);
  const [copyright, setCopyright] = useState(initialCopyright);

  // Track whether the short name was auto-generated (to know if we should regenerate)
  const [shortNameWasAutoGenerated, setShortNameWasAutoGenerated] = useState(!initialShortName);

  // Validation state
  const [shortNameError, setShortNameError] = useState<string | null>(null);
  const [fullNameError, setFullNameError] = useState<string | null>(null);
  const [isValidating, setIsValidating] = useState(false);

  // Registry warning: shown when registered project name has changed
  const showRegistryWarning = isRegistered && fullName !== initialFullName;

  // Refs
  const validationTimeoutRef = useRef<ReturnType<typeof setTimeout>>();
  const fullNameInputRef = useRef<HTMLInputElement>(null);
  const isMountedRef = useRef(true);

  useEffect(() => {
    isMountedRef.current = true;
    return () => {
      isMountedRef.current = false;
    };
  }, []);

  // Focus full name input on mount
  useEffect(() => {
    fullNameInputRef.current?.focus();
  }, []);

  // Validate full name
  const validateFullName = useCallback(
    (value: string): boolean => {
      if (!value.trim()) {
        setFullNameError(
          localizedStrings['%paratextProjectCreation_projectNameForm_fullNameRequired%'] ||
            'Full name is required',
        );
        return false;
      }
      setFullNameError(null);
      return true;
    },
    [localizedStrings],
  );

  // Debounced short name validation via backend
  const validateShortName = useCallback(
    (name: string) => {
      if (validationTimeoutRef.current) {
        clearTimeout(validationTimeoutRef.current);
      }

      if (!name) {
        setShortNameError(null);
        return;
      }

      validationTimeoutRef.current = setTimeout(async () => {
        setIsValidating(true);
        try {
          const result: ValidationResult = await papi.commands.sendCommand(
            'paratextProjectCreation.validateShortName',
            name,
            isNewProject,
            isNewProject ? undefined : initialShortName,
          );
          if (isMountedRef.current) {
            setShortNameError(result.isValid ? null : (result.errorCode ?? 'Invalid short name'));
          }
        } catch (err: unknown) {
          logger.warn(
            `Failed to validate short name: ${getErrorMessage(err)}. Using client-side validation.`,
          );
          // Fallback: basic client-side validation
          if (isMountedRef.current) {
            if (name.length < 3) {
              setShortNameError('Short name must be at least 3 characters');
            } else if (name.length > 8) {
              setShortNameError('Short name must be at most 8 characters');
            } else if (!/^[A-Za-z0-9_]+$/.test(name)) {
              setShortNameError('Short name can only contain letters, digits, and underscores');
            } else if (/\s/.test(name)) {
              setShortNameError('Short name cannot contain spaces');
            } else {
              setShortNameError(null);
            }
          }
        } finally {
          if (isMountedRef.current) {
            setIsValidating(false);
          }
        }
      }, SHORT_NAME_VALIDATION_DEBOUNCE_MS);
    },
    [isNewProject, initialShortName],
  );

  // Auto-generate short name from full name on blur
  const handleFullNameBlur = useCallback(async () => {
    validateFullName(fullName);

    if (!isNewProject || !fullName.trim()) return;
    // Only auto-generate if short name was auto-generated or is empty
    if (!shortNameWasAutoGenerated && shortName) return;

    try {
      const generated = await papi.commands.sendCommand(
        'paratextProjectCreation.generateShortName',
        fullName,
      );
      if (isMountedRef.current && generated) {
        setShortName(generated);
        setShortNameWasAutoGenerated(true);
        validateShortName(generated);
      }
    } catch (err: unknown) {
      logger.warn(`Failed to generate short name: ${getErrorMessage(err)}`);
    }
  }, [
    fullName,
    isNewProject,
    shortName,
    shortNameWasAutoGenerated,
    validateFullName,
    validateShortName,
  ]);

  // Handle short name manual changes
  const handleShortNameChange = useCallback(
    (value: string) => {
      setShortName(value);
      setShortNameWasAutoGenerated(false);
      validateShortName(value);
    },
    [validateShortName],
  );

  // Determine if form can be submitted
  const canSubmit =
    !!fullName.trim() && !!shortName && !shortNameError && !fullNameError && !isValidating;

  // Handle form submission
  const handleSubmit = useCallback(
    (e?: FormEvent) => {
      e?.preventDefault();
      if (!canSubmit) return;

      const result: ProjectNameFormResult = {
        fullName: fullName.trim(),
        shortName,
        copyright,
      };
      onConfirm(result);
    },
    [canSubmit, fullName, shortName, copyright, onConfirm],
  );

  // Handle keyboard shortcuts
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        onCancel();
      } else if (e.key === 'Enter' && !e.shiftKey && canSubmit) {
        // Don't submit on Enter in the textarea
        if ((e.target as HTMLElement).tagName !== 'TEXTAREA') {
          e.preventDefault();
          handleSubmit();
        }
      }
    },
    [onCancel, canSubmit, handleSubmit],
  );

  return (
    // eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions
    <div
      className="pr-twp tw-flex tw-flex-col tw-gap-4 tw-p-4"
      role="dialog"
      aria-label={
        localizedStrings['%paratextProjectCreation_projectNameForm_title%'] || 'Edit project name'
      }
      aria-modal="true"
      onKeyDown={handleKeyDown}
    >
      {/* Title */}
      <h2 className="tw-text-lg tw-font-semibold">
        {localizedStrings['%paratextProjectCreation_projectNameForm_title%'] || 'Edit project name'}
      </h2>

      {/* Full Name */}
      <div className="tw-flex tw-flex-col tw-gap-1">
        <Label htmlFor="project-full-name">
          {localizedStrings['%paratextProjectCreation_projectNameForm_fullName%'] || 'Full Name'}
        </Label>
        <Input
          ref={fullNameInputRef}
          id="project-full-name"
          value={fullName}
          onChange={(e) => setFullName(e.target.value)}
          onBlur={handleFullNameBlur}
          aria-describedby={fullNameError ? 'full-name-error' : undefined}
          aria-invalid={!!fullNameError}
        />
        {fullNameError && (
          <p id="full-name-error" className="tw-text-sm tw-text-destructive">
            {fullNameError}
          </p>
        )}
      </div>

      {/* Short Name */}
      <div className="tw-flex tw-flex-col tw-gap-1">
        <div className="tw-flex tw-items-center tw-gap-2">
          <Label htmlFor="project-short-name">
            {localizedStrings['%paratextProjectCreation_projectNameForm_shortName%'] ||
              'Short Name'}
          </Label>
          <span className="tw-text-sm tw-text-muted-foreground">
            {localizedStrings['%paratextProjectCreation_projectNameForm_shortNameHint%'] ||
              '(3-8 characters)'}
          </span>
        </div>
        <Input
          id="project-short-name"
          value={shortName}
          onChange={(e) => handleShortNameChange(e.target.value)}
          disabled={!isNewProject}
          aria-describedby={shortNameError ? 'short-name-error' : undefined}
          aria-invalid={!!shortNameError}
          className={cn({ 'tw-border-destructive': !!shortNameError })}
        />
        {shortNameError && (
          <p id="short-name-error" className="tw-text-sm tw-text-destructive">
            {shortNameError}
          </p>
        )}
      </div>

      {/* Copyright */}
      <div className="tw-flex tw-flex-col tw-gap-1">
        <Label htmlFor="project-copyright">
          {localizedStrings['%paratextProjectCreation_projectNameForm_copyright%'] || 'Copyright'}
        </Label>
        <Textarea
          id="project-copyright"
          value={copyright}
          onChange={(e) => setCopyright(e.target.value)}
          className="tw-min-h-[80px]"
        />
      </div>

      {/* Registry Warning Ribbon */}
      {showRegistryWarning && (
        <Alert variant="destructive">
          <AlertCircle className="tw-h-4 tw-w-4" />
          <AlertDescription>
            {localizedStrings['%paratextProjectCreation_projectNameForm_registryWarning%'] ||
              'Changing the name of a registered project will affect its registration on the registry.'}
          </AlertDescription>
        </Alert>
      )}

      {/* Action Buttons */}
      <div className="tw-flex tw-justify-end tw-gap-2">
        <Button variant="outline" onClick={onCancel}>
          {localizedStrings['%paratextProjectCreation_projectNameForm_cancel%'] || 'Cancel'}
        </Button>
        <Button variant="default" disabled={!canSubmit} onClick={() => handleSubmit()}>
          {localizedStrings['%paratextProjectCreation_projectNameForm_ok%'] || 'OK'}
        </Button>
      </div>
    </div>
  );
}
